### PR TITLE
Grid logs for mapped instances

### LINKED ISSUE #25616: grid view: first mapped task logs link points to map index: -1, should point to 0
### Apache Airflow version

main (development)

### What happened

Any mapped task will do, but here's a DAG with two:

```python3
with DAG(
    dag_id="zip_tf",
    schedule_interval=timedelta(days=30 * 365),
    start_date=datetime(1970, 1, 1),
) as zip_tf:

    @task
    def get_template():
        return ["hello {}", "goodbye {}"]

    @task
    def get_user():
        return ["foo", "bar"]

    @task
    def salutations(arg):
        print(arg[0].format(arg[1]))

    combined = get_template().zip(get_user())
    salutations.expand(arg=combined)
```

If you run it and navigate to the graph view, you can view the logs for both mapped tasks ("hello foo" and "goodbye bar").  But if you try to do the same thing via the grid view, you can only view the second one ("goodbye bar").  This is because the link to view the first one's logs is pointing to:

`http://localhost:8080/log?dag_id=zip_tf&dag_id=zip_tf&task_id=salutations&execution_date=1970-01-01T00%3A00%3A00%2B00%3A00&map_index=-1`

But `-1` is used for when there are no mapped tasks, not for the first one.  So when you follow the link, you don't see any logs at all.

neg

### What you think should happen instead

the correct logs should appear

### How to reproduce

see above

### Operating System

NixOS (linux)

### Versions of Apache Airflow Providers

n/a

### Deployment

Virtualenv installation

### Deployment details

LocalExecutor

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pierrejeambrun**
https://github.com/apache/airflow/pull/25568 added support for retrieving mapped instance task logs.

This PR adds support for displaying these logs in the Grid details side panel.
- Mapped Instances rows in the table are not selectable anymore. (Actions are done on all of them)
- Mapped Instances rows are clickable and bring a new details page for mapped instances. (We can see the Map Index on top of other detailed information).
- For the new details, logs tab is available and show the logs for this particular map index.
- Breadcrumbs get extended with the map index and the `taskInstance` breadcrumbs becomes clickable in this particular case.
- Extracting tasks actions into its own component.
- Add a button to go back to the dynamic task summary (thanks @bbovenzi)
- Add navigation link the same way we have for normal taks (xcom, details, templates, ...) and remove those links from MappedInstance Table (thanks @bbovenzi)
- Move the MappedInstance Table to its own tab (again thanks @bbovenzi)
- Added a few unit tests.

Tested on:
- Mapped Tasks (obviously) :heavy_check_mark: 
- Groups with mapped task :heavy_check_mark: 
- Logs display, `See More` and `Download` links, and logs filters :heavy_check_mark: 
- When there is multiple pages in the `MappedInstances` Table :heavy_check_mark:
- Breadcrumbs navigation :heavy_check_mark:
- Task actions for all mapped task are working :heavy_check_mark:
- Task actions from the details of a mapped task instance does not work with the `SequentialExecutor` but the calls seems fine. (I didn't modify that part)

Also fixes: https://github.com/apache/airflow/issues/25616

image
image

### CODE REVIEW

**Review by bbovenzi — COMMENTED** [review]
Looking good. A few ideas:

- Let's move the mapped task table to its own tab so on a dynamic task summary you see `Details | Mapped Tasks (count)`
- Let's add an extra "go back to dynamic task summary" button. you can use the breadcrumb but not everyone always realizes that
- let's remove the link buttons from the mapped task table and put that in the mapped task details page like how a normal task instance works. we can then replace that space in the table with a "direct to mapped task logs" button

I'm happy to help pull some of this apart so we can simplify the task instance component.

**Comment by pierrejeambrun** [comment]
I updated the PR and the description.

- Nav link is done, and removed them from the table, nice suggestion. :)
I'm not sure about direct log access, I feel like it is already covered by the preferred tab. If the user preferred tab is 'logs" he will directly land on logs by clicking on the table row otherwise he will land on details.

- Added the button to go back to the dynamic task summary, good idea!

- Separate the mapped task table on a new tab only available for mapped task summary. Unfortunately I do not have the number of mapped instance info available atm. (this could be an improvement).

`Logs` & `Mapped Tasks` tab are mutually exclusive. In terms of 'preferredTab' they act as the same. Meaning you can go from 'mapped' -> 'logs' and reverse without changing tabs.

**Comment by bbovenzi** [comment]
Since we store the map_index in the url, we need to make sure we load an individual mapped task instance details.
Try refreshing the page when you have a single mapped task selected and the details panel will be blank.

Also, a task instance might not have logs (ie: it is scheduled but hasn't run yet). We should handle that case instead of just showing a blank page to a user.

File: airflow/www/static/js/dag/details/taskInstance/BackToTaskSummary.tsx [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+  isMapIndexDefined: boolean;
+  onClick: () => void;
+}
+
+const BackToTaskSummary = ({ isMapIndexDefined, onClick }: Props) => {
+  if (!isMapIndexDefined) return null;
+
+  return (
+    <div>
+      {isMapIndexDefined && (
```
Comment (bbovenzi) [inline airflow/www/static/js/dag/details/taskInstance/BackToTaskSummary.tsx]: Since we have the `return null` above, we can remove the div and conditional block

File: airflow/www/static/js/dag/details/taskInstance/index.tsx [hunk 2]
```diff
@@ -54,18 +52,41 @@ const dagId = getMetaValue('dag_id')!;
...
+  onSelect: (selectionProps: SelectionProps) => void;
 }
 
-const TaskInstance = ({ taskId, runId }: Props) => {
-  const [selectedRows, setSelectedRows] = useState<number[]>([]);
+const TaskInstance = ({
+  taskId, runId, mapIndex, onSelect,
+}: Props) => {
+  const isMapIndexDefined = !(mapIndex === undefined);
+  const selectedRows: number[] = isMapIndexDefined ? [mapIndex] : [];
```
Comment (bbovenzi) [inline airflow/www/static/js/dag/details/taskInstance/index.tsx]: Do we need selectedRows anymore? We got rid of multiselect.

Comment (pierrejeambrun) [reply airflow/www/static/js/dag/details/taskInstance/index.tsx]: SelectedRow is currently used for the task actions. (Empty <=> all mapped, when non empty only run on those mapIndex).

The name is misleading indeed

File: airflow/www/static/js/dag/details/taskInstance/index.tsx [hunk 3]
```diff
@@ -54,18 +52,41 @@ const dagId = getMetaValue('dag_id')!;
...
   const [preferedTabIndex, setPreferedTabIndex] = useState(storageTabIndex);
 
+  const [instance, setInstance] = useState<TaskInstanceType>();
+
   const group = getTask({ taskId, task: groups });
   const run = dagRuns.find((r) => r.runId === runId);
 
+  useEffect(() => {
+    if (!isMapIndexDefined) {
+      setInstance(group?.instances.find((ti) => ti.runId === runId));
```
Comment (bbovenzi) [inline airflow/www/static/js/dag/details/taskInstance/index.tsx]: I don't think we should be using `useEffect` here.  The Details component should probably get the mapped instance info from the API: `/dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/{map_index}`

File: airflow/www/static/js/dag/details/taskInstance/index.tsx (hunk 2 above)
Comment (bbovenzi) [reply airflow/www/static/js/dag/details/taskInstance/index.tsx]: Let's rename it.

File: airflow/www/static/js/dag/details/taskInstance/index.tsx (hunk 3 above)
Comment (bbovenzi) [reply airflow/www/static/js/dag/details/taskInstance/index.tsx]: By using a new API endpoint for a single mapped instance, we can remove a lot of this `useEffect` logic, add autorefresh, and make sure that navigating to this page with `map_index` in the URl, data will load.

**Comment by pierrejeambrun** [comment]
> Since we store the map_index in the url, we need to make sure we load an individual mapped task instance details. Try refreshing the page when you have a single mapped task selected and the details panel will be blank.

I broke that in my last commit :facepalm:...

File: airflow/www/static/js/dag/details/taskInstance/BackToTaskSummary.tsx (hunk 1 above)
Comment (pierrejeambrun) [reply airflow/www/static/js/dag/details/taskInstance/BackToTaskSummary.tsx]: done

File: airflow/www/static/js/dag/details/taskInstance/index.tsx (hunk 2 above)
Comment (pierrejeambrun) [reply airflow/www/static/js/dag/details/taskInstance/index.tsx]: done

**Comment by pierrejeambrun** [comment]
Maybe this is the source of all the confusion.

I checked the autorefresh for mapped task, it is working now.

**Comment by pierrejeambrun** [comment]
> I don't think we should be using `useEffect` here. The Details component should probably get the mapped instance info from the API: `/dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/{map_index}`
True this would simplify the logic. 

Converted to draft while I implement the suggested change to the API.

File: airflow/www/static/js/dag/details/taskInstance/BackToTaskSummary.tsx [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+interface Props {
+  isMapIndexDefined: boolean;
+  onClick: () => void;
+}
+
+const BackToTaskSummary = ({ isMapIndexDefined, onClick }: Props) => {
+  if (!isMapIndexDefined) return null;
+
+  return (
+    <div>
```
Comment (bbovenzi) [inline airflow/www/static/js/dag/details/taskInstance/BackToTaskSummary.tsx]: Looks like the `<div>` got added back again.

Comment (pierrejeambrun) [reply airflow/www/static/js/dag/details/taskInstance/BackToTaskSummary.tsx]: removed

**Comment by pierrejeambrun** [comment]
With your suggestions I was able to come up with a much simpler implementation, that I feel will be more robust as well.

Thanks

File: airflow/www/static/js/dag/useSelection.test.tsx [hunk 5]
```diff
@@ -38,17 +38,19 @@ describe('Test useSelection hook', () => {
...
+    expect(mapIndex).toBeNull();
   });
 
   test.each([
-    { taskId: 'task_1', runId: 'run_1' },
-    { runId: 'run_1', taskId: null },
-    { taskId: 'task_1', runId: null },
+    { taskId: 'task_1', runId: 'run_1', mapIndex: 2 },
+    { runId: 'run_1', taskId: null, mapIndex: null },
+    { taskId: 'task_1', runId: null, mapIndex: 1 },
```
Comment (bbovenzi) [inline airflow/www/static/js/dag/useSelection.test.tsx]: Let's add a test case for `mapIndex: 0` and `mapIndex: -1`.

For -1, we probably need to cast it to null. Currently, I don't see anywhere this pops up in the UI, but a test couldn't hurt.

Comment (pierrejeambrun) [reply airflow/www/static/js/dag/useSelection.test.tsx]: Done :)

**Review by bbovenzi — APPROVED** [review]
Great work!

**Comment by pierrejeambrun** [comment]
Thank you Brent :)
