### PR TITLE
Show asset extra in asset list

### LINKED ISSUE #57566: Asset UI does not display extra metadata in Assets views
### Apache Airflow version

3.1.1

### If "Other Airflow 2/3 version" selected, which one?

_No response_

### What happened?

When viewing Assets in the Airflow 3.1.1 UI, the context-specific metadata attached to assets is not shown anywhere in the UI. For example, if an asset is defined with `extra={...}` (see below), this information is not visible in the asset event details, asset event list, or any related asset views. This makes it difficult for users to see or audit static asset metadata during asset event inspection. Only AssetEvent extra is displayed.

```python
Asset(
    's3://bucket/mydata.csv',
    extra={'owner': 'Sir Airflow'},
)
```

### What you think should happen instead?

The UI should display the `extra` dictionary (static asset metadata) somewhere in the Assets view, ideally together with other asset details. This could be shown as a dedicated section, or grouped with asset information in the event card or detail modal. Showing this field would allow users to see static asset metadata alongside event-specific metadata (`extra`).

### How to reproduce

1. Create an asset with `extra={...}`.
2. Emit one or more asset events for the asset.
3. Open the Assets view in the Airflow UI.
4. Observe that the static asset metadata (`extra`) is not displayed anywhere.

### Operating System

docker

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pierrejeambrun**
closes: https://github.com/apache/airflow/issues/57566

Similarly to xcoms and audit logs, displays assets extra in the table view. 

https://github.com/user-attachments/assets/b7968a39-c100-4e00-baef-bdc5993f1661

Asset details view already displays extras:
Screenshot 2025-12-08 at 12 20 55

### CODE REVIEW

**Review by bbovenzi — APPROVED** [review]

File: airflow-core/src/airflow/ui/src/pages/Events/Events.tsx [hunk 1]
```diff
@@ -221,8 +221,8 @@ export const Events = () => {
       <Flex alignItems="center" justifyContent="space-between">
         <EventsFilters urlDagId={dagId} urlRunId={runId} urlTaskId={taskId} />
         <ExpandCollapseButtons
-          collapseLabel={translate("auditLog.actions.collapseAllExtra")}
-          expandLabel={translate("auditLog.actions.expandAllExtra")}
+          collapseLabel={translate("collapseAllExtra")}
+          expandLabel={translate("expandAllExtra")}
```
Comment (choo121600) [inline airflow-core/src/airflow/ui/src/pages/Events/Events.tsx]:
```suggestion
          collapseLabel={translate("common:collapseAllExtra")}
          expandLabel={translate("common:expandAllExtra")}
```
