### PR TITLE
Explicitly set table ordering

### LINKED ISSUE #60576: Inconsistent table sorting state
### Apache Airflow version

3.1.6

### If "Other Airflow 3 version" selected, which one?

_No response_

### What happened?

On the 'Task Instances' view the 'Start Date' column will not sort in descending order, only toggling between unsorted and ascending sort.

### What you think should happen instead?

'Start Date' should be sortable in descending order. This is important to be able to view tasks that have been run recently at an aggregate level.

### How to reproduce

run `airflow standalone` using default configuration

go to http://localhost:8080/task_instances

select the 'Start Date' column to toggle sorting

### Operating System

Ubuntu 22.04.5 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes | 10.12.1rc1
apache-airflow-providers-common-compat   | 1.12.0rc1 
apache-airflow-providers-common-io       | 1.7.0     
apache-airflow-providers-common-sql      | 1.30.2    
apache-airflow-providers-smtp            | 2.4.1     
apache-airflow-providers-standard        | 1.10.2   

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

airflow standalone running on python 3.11 virtual environment

### Anything else?

OS: Mac OS Sequoia 15.7.3
Browser: Firefox 146.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by bbovenzi**
The sort handler for tansStack/table was inconsistent with when it cycled between sort states if it had a default value. Implementing it ourselves makes sure it always appears.

Closes https://github.com/apache/airflow/issues/60576

Also, added add a placeholder data of the previous data to prevent the whole table from showing a loading page when a user does change the sorting.

##### Was generative AI tooling used to co-author this PR?

- [ ] 

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/pages/TaskInstances/TaskInstances.tsx [hunk 1]
```diff
@@ -235,7 +235,7 @@ export const TaskInstances = () => {
   });
   const { pagination, sorting } = tableURLState;
   const [sort] = sorting;
-  const orderBy = sort ? [`${sort.desc ? "-" : ""}${sort.id}`] : ["-start_date", "-run_after"];
+  const orderBy = sort ? [`${sort.desc ? "-" : ""}${sort.id}`] : ["-run_after"];
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/TaskInstances/TaskInstances.tsx]: The second sort criteria was explicitely added in https://github.com/apache/airflow/pull/53804. I'd prefer we keep it to avoid any confusion, also it makes sense if there are a lot of TIs and some of them have the same `start_date`. (instead of defaulting to 'task_id' as a second criteria)

**Review by pierrejeambrun — COMMENTED** [review]
Just one remark otherwise looking good to me.

> The sort handler for tansStack/table was inconsistent with when it cycled between sort states if it had a default value. Implementing it ourselves makes sure it always appears.

I wasn't able to reproduce this, can you give more details as to what was happening? (for me it was correctly switching for desc/asc/default).

File: airflow-core/src/airflow/ui/src/pages/TaskInstances/TaskInstances.tsx (hunk 1 above)
Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/pages/TaskInstances/TaskInstances.tsx]: I found the real issue and was able to simplify this PR a lot

**Review by pierrejeambrun — APPROVED** [review]
Cool!

File: airflow-core/src/airflow/ui/src/pages/TaskInstances/TaskInstances.tsx (hunk 1 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/TaskInstances/TaskInstances.tsx]: Cool!

**Review by choo121600 — COMMENTED** [review]
Cool, looks good.
It looks like the e2e tests are failing. Could you please check?
