### PR TITLE
fix(UI): show 403 error when unauthorized user reparses DAG

### LINKED ISSUE #61459: When a Viewer/Author tries to reparse a DAG, the UI shows generic failed to reparse error
### Apache Airflow version

3.1.7

### If "Other Airflow 3 version" selected, which one?

_No response_

### What happened?

When a Viewer/Author tries to reparse a DAG, the UI shows:
“Dag Failed to Reparse. Dag parsing request failed. There could be pending parsing requests yet to be processed.”
This sounds like a transient system issue, whereas the actual reason is lack of permission.

### What you think should happen instead?

Should show a 403 message

### How to reproduce

Testing during DAG level roles implementation on the Astronomer Astro client

### Operating System

macOS

### Versions of Apache Airflow Providers

_No response_

### Deployment

Astronomer

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by liamkernan**
When a Viewer/Author tries to reparse a DAG, the API correctly returns 403 but the UI shows a misleading generic error ("Dag parsing request failed"). This checks the error status code and shows an "Access Denied" toast for 403 responses instead.

Closes #61459

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by bbovenzi** [comment]
Can we check the actual API error response to see if we're just presenting the wrong message? It would be better to send and display the correct errors from the API instead of manually creating error messages in the UI

File: airflow-core/src/airflow/ui/src/queries/useDagParsing.ts [hunk 1]
```diff
@@ -24,16 +24,23 @@ import {
...
+import { ApiError } from "openapi/requests";
 import { toaster } from "src/components/ui";
 
 export const useDagParsing = ({ dagId }: { readonly dagId: string }) => {
   const queryClient = useQueryClient();
   const { t: translate } = useTranslation("dag");
 
-  const onError = () => {
+  const onError = (error: unknown) => {
+    const isForbidden = error instanceof ApiError && error.status === 403;
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/queries/useDagParsing.ts]: Nit:

In other places we don't check the `instanceof ApiError` to keep things consistent you can:
```
error?.status === 403 # if the compiler is happy
```

Or 
```
(error as ExpandedApiError).status === 403
```

**Review by pierrejeambrun — APPROVED** [review]
LGTM and working as expected, thanks.

Just one nit.

**Comment by pierrejeambrun** [comment]
> Can we check the actual API error response to see if we're just presenting the wrong message? It would be better to send and display the correct errors from the API instead of manually creating error messages in the UI

API just returns `{detail: "Forbidden"}` on 403. Which is correct, but displaying that raw isn't great for users. (We do that at other places).

We can globally remap the `403` with 'details: Forbidden' to a generic message. "You do not have permission to perform this action". Which will prevent the need from doing a mapping between the front-end while still displaying something a little bit more explicit.

File: airflow-core/src/airflow/ui/public/i18n/locales/en/dag.json [hunk 2]
```diff
@@ -149,6 +149,10 @@
         "description": "Dag parsing request failed. There could be pending parsing requests yet to be processed.",
         "title": "Dag Failed to Reparse"
       },
+      "forbidden": {
+        "description": "You do not have permission to reparse this DAG.",
+        "title": "Access Denied"
+      },
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/public/i18n/locales/en/dag.json]: Here we can move that to 'common.json' and update this to a generic message.
`"You do not have permission to perform this action."`

File: airflow-core/src/airflow/ui/src/queries/useDagParsing.ts [hunk 3]
```diff
@@ -24,16 +24,23 @@ import {
...
     toaster.create({
-      description: translate("parse.toaster.error.description"),
-      title: translate("parse.toaster.error.title"),
+      description: isForbidden
+        ? translate("parse.toaster.forbidden.description")
+        : translate("parse.toaster.error.description"),
+      title: isForbidden
+        ? translate("parse.toaster.forbidden.title")
+        : translate("parse.toaster.error.title"),
       type: "error",
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/queries/useDagParsing.ts]: Move this toaster creation to a common function handler use it everywhere we create an 'error' toaster basically. `const createToaster = (error ?:) => {}`

Then https://github.com/apache/airflow/pull/61588 will take care of removing all the calls to the manual toaster handler and centralize this into a MutationCache.

**Comment by bbovenzi** [comment]
Yes lets make a single generic 403 message to use across the UI

**Review by pierrejeambrun — COMMENTED** [review]
Update: I chatted with Brent, we believe a generic handler is better

**Comment by eladkal** [comment]
@liamkernan can you handle the open comments?

File: airflow-core/src/airflow/ui/public/i18n/locales/en/dag.json (hunk 2 above)
Comment (liamkernan) [reply airflow-core/src/airflow/ui/public/i18n/locales/en/dag.json]: done, I moved the forbidden toast copy out of dag.json into common.json and updated it to the generic wording: “You do not have permission to perform this action.”
useDagParsing now references the common key so this message is reusable across UI mutations.

File: airflow-core/src/airflow/ui/src/queries/useDagParsing.ts (hunk 1 above)
Comment (liamkernan) [reply airflow-core/src/airflow/ui/src/queries/useDagParsing.ts]: Updated per suggestion, I removed the instanceof ApiError check and now use (error as ExpandedApiError).status === 403, consistent with existing patterns in the codebase.

File: airflow-core/src/airflow/ui/src/queries/useDagParsing.ts (hunk 3 above)
Comment (liamkernan) [reply airflow-core/src/airflow/ui/src/queries/useDagParsing.ts]: I added a shared error-toast helper at src/queries/createErrorToaster.ts and switched useDagParsing to use it.
The helper centralizes 403 -> common access denied toast, with fallback title/description for non-403 errors. This should make follow-up centralization in #61588 straightforward.

**Comment by liamkernan** [comment]
Finished; let me know if there's anything else I can tweak or improve.

File: airflow-core/src/airflow/ui/src/components/ui/createErrorToaster.ts [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+    const isForbidden = (error as ExpandedApiError).status === 403;
+
+    toaster.create({
+      description: isForbidden
+        ? translate("toaster.forbidden.description", { ns: "common" })
+        : fallbackMessage.description,
+      title: isForbidden ? translate("toaster.forbidden.title", { ns: "common" }) : fallbackMessage.title,
+      type: "error",
+    });
+  };
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/components/ui/createErrorToaster.ts:40]: Move this to 'components/ui/Toaster'.

**Review by pierrejeambrun — COMMENTED** [review]
Looking good, just one nit.

File: airflow-core/src/airflow/ui/src/components/ui/createErrorToaster.ts (hunk 4 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/components/ui/createErrorToaster.ts:40]: I just pushed an update.

**Review by choo121600 — APPROVED** [review]
