### PR TITLE
fix(ui): unique keys for pagination ellipses

### LINKED ISSUE #62350: Web UI - Incorrect rendering of pagination ellipses
### Apache Airflow version

3.1.7

### If "Other Airflow 3 version" selected, which one?

_No response_

### What happened?

Pagination ellipses don’t render correctly when the page range back to [1 2 3 4 5]. 

See the video:

https://github.com/user-attachments/assets/c95e4db0-bcaf-4d8c-b5d1-4f5c8b86dfd2

### What you think should happen instead?

Pagination ellipses should disappear when the page range returns to [1 2 3 4 5].

### How to reproduce

1. Navigate to the Dag Runs page
2. Scroll down to the bottom
3. Click page 4 and page 3 back and forth.

### Operating System

MacOS

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by yjaw**
The current ellipses share the same key ("ellipsis"), which may cause rendering bugs. Added the page value to each ellipsis key to ensure they are unique.

before:
https://github.com/user-attachments/assets/2a27167f-f923-4973-8710-18bfcfd8615b

after:
https://github.com/user-attachments/assets/053b20d1-b676-4b98-bbc3-25658106250a

closes: #62350 
 

---

##### Was generative AI tooling used to co-author this PR?

- [x] Yes (please specify the tool below)

Generated-by: [Gemini and Antigravity] following [the guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#gen-ai-assisted-contributions)

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).
* *

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/components/ui/Pagination/Items.tsx [hunk 1]
```diff
@@ -24,13 +24,15 @@ import { Item } from "./Item";
...
-          <Ellipsis index={index} key={page.type} {...props} />
-        ) : (
-          <Item key={page.value} type="page" value={page.value} {...props} />
-        ),
-      )
+      pages.map((page, index) => {
+        if (page.type === "ellipsis") {
+          const prevVal = (pages[index - 1] as { value: number }).value;
+
+          return <Ellipsis index={index} key={`ellipsis-${prevVal}`} {...props} />;
```
Comment (guan404ming) [inline airflow-core/src/airflow/ui/src/components/ui/Pagination/Items.tsx]:
```suggestion
          return <Ellipsis index={index} key={`ellipsis-${index}`} {...props} />;
```

Could we try to uses index as the key discriminator? Keeping the original ternary style and avoiding the unsafe type cast.

Comment (yjaw) [reply airflow-core/src/airflow/ui/src/components/ui/Pagination/Items.tsx]: I also think that using an index is more elegant and eliminates the concern of an array out-of-range error. However, it appears that the linter does not allow us to use an index as a key. I agree that we cloud try other way to make key unique.

here is error message:
error  Do not use Array index in keys  react/no-array-index-key
✖ 1 problem (1 error, 0 warnings)

Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/components/ui/Pagination/Items.tsx]: Since the ellipsis items genuinely have no stable identifier, I think we use index but suppress the lint rule for this specific line. What do you think?

Comment (yjaw) [reply airflow-core/src/airflow/ui/src/components/ui/Pagination/Items.tsx]: I think using index won't be a problem in this scenario. How can I bypass linter?

Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/components/ui/Pagination/Items.tsx]: use `// eslint-disable-next-line react/no-array-index-key`

**Review by pierrejeambrun — APPROVED** [review]

**Review by guan404ming — APPROVED** [review]

**Comment by guan404ming** [comment]
Thanks for the update.
