### PR TITLE
Fix gantt chart queued duration when queued_dttm is greater than start_date for deferred tasks.

### LINKED ISSUE #35288: Incorrect queued duration for deferred tasks in gantt view
### Apache Airflow version

main (development)

### What happened

Gantt view calculates the diff between start date and queued at values to show queued duration. In case of deferred tasks that tasks get re-queued when the triggerer returns an event causing queued at to be greater than start date. This causes incorrect values to be shown in the UI. I am not sure how to fix this. Maybe queued duration can be not shown on the tooltip when queued time is greater than start time.

Screenshot from 2023-10-31 09-15-54

### What you think should happen instead

_No response_

### How to reproduce

1. Trigger the below dag
2. `touch /tmp/a` to ensure triggerer returns an event.
3. Check for queued duration value in gantt view.

```python
from __future__ import annotations

from datetime import datetime

from airflow import DAG
from airflow.models.baseoperator import BaseOperator
from airflow.triggers.file import FileTrigger


class FileCheckOperator(BaseOperator):
    def __init__(self, filepath, **kwargs):
        self.filepath = filepath
        super().__init__(**kwargs)

    def execute(self, context):
        self.defer(
            trigger=FileTrigger(filepath=self.filepath),
            method_name="execute_complete",
        )

    def execute_complete(self, context, event=None):
        pass


with DAG(
    dag_id="file_trigger",
    start_date=datetime(2021, 1, 1),
    catchup=False,
    schedule_interval=None,
) as dag:
    t1 = FileCheckOperator(task_id="t1", filepath="/tmp/a")
    t2 = FileCheckOperator(task_id="t2", filepath="/tmp/b")

    t1
    t2
```

### Operating System

Ubuntu

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tirkarthi**
closes: #35288
related: #35288 

When a task is deferred then the same attempt is used to queue and resume causing the queued_dttm to be greater than start_date for an execution. This causes queued duration to be displayed with incorrect value taking queued_dttm - start_date which is not correct since start_date should always be greater than queued time. Also this causes start offset and to have a fixed queued duration bar width of 5. start offset and queued duration min width are shown only when queued_dttm is valid by being greater than start_date.

Before patch : (Incorrect queued duration of 23 hours and start of the bar is incorrect)

gantt_before_patch

After patch : (queued duration is 0 since queued_dttm is greater than start_date. start_date position is also correct in gantt as per start_date)

gantt_after

Sample dag : 

```python
from __future__ import annotations

from datetime import datetime

from airflow import DAG
from airflow.models.baseoperator import BaseOperator
from airflow.triggers.file import FileTrigger


class FileCheckOperator(BaseOperator):
    def __init__(self, filepath, **kwargs):
        self.filepath = filepath
        super().__init__(**kwargs)

    def execute(self, context):
        self.defer(
            trigger=FileTrigger(filepath=self.filepath),
            method_name="execute_complete",
        )

    def execute_complete(self, context, event=None):
        pass


with DAG(
    dag_id="file_trigger",
    start_date=datetime(2021, 1, 1),
    catchup=False,
    schedule_interval=None,
) as dag:
    t1 = FileCheckOperator(task_id="t1", filepath="/tmp/a")
    t2 = FileCheckOperator(task_id="t2", filepath="/tmp/b")

    t1
    t2
```

### CODE REVIEW

File: airflow/www/static/js/dag/details/gantt/Row.tsx [hunk 1]
```diff
@@ -53,17 +53,21 @@ const Row = ({
   const instance = task.instances.find((ti) => ti.runId === runId);
   const isSelected = taskId === instance?.taskId;
   const hasQueuedDttm = !!instance?.queuedDttm;
+  const validQueuedDttm =
```
Comment (bbovenzi) [inline airflow/www/static/js/dag/details/gantt/Row.tsx]: I feel like we can combine these two variables to `hasValidQueuedDttm`

File: airflow/www/static/js/dag/details/gantt/Row.tsx [hunk 2]
```diff
@@ -53,17 +53,21 @@ const Row = ({
...
+    hasQueuedDttm &&
+    (instance?.startDate && instance?.queuedDttm
+      ? instance.queuedDttm < instance.startDate
+      : true);
   const isOpen = openGroupIds.includes(task.id || "");
 
   // Calculate durations in ms
   const taskDuration = getDuration(instance?.startDate, instance?.endDate);
-  const queuedDuration = hasQueuedDttm
+  const queuedDuration = validQueuedDttm
```
Comment (bbovenzi) [inline airflow/www/static/js/dag/details/gantt/Row.tsx:65]: Isn't validQueuedDttm here a boolean value?

File: airflow/www/static/js/dag/details/gantt/Row.tsx (hunk 1 above)
Comment (tirkarthi) [reply airflow/www/static/js/dag/details/gantt/Row.tsx]: There is a case where the task is queued to have queued_dttm and there is no start_date since the task has not started where hasQueuedDttm is true but validQueuedDttm won't be true since start_date is null and based on hasQueuedDttm the minimum bar for needs to be present.

Comment (tirkarthi) [reply airflow/www/static/js/dag/details/gantt/Row.tsx]: Ok, please ignore I see I combined them later and hasQueuedDttm is not used except for this check. Makes sense to combine them.

**Review by bbovenzi — APPROVED** [review]
