### PR TITLE
Fixes constraint generation for pypi providers

### LINKED ISSUE #15463: Inconsistency between the setup.py and the constraints file
**Apache Airflow version**: 2.0.2

**What happened**:

Airflow's 2.0.2's [constraints file](https://raw.githubusercontent.com/apache/airflow/constraints-2.0.2/constraints-3.8.txt) has used newer `oauthlib==3.1.0` and `request-oauthlib==1.3.0` than 2.0.1's [constraints file](https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.8.txt)

However both 2.0.2's [setup.py](https://github.com/apache/airflow/blob/10023fdd65fa78033e7125d3d8103b63c127056e/setup.py#L282-L286) and 2.0.1's [setup.py](https://github.com/apache/airflow/blob/beb8af5ac6c438c29e2c186145115fb1334a3735/setup.py#L273) don't allow these new versions

Image build with `google_auth` being an "extra"  will fail if using `pip==21.0.1` **without** the `--use-deprecated=legacy-resolver` flag.

Another option is to use `pip==20.2.4`.

**What you expected to happen**:

The package versions in `setup.py` and `constraints-3.8.txt` should be consistent with each other.

**How to reproduce it**:

`docker build` with the following in the `Dockerfile`:
```
pip install apache-airflow[password,celery,redis,postgres,hive,jdbc,mysql,statsd,ssh,google_auth]==2.0.2 \
    --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.0.2/constraints-3.8.txt
```
image build failed with

```
ERROR: Could not find a version that satisfies the requirement oauthlib!=2.0.3,!=2.0.4,!=2.0.5,<3.0.0,>=1.1.2; extra == "google_auth" (from apache-airflow[celery,google-auth,hive,jdbc,mysql,password,postgres,redis,ssh,statsd])
ERROR: No matching distribution found for oauthlib!=2.0.3,!=2.0.4,!=2.0.5,<3.0.0,>=1.1.2; extra == "google_auth"
```

### PR DESCRIPTION
**Pull request by potiuk**
The constraints generated from PyPI version of providers, missed
core requirements of Airflow, therefore the constraints were not
consistent with setup.py core requirements.

Fixes: #15463

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

File: scripts/in_container/_in_container_utils.sh [hunk 1]
```diff
@@ -318,6 +318,7 @@ function install_local_airflow_with_eager_upgrade() {
 
 
 function install_all_providers_from_pypi_with_eager_upgrade() {
+    NO_PROVIDERS_EXTRAS=$(python -c 'import setup; print(",".join(setup.CORE_EXTRAS_REQUIREMENTS.keys()))')
```
Comment (uranusjr) [inline scripts/in_container/_in_container_utils.sh]:
```suggestion
    NO_PROVIDERS_EXTRAS=$(python -c 'import setup; print(",".join(setup.CORE_EXTRAS_REQUIREMENTS))')
```

**Review by ashb — APPROVED** [review]
