### PR TITLE
AIP-38 Mark TI as success/failed

### LINKED ISSUE #46137: AIP-38 Mark TI as success / failed
### Body

Related to https://github.com/apache/airflow/issues/43712

### Committer

- [x] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### PR DESCRIPTION
**Pull request by pierrejeambrun**
Depends on https://github.com/apache/airflow/pull/46018, only last commit is relevant:

Closes: https://github.com/apache/airflow/issues/46137
Screenshot 2025-01-27 at 17 48 44
Screenshot 2025-01-27 at 17 48 32
Screenshot 2025-01-27 at 17 48 52
Screenshot 2025-01-27 at 17 49 12
Screenshot 2025-01-27 at 17 49 35
Screenshot 2025-01-27 at 17 50 10

### CODE REVIEW

**Comment by pierrejeambrun** [comment]
Draft. Some refactoring + cleaning is required before being ready for review.

File: airflow/ui/src/components/MarkAs/MarkAsAccordion.tsx [hunk 1]
```diff
@@ -16,57 +16,95 @@
...
+              as={VStack}
+              gap="0"
+              height="200px"
+              overflowY="auto"
+              width="100%"
+            >
+              {Boolean(note) ? (
+                <ReactMarkdown>{note}</ReactMarkdown>
+              ) : (
+                <Text color="gray" opacity={0.6}>
```
Comment (bbovenzi) [inline airflow/ui/src/components/MarkAs/MarkAsAccordion.tsx]: We probably want to use something like `text.subtle`

Screenshot 2025-01-27 at 12 29 35 PM

File: airflow/ui/src/queries/usePatchTaskInstanceDryRun.ts [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+        requestBody,
+        taskId,
+      }) as TData,
+    queryKey: [
+      "patchTaskInstanceDryRun",
+      dagId,
+      dagRunId,
+      taskId,
+      mapIndex,
+      { ...requestBody, note: Boolean(requestBody.note) },
```
Comment (bbovenzi) [inline airflow/ui/src/queries/usePatchTaskInstanceDryRun.ts]: Why is note a boolean?

File: airflow/ui/src/components/MarkAs/MarkAsAccordion.tsx [hunk 3]
```diff
@@ -16,57 +16,95 @@
...
+                columns={columns}
+                data={affectedTasks.task_instances}
+                displayMode="table"
+                initialState={{
+                  pagination: {
+                    pageIndex: 0,
+                    pageSize: affectedTasks.total_entries,
+                  },
+                  sorting: [],
+                }}
```
Comment (bbovenzi) [inline airflow/ui/src/components/MarkAs/MarkAsAccordion.tsx]: I'm not sure we need to set initialState if this isnt paginated or sortable

File: airflow/ui/src/components/MarkAs/MarkAsAccordion.tsx (hunk 1 above)
Comment (pierrejeambrun) [reply airflow/ui/src/components/MarkAs/MarkAsAccordion.tsx]: Yes, the reason I did that in the first place is because I wanted the 'placeholder' of the markdown rendering to be exactly the same as the placeholder of the `Editable.Textarea` so there's no change when we focus on the item. But  indeed it won't play nice with dark mode.

I switched to `fg.suble`

File: airflow/ui/src/queries/usePatchTaskInstanceDryRun.ts (hunk 2 above)
Comment (pierrejeambrun) [reply airflow/ui/src/queries/usePatchTaskInstanceDryRun.ts]: The idea was to cache the request on 'there is a note' or 'there is not a note' in the update request. We don't want the dry_run query to trigger on every keystroke, but I figured it's simpler to not specify the `note` at all in the caching key. It's just more verbose as I can't do anymore:
```js
{...requestBody}
```

But something like that just to omit 1 key:
```js
      requestBody.new_state,
      requestBody.include_downstream,
      requestBody.include_future,
      requestBody.include_past,
      requestBody.include_upstream,
```

File: airflow/ui/src/components/MarkAs/MarkAsAccordion.tsx (hunk 3 above)
Comment (pierrejeambrun) [reply airflow/ui/src/components/MarkAs/MarkAsAccordion.tsx]: You are right, thanks, updated.

**Review by bbovenzi — APPROVED** [review]
Looking good, but we may want to change how we use the statusbadge for the dropdown

Screenshot 2025-01-28 at 11 15 27 AM

**Comment by pierrejeambrun** [comment]
> Looking good, but we may want to change how we use the statusbadge for the dropdown

Yes that's not great. I just added a small marging for now. So it looks a bit better but not ideal.

Screenshot 2025-01-28 at 17 28 33
