### PR TITLE
enhance error message for `breeze --backend none` to suggest setting a valid backend

### LINKED ISSUE #52315: Improve error message when using `start-airflow` with `--backend none` in Breeze
### Description

related https://apache-airflow.slack.com/archives/CQ9QHSFQX/p1750917889606339?thread_ts=1750915462.814829&cid=CQ9QHSFQX

### Problem

Currently, when users run `breeze --backend none` and attempt to use `start-airflow`, it results in a cryptic error or unexpected behavior. This can be confusing, especially for newcomers who might not realize that the `none` backend is intended for non-DB tests and is not compatible with `start-airflow`.

Image

### Proposed Improvement

Improve the developer experience by adding a clearer error or warning message in `start-airflow` when the backend is set to `none`.

### Use case/motivation

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by kyungjunleeme**
Currently, running the following command:

```
breeze start-airflow --backend=none
```
results in an unclear error caused by an invalid SQLAlchemy connection string. This can confuse users who may not realize that --backend=none disables the Airflow database entirely and is not compatible with start-airflow.

This PR introduces an explicit error message to prevent this misuse:

```
ERROR: 'start-airflow' cannot be used with --backend=none.
Supported database backends are: sqlite, postgres, mysql, mssql.
Please specify one using '--backend'.
```
This change improves the user experience by clearly indicating what went wrong and how to fix it.

closes: https://github.com/apache/airflow/issues/52315

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: scripts/in_container/check_environment.sh [hunk 1]
```diff
@@ -61,7 +61,9 @@ function check_db_backend {
     elif [[ ${BACKEND} == "sqlite" ]]; then
         return
     elif [[ ${BACKEND} == "none" ]]; then
-        echo "${COLOR_YELLOW}WARNING: Using no database backend!${COLOR_RESET}"
+        echo "${COLOR_RED}ERROR: 'start-airflow' cannot be used with --backend=none.${COLOR_RESET}"
```
Comment (amoghrajesh) [inline scripts/in_container/check_environment.sh]:
```suggestion
        echo "${COLOR_RED}ERROR: Cannot start airflow with --backend=none.${COLOR_RESET}"
```

File: scripts/in_container/check_environment.sh [hunk 2]
```diff
@@ -61,7 +61,9 @@ function check_db_backend {
...
+        echo "${COLOR_RED}Supported database backends are: sqlite, postgres, mysql, mssql.${COLOR_RESET}"
```
Comment (amoghrajesh) [inline scripts/in_container/check_environment.sh]: mssql is dropped. I suggest you display this from `ALLOWED_BACKENDS` variable.

Comment (kyungjunleeme) [reply scripts/in_container/check_environment.sh]: @amoghrajesh okay, thanks, I follow ur comment.

File: scripts/in_container/check_environment.sh [hunk 3]
```diff
@@ -61,10 +61,12 @@ function check_db_backend {
...
         return
     elif [[ ${BACKEND} == "none" ]]; then
-        echo "${COLOR_YELLOW}WARNING: Using no database backend!${COLOR_RESET}"
+        echo "${COLOR_RED}ERROR: Cannot start airflow with --backend=none.${COLOR_RESET}"
+        echo "${COLOR_RED}Supported values are: [postgres,mysql,sqlite]${COLOR_RESET}"
+        echo "${COLOR_RED}Please specify one using '--backend'.${COLOR_RESET}"
         return
     else
-        echo "Unknown backend. Supported values: [postgres,mysql,mssql,sqlite]. Current value: [${BACKEND}]"
+        echo "Unknown backend. Supported values: [postgres,mysql,sqlite]. Current value: [${BACKEND}]"
```
Comment (kyungjunleeme) [inline scripts/in_container/check_environment.sh]: @amoghrajesh I made additional changes to the else block as well, based on the feedback you provided earlier.

Comment (amoghrajesh) [reply scripts/in_container/check_environment.sh]: Sounds good.

**Review by amoghrajesh — APPROVED** [review]

File: scripts/in_container/check_environment.sh (hunk 2 above)
Comment (amoghrajesh) [reply scripts/in_container/check_environment.sh]: Sounds fine

**Comment by kyungjunleeme** [comment]
@amoghrajesh thank you for reviewing my pr. could you merge for my pr?

File: scripts/in_container/check_environment.sh [hunk 4]
```diff
@@ -61,10 +61,12 @@ function check_db_backend {
     elif [[ ${BACKEND} == "sqlite" ]]; then
         return
     elif [[ ${BACKEND} == "none" ]]; then
-        echo "${COLOR_YELLOW}WARNING: Using no database backend!${COLOR_RESET}"
+        echo "${COLOR_RED}ERROR: Cannot start airflow with --backend=none.${COLOR_RESET}"
```
Comment (potiuk) [inline scripts/in_container/check_environment.sh]: Nice. But I think we should only to it when `START_AIRFLOW` variable is set - and then do `sys.exit(1)` - generally speaking, when we do RED (error) we should stop the current operation rather than let it fall through - and I think it is really "error" when you try to run "start-airflow" - but in other cases warning is good.

So: 
* print the warning (yellow) first as it was
* if START_AIRFLOW is "true" -> print error and exit 1 
* also woudl be nice to have to add red colour to the "Unknown backend" just few lines down

Comment (kyungjunleeme) [reply scripts/in_container/check_environment.sh]: @potiuk Thank you for commenting my pr. I follow ur comment. and then, I will request review.

File: scripts/in_container/check_environment.sh [hunk 5]
```diff
@@ -61,10 +61,16 @@ function check_db_backend {
     elif [[ ${BACKEND} == "sqlite" ]]; then
         return
     elif [[ ${BACKEND} == "none" ]]; then
-        echo "${COLOR_YELLOW}WARNING: Using no database backend!${COLOR_RESET}"
-        return
+        echo "${COLOR_YELLOW}WARNING: Using no database backend${COLOR_RESET}"
+
+        if [[ ${START_AIRFLOW} == "true" ]]; then
```
Comment (potiuk) [inline scripts/in_container/check_environment.sh]:
```suggestion
        if [[ ${START_AIRFLOW=} == "true" ]]; then
```

Otherwise it will fail if START_AIRFLOW is not set at all.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
NICE! 
image

File: scripts/in_container/check_environment.sh (hunk 5 above)
Comment (kyungjunleeme) [reply scripts/in_container/check_environment.sh]: @potiuk Oh sorry, next time, I do not reproduce mistake like that. Thank you

Comment (potiuk) [reply scripts/in_container/check_environment.sh]: No... No worries :). It's a bit dark-magic knowledge of Bash and the fact that we set the options to fail when variable is not declared. So you have all the right to **not** know that :)

Comment (kyungjunleeme) [reply scripts/in_container/check_environment.sh]: ah ha Thank you!, next time I will post with test result output
