### PR TITLE
Fix slow log scrolling for large task logs

### LINKED ISSUE #51788: Scrolling in logs does not work properly.
### Apache Airflow version

3.0.2

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

I did a clean installation of Airflow 3.0.2 and when trying to scroll the logs the following behavior occurs:

Image

Even though it seems to be at the end, I need a few seconds to manually move down until I reach the end...

### What you think should happen instead?

_No response_

### How to reproduce

Fix Scroll behavior

### Operating System

Running docker compose on Debian 12

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

Always

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by guan404ming**
## Related Issue

Ref #54447
Closes #51788

## Why

Scrolling to the end of large log files was slow because the virtualizer had to compute positions for all rows. This fix:                                                                                                      

## How
                                                                                                                                                      
- Use scrollToOffset with direct offset calculation for instant jumps                                                                            
- Add useLocation hook so clicking a log line highlights it reactively                                                                                                                                                                           
- Extract scroll utilities to utils.ts

https://github.com/user-attachments/assets/50532281-b296-454b-a1d5-bdbfd9faa217

---

##### Was generative AI tooling used to co-author this PR?

- [x] Yes (please specify the tool below)
Claude Code

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -15,6 +15,7 @@ airflow-core/src/airflow/ui/coverage/
 airflow/git_version
 airflow/ui/coverage/
 logs/
+!airflow-core/src/airflow/ui/**/Logs/
```
Comment (pierrejeambrun) [inline .gitignore]: I don't think that's relevant to the PR, we should remove it.

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/TaskLogContent.tsx [hunk 2]
```diff
@@ -92,14 +99,55 @@ export const TaskLogContent = ({ error, isLoading, logError, parsedLogs, wrap }:
...
+
+    if (!el) {
+      rowVirtualizer.scrollToIndex(targetIndex, { align: "start" });
+
+      return;
     }
+
+    const vItem = rowVirtualizer.getVirtualItems().find((virtualRow) => virtualRow.index === targetIndex);
+    const approxPerItem = 20;
+    const targetPosition = vItem?.start ?? targetIndex * approxPerItem;
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/TaskLogContent.tsx]: I don't think this is working well if the logs are wrapped.

I would keep this as a follow up PR, so we can focus this one on fixing the scroll to top / bottom issue.

**Review by pierrejeambrun — COMMENTED** [review]
Thanks for the PR, would be great to have this scroll to bottom / top fixed!

Just a few comments, but tested locally and working as expected, we just need to trim down the PR to focus on this part only while we figure out the rest.

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/TaskLogContent.tsx (hunk 2 above)
Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/TaskLogContent.tsx]: +1 let's make this two PRs

Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/TaskLogContent.tsx]: Sure, I've trimmed the pr to focus on fixing the scroll.

File: .gitignore (hunk 1 above)
Comment (guan404ming) [reply .gitignore]: Sure, I've removed it. This change is because my Git setup was somehow ignoring the folder `airflow-core/src/airflow/ui/**/Logs/`. I believe I can fix this myself by adjusting my local configuration.

**Review by bbovenzi — APPROVED** [review]

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/utils.ts [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+
+  element.scrollTop = offset;
+
+  requestAnimationFrame(() => {
+    element.scrollTop = offset;
+    requestAnimationFrame(() => {
+      element.scrollTop = offset;
+      const lastItem = element.querySelector<HTMLElement>(
+        `[data-testid="virtualized-item-${itemCount - 1}"]`,
+      );
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/utils.ts]: Why are we nesting `requestAnimationFrame`?

Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/utils.ts]: I guess I'm also confused on why we need to set the scrollTop three times

Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/utils.ts]: I originally thought the nested requestAnimationFrame was needed to ensure the scroll position was applied after the virtualizer had finished updating the DOM. The idea was to wait for one frame for the virtualizer to process, then another frame to ensure the scroll stuck.              
                                                                                                                                                        
However, after local testing without them, it turns out they're redundant. The simpler approach of just calling `virtualizer.scrollToOffset()` followed by setting `element.scrollTop` works reliably. Removed the unnecessary complexity.

**Review by pierrejeambrun — APPROVED** [review]

**Comment by pierrejeambrun** [comment]
Manual backport https://github.com/apache/airflow/pull/60875

**Comment by guan404ming** [comment]
Thanks!
