### PR TITLE
Much easier to use and better documented Docker image

### LINKED ISSUE #14255: Breeze: Specifiying "-install-airflow-version 2.0.1" produces error on Image build
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): "elementary OS 5.1.7 Hera"
- **Kernel** (e.g. `uname -a`): "Linux 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux"
- **Install tools**: Anaconda3
- **Others**: Python 3.7.6, Docker version 19.03.6, build 369ce74a3c, docker-compose version 1.28.2, build 67630359

**What happened**:

When running the following command:
`./breeze start-airflow --python 3.8 --install-airflow-version 2.0.1 --backend postgres --postgres-version 9.6`
If I choose to rebuild the CI image, I get the following error:
`Please confirm rebuild image CI-python3.8. Are you sure? [y/N/q]
y
....
airflow-providers-zendesk
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Requirement already up-to-date: pip==20.2.4 in /usr/local/lib/python3.8/site-packages (20.2.4)
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
apache-airflow 2.1.0.dev0 requires apache-airflow-providers-ftp, which is not installed.
apache-airflow 2.1.0.dev0 requires apache-airflow-providers-http, which is not installed.
apache-airflow 2.1.0.dev0 requires apache-airflow-providers-imap, which is not installed.
apache-airflow 2.1.0.dev0 requires apache-airflow-providers-sqlite, which is not installed.
apache-beam 2.27.0 has requirement dill<0.3.2,>=0.3.1.1, but you have dill 0.3.3.
apache-beam 2.27.0 has requirement httplib2<0.18.0,>=0.8, but you have httplib2 0.18.1.
apache-beam 2.27.0 has requirement mock<3.0.0,>=1.0.1, but you have mock 4.0.2.
The command '/bin/bash -o pipefail -e -u -x -c if [[ ${INSTALL_FROM_PYPI} == "true" ]]; then         bash /scripts/docker/install_airflow.sh;     fi' returned a non-zero code: 1
ERROR: The previous step completed with error. Please take a look at output above`

**What you expected to happen**: The image would build accordingly

**How to reproduce it**: `./breeze start-airflow --python 3.8 --install-airflow-version 2.0.1 --backend postgres --postgres-version 9.6`

**Anything else we need to know**: Jarek asked me to log this issue on the slack channel. I'm a n00b at this, but I am looking forward to contributing.

### LINKED ISSUE #14848: It should be necessary to specify   --build-arg AIRFLOW_CONSTRAINTS_REFERENCE="constraints-${AIRFLOW_VERSION}" \
**Description**

By default AIRFLOW_CONSTRAINTS_REFERENCE is `constraints-master` and that will make the `docker build` fail if you are building for `--build-arg AIRFLOW_VERSION="${AIRFLOW_VERSION}"`

I suggest that that AIRFLOW_CONSTRAINT_REFERENCE default value is computed by default as `constraints-${AIRFLOW_VERSION}`  instead of `constraints-master`. 

**Use case / motivation**

I want avoid having to provide all three
* `AIRFLOW_VERSION`
* `AIRFLOW_INSTALL_VERSION`
* `AIRFLOW_CONSTRAINTS_REFERENCE`

I think AIRFLOW_INSTALL_VERSION and AIRFLOW_CONSTRAINTS_REFERENCE can be computed from AIRFLOW_VERSION 

**Are you willing to submit a PR?**

No

**Related Issues**

#14845

### PR DESCRIPTION
**Pull request by potiuk**
Previously you had to specify AIRFLOW_VERSION_REFERENCE and
AIRFLOW_CONSTRAINTS_REFERENCE to point to the right version
of Airflow. Now those values are auto-detected if not specified
(but you can still override them)

This change allowed to simplify and restructure the Dockerfile
documentation - following the recent change in separating out
the docker-stack, production image building documentation has
been improved to reflect those simplifications. It should be
much easier to grasp by the novice users now - very clear
distinction and separation is made between the two types of
building your own images - customizing or extending - and it
is now much easier to follow examples and find out how to
build your own image. The criteria on which approach to
choose were put first and forefront.

Examples have been reviewed, fixed and put in a logical
sequence. From the most basic ones to the most advanced,
with clear indication where the basic aproach ends and where
the "power-user" one starts. The examples were also separated
out to separate files and included from there - also the
example Docker images and build commands are executable
and tested automatically in CI, so they are guaranteed
to work.

Finally The build arguments were split into sections - from most
basic to most advanced and each section links to appropriate
example section, showing how to use those parameters.

Fixes: #14848
Fixes: #14255

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
@ecerulm @grantav -> your issues will be fixed when this one is merged.

**Comment by potiuk** [comment]
@mik-laj - that impacts a bit #14846 - If you want you can merge it first and I will resolve the conflicts after (but also need review  here)

**Comment by potiuk** [comment]
Hey @ecerulm @grantav @mik-laj (also @kaxil and @ashb) - while improving the automation of image building, I also realized that after some of the recent changes we got very close to a "target" prod image setting I Imagined when I started it. Finally the original "development" image turned into a much closer "production" one - much more user friendly to build and use.

The nice thing is that we still kept the "development" friendliness (and especially CI friendliness) of the image that I started it from and we have now a very nice (I think) way of describing it. Following @mik-laj separating out of the docker-stack in our documentation I restructured it internally and removes some of the old arguments/fixed examples, I also made a very clear progression of complexity of building the image - from very easy extending the image going through more complex cases, ending with rather complex "building image in restricted environment" (which was BTW a real case we had with two of our customers independently so it is not an isolated or rare case). 

I restructured and split the "build-args" reference following the same pattern - first you have the basic args that you will almost always use when customizing the image, and then you have other args that are grouped by "customization cases" with links to the examples section where you can see how the args can be used.

I made it very clear - I think when extension is a good choice, and when you should go with the customization route. I prepared an example Customize vs Extend where I got 1.1 GB "extended" vs 874 MB "Customized" with the same customization, this is a nice example of showing how you can get 20% optimization if you are a "Power-user".

Moreover - I extracted all the examples (using `exampleinclude`) and I run them in CI (!) so that we will be sure that those examples work (I have to fix failing test but this is the goal to keep them tested automatically).


@ecerulm -> you were looking at the image recently as the user, I would really appreciate your feedback and potential improvements in this PR - but anyone else's comments are most welcome.

File: scripts/ci/images/ci_run_prod_image_test.sh [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+echo "${res}" >"${PARALLEL_JOB_STATUS}"
+# cleanup docker
+docker system prune --force || true >/dev/null 2>&1
+
+echo
+# print status to log
+if [[ ${res} == "0" ]]; then
+    echo "${COLOR_GREEN}Extend PROD image test ${job_name} succeeded${COLOR_RESET}"
+else
+    echo "${COLOR_RED}Extend PROD image test${job_name} failed${COLOR_RESET}"
```
Comment (mik-laj) [inline scripts/ci/images/ci_run_prod_image_test.sh]:
```suggestion
    echo "${COLOR_RED}Extend PROD image test ${job_name} failed${COLOR_RESET}"
```

File: scripts/docker/common.sh [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+# KIND, either express or implied.  See the License for the
+# specific language governing permissions and limitations
+# under the License.
+set -euo pipefail
+
+test -v INSTALL_MYSQL_CLIENT
+test -v AIRFLOW_INSTALL_USER_FLAG
+test -v AIRFLOW_REPO
+test -v AIRFLOW_BRANCH
```
Comment (mik-laj) [inline scripts/docker/common.sh:23]: 😻

File: scripts/docker/common.sh [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+            AIRFLOW_CONSTRAINTS_REFERENCE=constraints-${AIRFLOW_VERSION}
+        else
+            AIRFLOW_CONSTRAINTS_REFERENCE=${DEFAULT_CONSTRAINTS_BRANCH}
+        fi
+    fi
+
+    if [[ -z ${AIRFLOW_CONSTRAINTS_LOCATION} ]]; then
+        local constraints_base="https://raw.githubusercontent.com/${CONSTRAINTS_GITHUB_REPOSITORY}/${AIRFLOW_CONSTRAINTS_REFERENCE}"
+        local python_version
+        python_version="$(python -c 'import platform;print(f"{platform.sys.version_info.major}.{platform.sys.version_info.minor}")')"
```
Comment (mik-laj) [inline scripts/docker/common.sh]: This will not work if you are building an image for Airflow 1.10 and Python 2.7.
```suggestion
        # 2>/dev/stdout for Python 2.7 compatibility.
        python_version="$(python --version 2>/dev/stdout | cut -d " " -f 2 | cut -d "." -f 1-2)"
```

File: docs/docker-stack/build.rst [hunk 4]
```diff
@@ -41,210 +80,322 @@ Debian dependencies with ``apt`` or PyPI dependencies with ``pip install`` or an
...
-  as ``root`` user, you need to switch to it with ``USER`` directive of the Dockerfile. Also you
-  should remember about following the
+  as ``root`` user, you need to switch to it with ``USER`` directive of the Dockerfile and switch back to
+  ``airflow`` user when you are done. Also you should remember about following the
   `best practises of Dockerfiles <https://docs.docker.com/develop/develop-images/dockerfile_best-practices/>`_
   to make sure your image is lean and small.
 
-  .. code-block:: dockerfile
+* The PyPI dependencies in Apache Airflow are installed in the user library, of the "airflow" user, so
+  PIP packages are installed to ~/.local folder as if the ``--user`` flag was specified when running PIP.
```
Comment (mik-laj) [inline docs/docker-stack/build.rst]:
```suggestion
  PIP packages are installed to ``~/.local`` folder as if the ``--user`` flag was specified when running PIP.
```

File: docs/docker-stack/build.rst [hunk 5]
```diff
@@ -41,210 +80,322 @@ Debian dependencies with ``apt`` or PyPI dependencies with ``pip install`` or an
...
+
+The size of this image is ~ 1.1 GB when build. As you will see further, you can achieve 20% reduction in
+size of the image in case you use "Customizing" rather than "Extending" the image.
+
+DAG embedding example
+.....................
+
+The following example adds ``test_dag.py`` to your image in the ``/opt/airflow/dags`` folder.
+
+.. exampleinclude:: docker-examples/extending/embedding-dags/Dockerfile
```
Comment (mik-laj) [inline docs/docker-stack/build.rst:152]: In the Helm documentation, we have an example that sets file permissions. Is it necessary? Should we unify these examples?
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/helm-chart/latest/manage-dags-files.html#bake-dags-in-docker-image

File: docs/docker-stack/build.rst [hunk 6]
```diff
@@ -41,210 +80,322 @@ Debian dependencies with ``apt`` or PyPI dependencies with ``pip install`` or an
...
 
-  docker build . \
-    --build-arg PYTHON_BASE_IMAGE="python:3.7-slim-buster" \
-    --build-arg PYTHON_MAJOR_MINOR_VERSION=3.7 \
-    --build-arg AIRFLOW_INSTALLATION_METHOD="https://github.com/apache/airflow/archive/2.0.1.tar.gz#egg=apache-airflow" \
-    --build-arg AIRFLOW_CONSTRAINTS_REFERENCE="constraints-2-0" \
-    --build-arg AIRFLOW_BRANCH="v1-10-test" \
-    --build-arg AIRFLOW_SOURCES_FROM="empty" \
-    --build-arg AIRFLOW_SOURCES_TO="/empty"
+The above image is equivalent of the ""extended" image from previous chapter but it's size is only
```
Comment (mik-laj) [inline docs/docker-stack/build.rst]:
```suggestion
The above image is equivalent of the "extended" image from previous chapter but it's size is only
```

File: docs/docker-stack/build.rst [hunk 7]
```diff
@@ -41,210 +80,322 @@ Debian dependencies with ``apt`` or PyPI dependencies with ``pip install`` or an
...
-    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list" \
-    --build-arg ADDITIONAL_RUNTIME_APT_DEPS="msodbcsql17 unixodbc git procps vim" \
-    --build-arg ADDITIONAL_RUNTIME_ENV_VARS="ACCEPT_EULA=Y" \
-    --tag my-image
-
-Customizing images in high security restricted environments
-...........................................................
+In case you need to use your custom PyPI package indexes, you can also customize PYPI sources used during
+image build by adding a ``docker-context-files``/``.pypirc`` file when building the image.
+This ``.pypirc`` will not be committed to the repository (it is added to .gitignore) and it will not be
```
Comment (mik-laj) [inline docs/docker-stack/build.rst]:
```suggestion
This ``.pypirc`` will not be committed to the repository (it is added to ``.gitignore``) and it will not be
```

File: docs/docker-stack/build.rst [hunk 8]
```diff
@@ -262,119 +413,99 @@ The ``pip download`` might happen in a separate environment. The files can be co
 binary repository and vetted/verified by the security team and used subsequently to build images
 of Airflow when needed on an air-gaped system.
 
-Preparing the constraint files and wheel files:
+Example of preparing the constraint files and wheel files (note that ``mysql`` dependency is removed
```
Comment (mik-laj) [inline docs/docker-stack/build.rst]: Missing closing bracket

File: docs/docker-stack/build.rst [hunk 9]
```diff
@@ -262,119 +413,99 @@ The ``pip download`` might happen in a separate environment. The files can be co
...
-+----------------------------------------------------+---------------------+-----------------------+
-
-[1] When you combine customizing and extending the image, you can use external sources
-in the "extend" part. There are plans to add functionality to add external sources
-option to image customization. You can also modify Dockerfile manually if you want to
-use non-default sources for dependencies.
-
-More details about the images
------------------------------
+More details
```
Comment (mik-laj) [inline docs/docker-stack/build.rst:498]: Incorrect header level. We have. a new page.
Screenshot 2021-03-23 at 00 54 34

File: docs/docker-stack/build.rst [hunk 10]
```diff
@@ -262,119 +413,99 @@ The ``pip download`` might happen in a separate environment. The files can be co
...
 
-You can customize PYPI sources used during image build by adding a ``docker-context-files``/``.pypirc`` file
-This ``.pypirc`` will never be committed to the repository and will not be present in the final production image.
-It is added and used only in the build segment of the image so it is never copied to the final image.
+* The ``docker-context-files`` folder is automatically added to the context of the image, so if you want
+  to add individual files, binaries, requirement files etc you can add them there. The
+  ``docker-context-files`` is copied to the ``/docker-context-files`` folder of the build segment of the
+  image, so it is not present in the final image - which makes the final image smaller in case you want
+  to use those files only in the ``build`` segment. You must copy any files from the directory manually,
+  using COPY command if you want to get the files in your final image (in the main image segment).
```
Comment (mik-laj) [inline docs/docker-stack/build.rst:495]:
```suggestion
  using ``COPY`` command if you want to get the files in your final image (in the main image segment).
```

File: docs/docker-stack/build.rst [hunk 11]
```diff
@@ -262,119 +413,99 @@ The ``pip download`` might happen in a separate environment. The files can be co
...
-    --build-arg AIRFLOW_PRE_CACHED_PIP_PACKAGES="false" \
-    --build-arg INSTALL_FROM_DOCKER_CONTEXT_FILES="true" \
-    --build-arg AIRFLOW_CONSTRAINTS_LOCATION="/docker-context-files/constraints-2-0.txt"
+* We are using the widely recommended pattern of ``.dockerignore`` where everything is ignored by default
+  and only the required folders are added through exclusion (!). This allows to keep docker context small
+  because there are many binary artifacts generated in the sources of Airflow and if they are added to
+  the context, the time of building the image would increase significantly. If you want to add any new
+  folders to be available in the image you must add it here with leading ``!``.
 
+.. code-block:: text
```
Comment (mik-laj) [inline docs/docker-stack/build.rst]: This seems to have the same indentation level as the paragraph above.

**Comment by mik-laj** [comment]
Love it! 😻 Now it is much clearer and user-friendly.

File: scripts/docker/common.sh (hunk 3 above)
Comment (potiuk) [reply scripts/docker/common.sh]: Nice!

File: docs/docker-stack/build.rst (hunk 5 above)
Comment (potiuk) [reply docs/docker-stack/build.rst:152]: Uhhh. I actually realized it is a bug 

I unified it in the Dockerfile (and will submit it as separate fix in a moment)

Comment (potiuk) [reply docs/docker-stack/build.rst:152]: `usermod -g 0 ${AIRFLOW_UID}` in the prod image should fix it

Comment (potiuk) [reply docs/docker-stack/build.rst:152]: And then we should not worry about changing user in this case ( will fix it in the helm example too)

Comment (potiuk) [reply docs/docker-stack/build.rst:152]: Fixed in #14944

**Comment by potiuk** [comment]
All fixed @mik-laj  - I also rebased it on top of #14944 that fixes default group for the airflow user

**Review by mik-laj — APPROVED** [review]

File: .github/workflows/ci.yml [hunk 12]
```diff
@@ -229,6 +230,29 @@ jobs:
       - name: "Generate client codegen diff"
         run: ./scripts/ci/openapi/client_codegen_diff.sh
 
+  test-examples-of-prod-image-building:
+    timeout-minutes: 60
+    name: "Test examples of production image building"
+    runs-on: ${{ fromJson(needs.build-info.outputs.runsOn) }}
+    needs: [build-info]
+    if: needs.build-info.outputs.needs-api-codegen == 'true'
```
Comment (kaxil) [inline .github/workflows/ci.yml]: Why does this step need api codegen?

**Review by kaxil — APPROVED** [review]

File: .github/workflows/ci.yml (hunk 12 above)
Comment (potiuk) [reply .github/workflows/ci.yml]: mistake :)
