### PR TITLE
Show multiple asset triggered runs from an event

### LINKED ISSUE #48482: Only one dagrun is shown per asset event in UI
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

When there are multiple dagruns per asset event only one is shown. I guess I made it this way because there was no dagrun list page and asset page during the component being added. Initially the design had first 2 or 3 dagruns and then more ones as "+n more" . Should all dagruns be shown as links or in case of "n more" should it be a popup showing them.

`created_dagruns[0]` is used which should be looping through `created_dagruns`

https://github.com/apache/airflow/blob/347c98cd8c285b7b8ca3a8a626be89d16a572bbf/airflow-core/src/airflow/ui/src/components/Assets/AssetEvent.tsx#L84-L92

### What you think should happen instead?

_No response_

### How to reproduce

1. Create an asset event with both dags enabled.
2. Only one dagrun is shown in the asset event widget though 2 dagruns got triggered.

```python

from __future__ import annotations

import datetime

from airflow.decorators import task
from airflow.models.dag import DAG
from airflow.sdk.definitions.asset import Asset

asset = Asset(uri="s3://output.txt", name="test-asset-output")

with DAG(
    dag_id="asset_dag_1",
    catchup=False,
    start_date=datetime.datetime.min,
    schedule=[asset],
):

    @task()
    def run_1():
        pass

    run_1()

with DAG(
    dag_id="asset_dag_2",
    catchup=False,
    start_date=datetime.datetime.min,
    schedule=[asset],
):

    @task()
    def run_2():
        pass

    run_2()
```

### Operating System

Ubuntu 20.04

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by bbovenzi**
When there are multiple asset event triggered dag runs, show a popover with a link to each one. Also, show the dag run state.

Fixes: https://github.com/apache/airflow/issues/48482

Also, I found some spots where we were still using asset.name to look up dependencies instead of the id. This fixes materializing an asset and highlighting the edges in the asset graph.

Removed `asset.name` from the asset event list card when you're on the asset details page.

Screenshot 2025-04-01 at 11 50 15 AM

Screenshot 2025-04-01 at 11 50 25 AM

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

**Comment by tirkarthi** [comment]
Off-topic but in case of many events currently there is no page to see all the asset events so just wondering if there will be a global page for asset events like task instances, dag runs in the dags list page.

**Comment by bbovenzi** [comment]
@tirkarthi yes thats on the to-do list!

**Comment by tirkarthi** [comment]
I think it's still useful to show the source of the event in asset detail page. Maybe below was the intention of the PR change to hide name instead of the source.

```patch
diff --git a/airflow-core/src/airflow/ui/src/components/Assets/AssetEvent.tsx b/airflow-core/src/airflow/ui/src/components/Assets/AssetEvent.tsx
index adfd2e125c..fff67542d8 100644
--- a/airflow-core/src/airflow/ui/src/components/Assets/AssetEvent.tsx
+++ b/airflow-core/src/airflow/ui/src/components/Assets/AssetEvent.tsx
@@ -55,7 +55,7 @@ export const AssetEvent = ({
       <Text fontWeight="bold">
         <Time datetime={event.timestamp} />
       </Text>
-      {Boolean(assetId) ? undefined : (
+      {Boolean(assetId) && !Boolean(showAssetName) ? undefined : (
         <HStack>
           <FiDatabase />
           <Tooltip
@@ -73,7 +73,6 @@ export const AssetEvent = ({
           </Tooltip>
         </HStack>
       )}
-      {Boolean(showAssetName) ? (
         <HStack>
           <Text>Source: </Text>
           {source === "" ? (
@@ -86,7 +85,6 @@ export const AssetEvent = ({
             source
           )}
         </HStack>
-      ) : undefined}
       <HStack>
         <TriggeredRuns dagRuns={event.created_dagruns} />
       </HStack>
```

**Comment by bbovenzi** [comment]
Yes, my bad. I already had this built in. Reverting.

File: airflow-core/src/airflow/ui/src/components/Assets/AssetEvents.tsx [hunk 1]
```diff
@@ -42,6 +42,7 @@ type AssetEventProps = {
   readonly isLoading?: boolean;
   readonly setOrderBy?: (order: string) => void;
   readonly setTableUrlState?: (state: TableState) => void;
+  readonly showAssetName?: boolean;
```
Comment (tirkarthi) [inline airflow-core/src/airflow/ui/src/components/Assets/AssetEvents.tsx]: This can be removed since it's not used.

**Review by tirkarthi — APPROVED** [review]
Thanks @bbovenzi
