### PR TITLE
Hide Irrelevant Dag Processor from Cluster Activity Page

### LINKED ISSUE #33497: DAG Processor should not be visible in the Cluster Activity Page if there is no stand alone processor
### Apache Airflow version

2.7.0rc2

### What happened

In the Airflow UI, currently, the DAG Processor is visible in the Cluster Activity page even if there is no stand-alone dag processor. 

### What you think should happen instead

It should be hidden if there is no stand-alone dag processor.

### How to reproduce

Run Airflow 2.7 

### Operating System

Mac OS

### Versions of Apache Airflow Providers

Airflow > 2.7

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by erdos2n**
Users should not see the Dag Processor health on the Cluster Activity page if `standalone_dag_processor=False`. 

closes: https://github.com/apache/airflow/issues/33497

### CODE REVIEW

File: airflow/www/static/js/index.d.ts [hunk 1]
```diff
@@ -22,6 +22,7 @@ import type { DepEdge, DepNode } from "./types";
 // define global variables that come from FAB
 declare global {
   const autoRefreshInterval: number | undefined;
+  const standaloneDagProcessor: boolean | false;
```
Comment (bbovenzi) [inline airflow/www/static/js/index.d.ts]:
```suggestion
  const standaloneDagProcessor: boolean | undefined;
```

File: airflow/www/static/js/cluster-activity/live-metrics/Health.tsx [hunk 2]
```diff
@@ -107,11 +106,15 @@ const Health = (props: CenterProps) => {
               latestHeartbeat={data?.triggerer?.latestTriggererHeartbeat}
               mb={3}
             />
+            { 
+            standaloneDagProcessor === true &&
```
Comment (bbovenzi) [inline airflow/www/static/js/cluster-activity/live-metrics/Health.tsx]:
```suggestion
            !!standaloneDagProcessor &&
```

File: airflow/www/static/js/index.d.ts (hunk 1 above)
Comment (erdos2n) [reply airflow/www/static/js/index.d.ts]: done

File: airflow/www/static/js/cluster-activity/live-metrics/Health.tsx (hunk 2 above)
Comment (erdos2n) [reply airflow/www/static/js/cluster-activity/live-metrics/Health.tsx]: done

**Comment by erdos2n** [comment]
@bbovenzi how can I prevent this error from occurring in the `React/WWW` tests?

```
    ReferenceError: standaloneDagProcessor is not defined
```

**Comment by bbovenzi** [comment]
> @bbovenzi how can I prevent this error from occurring in the `React/WWW` tests?
> 
> ```
>     ReferenceError: standaloneDagProcessor is not defined
> ```

Look at `global.stateColors` inside of `jest-setup.js`

**Comment by bbovenzi** [comment]
Care to rebase? Not sure why some images aren't building correctly.

**Comment by potiuk** [comment]
I rebased. We had a "botocore" causing backtracking issues (solved today with #33649

**Review by bbovenzi — APPROVED** [review]

File: airflow/www/static/js/cluster-activity/live-metrics/Health.tsx [hunk 3]
```diff
@@ -107,11 +106,16 @@ const Health = (props: CenterProps) => {
               latestHeartbeat={data?.triggerer?.latestTriggererHeartbeat}
               mb={3}
             />
-            <HealthSection
-              title="Dag Processor"
-              status={data?.dagProcessor?.status}
-              latestHeartbeat={data?.dagProcessor?.latestDagProcessorHeartbeat}
-            />
+            {!!standaloneDagProcessor && (
```
Comment (pierrejeambrun) [inline airflow/www/static/js/cluster-activity/live-metrics/Health.tsx:108]: All items should have a margin bottom except the last one to keep spacing consistent. (padding of the card is already handled)
Both when the last item is the `Dag Processor` or the `Triggerer`.

To not add a ternary operator into the triggerer `mb` props you can simply define a margin top on the `Dag Processor` section and remove the `mb` of the Triggerer.

Comment (erdos2n) [reply airflow/www/static/js/cluster-activity/live-metrics/Health.tsx:108]: @pierrejeambrun I've made these updates. Can you mark this a resolved? Let me know if further updates are needed.

**Review by pierrejeambrun — APPROVED** [review]
LGTM thank you!

Re-running the failed job, should be green
