### PR TITLE
Better compatibility/diagnostics for arbitrary UID in docker image

### LINKED ISSUE #15107: Make the entrypoint in Prod image fail in case the user/group is not properly set
Airflow Production image accepts two types of uid/gid setting:

* airflow user (50000) with any GID
* any other user wit GID = 0 (this is to accommodate OpenShift Guidelines https://docs.openshift.com/enterprise/3.0/creating_images/guidelines.html)

We should check the uid/gid at entrypoint and fail it with clear error message if the uid/gid are set wrongly.

**Description**

**Use case / motivation**

**Are you willing to submit a PR?**

**Related Issues**

### PR DESCRIPTION
**Pull request by potiuk**
The PROD image of airflow is OpenShift compatible and it can be
run with either 'airflow' user (UID=50000) or with any other
user with (GID=0).

This change adds umask 0002 to make sure that whenever the image
is extended and new directories get created, the directories are
group-writeable for GID=0. This is added in the default
entrypoint.

The entrypoint will fail if it is not run as airflow user or if
other, arbitrary user is used with GID != 0.

Fixes: #15107

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by ashb** [comment]
What fails of the you uid is incorrect?

So long as the dags can be read, and the logs folder written to the image will work I think?

**Comment by potiuk** [comment]
It's about access right to a number of directories. This is very common pattern (for example used in OpenShift) and we already have a number of issues opened about it (for example just opened issue here which describes what happens and where the problems are: https://github.com/apache/airflow/issues/15161#issuecomment-812606687) 

This is also very closely following the openshift guidelines: 

https://docs.openshift.com/container-platform/4.7/openshift_images/create-images.html#images-create-guide-openshift_create-images

All the reasons for this approach are described there in detail in th "support for arbitrary user ids" chapter in the openshift documentation - I will not copy it here, they described it pretty well there.

**Comment by potiuk** [comment]
I just pushed a bit better error message returned in this case, so that it is much clearer.

**Comment by potiuk** [comment]
BTW. I 'd love to cherry-pick it before we prepare 2.0.2 (because more users have questions about it recently)

**Comment by potiuk** [comment]
@ash - do you have any concerns about this ? It's pretty standard problem with any docker images out there, how to make them run with arbitrary user ids and there are couple of solution (like changing directory permissions dynamically when entering the image or making them rxw to "other". The openshift solution is elegant and simple, also with recent changes where 'root' group is the default and --local flag in PIP is default as well, we have a complete solution that works out-of-the-box in most scenarios - this entrypoint warning is just a way to make the users aware about the limitations.

**Comment by ashb** [comment]
I read that guide in openshift and come to the complete opposite conclusion: we should support running as whatever user id the user chooses.

I don't have a problem with this change though, just wanted to know what the problem/exact error was since the linked issue didn't mention.

File: scripts/in_container/prod/entrypoint_prod.sh [hunk 1]
```diff
@@ -244,6 +243,30 @@ function exec_to_bash_or_python_command_if_specified() {
...
+    >&2 echo
+    >&2 echo "The image can be run in two ways when it comes to UID:"
+    >&2 echo "  * with 'airflow' user (UID=50000) and any GID"
+    >&2 echo "  * with any user and GID=0 (root)"
+    >&2 echo
+    >&2 echo " You start the image with UID=$(id -u) and GID=$(id -g)"
+    >&2 echo
+    >&2 echo " This is to learn from the guidelines of OpenShift and make the image OpenShift compatible"
+    >&2 echo " See more about it in the docker image documentation on http://airflow.apache.org/docs/"
+    >&2 echo " or https://docs.openshift.com/container-platform/4.7/openshift_images/create-images.html#images-create-guide-openshift_create-images"
```
Comment (ashb) [inline scripts/in_container/prod/entrypoint_prod.sh]: I don't think linking to a doc about building an image on openshift is relevant for users running this image.

**Comment by potiuk** [comment]
> I read that guide in openshift and come to the complete opposite conclusion: we should support running as whatever user id the user chooses.

Yeah. I actually fully agree with that statement. And we can do that already (our image allows that),

But the gudelines also say (and I follow it) that in order to make it possible without additional extra effort, the best way is to also always run the image with GID=0 and make your image prepared for that - every folder in the image to have GID=0 as primary group and all the access rights synchronized so that rights of the owner and rights of the group are the same.

Following this avoids many pitfalls when you think about extendability of the image . For example if you build your image FROM: and want to install new package, if you will do it as an `airflow` user (because  you do not want to change it back to root and again back to airflow) with the current approach, it will still be "OpenShift-compatible" and work without any more effort.

Which actually made me check something - I am going to update this one a bit and add `umask 0002` instead of the default `0022` which will make it truly working out-of-the box for arbitrary user even if the installation of such 3-rd party package will create a new writeable directory.

File: scripts/in_container/prod/entrypoint_prod.sh (hunk 1 above)
Comment (potiuk) [reply scripts/in_container/prod/entrypoint_prod.sh]: Agree. We are going to have a new "docker" area in teh 2.0.2 image. I am going to point to that - in the updated documentation, I already explained it in more detailed and linked to openshift guidelines.

**Comment by potiuk** [comment]
I added the umask and changed the description/subject of the commit to better describe the meaning of this now. Also I added a comment in the entrypoint explaining why umask is added, and linked to the new, updated documentation (already cherry-picked to 2.0.2 so it should be linking to the right part of the documentation when we release it.

**Comment by potiuk** [comment]
I thought about it a bit more and added a bit more clearer description (and example) on why we are doing all that. And I closed some of the loopholes (for example I realized that I removed 50000 GID from airflow rather than made it supplementary group).

I think with those explanations and examples and the entrypoint script redirecting the user to that documentation, we should not have any more issues/questions from our users. Looking forward to getting it reviewed quickly.


@ashb @kaxil  - when are we cutting 2.0.2? I would really love to get that one in. This will guide the users better, when trying to build their own images based on Airflow's reference one. 

I think it closes quite a number of potential mistakes of the users trying to build their own images

File: scripts/in_container/prod/entrypoint_prod.sh [hunk 2]
```diff
@@ -244,6 +243,47 @@ function exec_to_bash_or_python_command_if_specified() {
     fi
 }
 
+function check_uid_gid() {
+    if [[ $(id -g) == "0" ]]; then
+        return
+    fi
+    if [[ $(id -u) == "50000" ]]; then
+        >&2 echo
```
Comment (potiuk) [inline scripts/in_container/prod/entrypoint_prod.sh:251]: I turned it into warning only if 'airflow' user is used and GID is not 0. This should be quite nice for the users:

* existing helm charts will work
* it's rather OK to run airflow with any GID as long as you are never going to use the arbitrary UID for already created directories
* we clearly warn the users and they will see it in their log files that GID=0 is the "recommended" way.

File: docs/docker-stack/entrypoint.rst [hunk 3]
```diff
@@ -87,13 +87,49 @@ The image entrypoint works as follows:
...
+
+Allowing arbitrary user to run the container
+--------------------------------------------
+
+Airflow image is Open-Shift compatible, which means that you can start it with random user ID and the
+group id ``0`` (``root``). If you want to run the image with user different than Airflow, you MUST set
+GID of the user to ``0``. In case you try to use different group, the entrypoint exits with error.
+
+In order to accommodate a number of external libraries and projects, Airflow will automatically create
+such an arbitrary user in (`/etc/passwd`) and make it's home directory point to ``/home/airflow``.
```
Comment (mik-laj) [inline docs/docker-stack/entrypoint.rst:100]:
```suggestion
such an arbitrary user in (``/etc/passwd``) and make it's home directory point to ``/home/airflow``.
```

**Comment by potiuk** [comment]
Hey @ashb / @kaxil/ @mik-laj ->  any more comments here for the UID feature? I think I described it pretty well now and we have warning rather than error where airflow is used with the original UID. Seems like this one might save us some issues from users.

**Comment by potiuk** [comment]
Anyone :) ?

**Review by feluelle — APPROVED** [review]

**Comment by dimberman** [comment]
Hi @potiuk, Ash is on vacation this week, I think this looks good though!

**Review by dimberman — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks @dimberman !
