### PR TITLE
Display all task tries in Gantt chart

### LINKED ISSUE #55246: Gantt view is always showing the latest dagrun data even if user selects previous task try
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

Image

Image

### What you think should happen instead?

_No response_

### How to reproduce

For the below dag, create a dagrun and clear dagrun, notice gantt view for 2 task tries:

```python
import datetime

from airflow.providers.standard.operators.bash import BashOperator
from airflow.providers.standard.operators.python import PythonOperator
from airflow.sdk import DAG


def fetch_xcom(**kwargs):
    return kwargs["ti"].xcom_pull(key="choice")

def push_xcom(**kwargs):
    kwargs["ti"].xcom_push(key="choice", value="foo")

dag = DAG(
    'test_api_dag',
    start_date=datetime.datetime(2025, 8,25),
    schedule='@daily',
    is_paused_upon_creation=False,
    catchup=True,
)

hello_task = BashOperator(
    task_id="hello",
    bash_command="echo hello",
    dag=dag
)

bye_task = BashOperator(
    task_id="bye",
    bash_command="echo bye",
    dag=dag
)

hello_task >> bye_task

``` 

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by guan404ming**
<!--
Thank you for contributing!

Please provide above a brief description of the changes made in this pull request.
Write a good git commit message following this guide: http://chris.beams.io/posts/git-commit/

Please make sure that your code changes are covered with tests.
And in case of new features or big changes remember to adjust the documentation.

Feel free to ping (in general) for the review if you do not see reaction for a few days
(72 Hours is the minimum reaction time you can expect from volunteers) - we sometimes miss notifications.

In case of an existing issue, reference it using one of the following:

* closes: #ISSUE
* related: #ISSUE
-->

Related Issue

Close #55246

## Why                                                                                                                                                           
                                                                                                                                                                
Gantt always the latest TI try. But it should show all history tries like AF2
                                                                                                                                                              
## How                                                                                                                                                           
                                                                                                                                                              
- Backend: New /ui/gantt/{dag_id}/{run_id} endpoint combining current task instances with historical tries via union_all                                      
- Frontend: Transform data to show multiple tries per task row with try number in tooltip                                                                     


https://github.com/user-attachments/assets/ecf390d4-7039-48c4-aa8b-cbd4a313ee4b

---

##### Was generative AI tooling used to co-author this PR?

<!--
If generative AI tooling has been used in the process of authoring this PR, please
change below checkbox to `[X]` followed by the name of the tool, uncomment the "Generated-by".
-->

- [x] Yes (please specify the tool below)
Claude Code with Opus 4.5

<!--
Generated-by: [Tool Name] following [the guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#gen-ai-assisted-contributions)
-->

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/queries/useClearTaskInstances.ts
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/queries/useClearTaskInstances.ts:1]: We should do the same for `useClearRun`

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts [hunk 1]
```diff
@@ -50,13 +59,90 @@ type ChartOptionsParams = {
...
+          });
+        }
+      }
+
+      return undefined;
+    })
+    .filter((item): item is GanttDataItem => item !== undefined);
+};
+
 export const createHandleBarClick =
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts:141]: Let's include try_number in handleBarClick so that clicking on a try that isn't the latest will update the search params like `?try_number=2`

**Review by bbovenzi — COMMENTED** [review]
Looking promising!

File: airflow-core/src/airflow/ui/src/queries/useClearTaskInstances.ts
Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/queries/useClearTaskInstances.ts:1]: Nice catch, thanks!

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts (hunk 1 above)
Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts:141]: Sure, I've updated

https://github.com/user-attachments/assets/9900fbde-1dc3-436a-bffb-93e080e9bafd

File: airflow-core/tests/unit/api_fastapi/core_api/routes/ui/test_gantt.py [hunk 2]
```diff
@@ -0,0 +1,310 @@
...
+                "run_1",
+                "task",
+                "2024-11-30T10:00:00Z",
+                "2024-11-30T10:05:00Z",
+                "success",
+                id="success_task_has_dates",
+            ),
+            pytest.param(
+                DAG_ID,
+                "run_1",
```
Comment (pierrejeambrun) [inline airflow-core/tests/unit/api_fastapi/core_api/routes/ui/test_gantt.py:255]: Can you add db queries guards, just to ensure that this doesn't explode later when updating that endpoint. (and to make sure there isn't N+1 db queries problem, there doesn't seem to be btw)

**Review by pierrejeambrun — COMMENTED** [review]
Backend code looks good. Thanks

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts [hunk 3]
```diff
@@ -50,42 +59,135 @@ type ChartOptionsParams = {
...
+    });
+
+    const searchParams = new URLSearchParams(location.search);
+    const isOlderTry =
+      tryNumber !== undefined &&
+      tryNumber <
+        Math.max(...data.filter((item) => item.taskId === taskId).map((item) => item.tryNumber ?? 1));
+
+    if (isOlderTry) {
+      searchParams.set("try_number", tryNumber.toString());
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts]: Can we use the TRY_NUMBER const from searchParams.ts here?

File: airflow-core/tests/unit/api_fastapi/core_api/routes/ui/test_gantt.py (hunk 2 above)
Comment (guan404ming) [reply airflow-core/tests/unit/api_fastapi/core_api/routes/ui/test_gantt.py:255]: Sure, just updated!

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts (hunk 3 above)
Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts]: Sure, thanks for catching this. Just updated!

**Review by bbovenzi — APPROVED** [review]
