### PR TITLE
Vendor in the bitnami chart

### LINKED ISSUE #24037: Frequent failures of helm chart tests
### Apache Airflow version

main (development)

### What happened

We keep on getting very frequent failures of Helm Chart tests and seems that a big number of those errors are because of errors when pulling charts from bitnami for postgres:

Example here (but I saw it happening very often recently): 

https://github.com/apache/airflow/runs/6666449965?check_suite_focus=true#step:9:314

```
  Save error occurred:  could not find : chart postgresql not found in https://charts.bitnami.com/bitnami: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR
  Deleting newly downloaded charts, restoring pre-update state
  Error: could not find : chart postgresql not found in https://charts.bitnami.com/bitnami: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR
  Dumping logs from KinD
```

It is not only a problem for our CI but it might be similar problem for our users who want to install the chart - they might also get the same kinds of error.

I guess we should either make it more resilient to intermittent problems with bitnami charts or use another chart (or maybe even host the chart ourselves  somewhere within apache infrastructure. While the postgres chart is not really needed for most "production" users, it is still a dependency of our chart and it makes our chart depend on external and apparently flaky service.

### What you think should happen instead

We should find (or host ourselves) more stable dependency or get rid of it. 

### How to reproduce

Look at some recent CI builds and see that they often fail in K8S tests and more often than not the reason is missing postgresql chart.

### Operating System

any

### Versions of Apache Airflow Providers

not relevant

### Deployment

Other

### Deployment details

CI 

### Anything else

Happy to make the change once we agree what's the best way :).

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by potiuk**
After the Bitnami fiasco
https://github.com/bitnami/charts/issues/10539

We lost trust in bitnami index being good and reliable source
of charts. That's why we vendored-in the postgres chart needed for
our Helm chart.

Fixes: #24037

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
:) @jedcunningham ?

File: scripts/ci/libraries/_kind.sh [hunk 1]
```diff
@@ -69,7 +69,7 @@ function kind::make_sure_kubernetes_tools_are_installed() {
     kubectl_url="https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/${system}/${machine}/kubectl"
     if [[ -f "${KUBECTL_BINARY_PATH}" ]]; then
         local downloaded_kubectl_version
-        downloaded_kubectl_version="$(${KUBECTL_BINARY_PATH} version --client=true --short | awk '{ print $3 }')"
```
Comment (jedcunningham) [inline scripts/ci/libraries/_kind.sh:72]: Why no `--short`?

**Review by jedcunningham — APPROVED** [review]

File: scripts/ci/libraries/_kind.sh (hunk 1 above)
Comment (potiuk) [reply scripts/ci/libraries/_kind.sh:72]: We will be re-doing this part when we add it to Breeze (I hope shortly). I will respond then ok :)?
