### PR TITLE
Fix asset name text overflow in DAGs list view

### LINKED ISSUE #55721: Asset name in the schedule field overlaps on the latest run field in the dags page
### Apache Airflow version

3.0.6

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

When the dag trigger schedule is asset based, if the name of the asset is longer, the name overlaps on the latest run field making it hard for the user to read the latest run value.

https://github.com/user-attachments/assets/a3fcc4b9-5cf0-40f6-be53-ee66ad2bfc15

### What you think should happen instead?

The name of the asset field should wrap in or not overlap on the other fields when the string length is longer for the asset name

### How to reproduce

Create a dummy asset with lengthy name and schedule the dag run by setting the asset as an inlet for the dag to trigger.
Verify if the name of the asset overlaps with the latest  run field.

### Operating System

os

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by steveahnahn**
## Summary
This PR fixes the UI issue where long asset names in the DAGs list view overlap with the latest run timestamp, making both the asset name and timestamp unreadable.

## Related Issues
Fixes #55721

Screenshot 2025-09-19 at 2 24 43 PM

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx [hunk 1]
```diff
@@ -63,7 +63,16 @@ export const AssetSchedule = ({ assetExpression, dagId, latestRunAfter, timetabl
...
-        <Link asChild color="fg.info" display="block" fontSize="sm">
+        <Link
+          asChild
+          color="fg.info"
+          display="block"
+          fontSize="sm"
+          maxWidth="200px"
+          overflow="hidden"
+          textOverflow="ellipsis"
+          whiteSpace="nowrap"
```
Comment (guan404ming) [inline airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx]:
```suggestion
          truncate
```
It could be clearer in this way
ref: https://tailwindcss.com/docs/text-overflow

**Review by guan404ming — APPROVED** [review]
LGTM

**Comment by steveahnahn** [comment]
I do not have permissions to merge, do I need to contact a contributor everytime?

**Review by pierrejeambrun — APPROVED** [review]

**Comment by pierrejeambrun** [comment]
Yes, someone with write permission need to approve and merge the PR.
