### PR TITLE
fix(ui): wire up logical date filter on /dagruns page (#62799)

### LINKED ISSUE #62799: Logical date filter not working correctly for /dagruns page
### Apache Airflow version

3.1.7

### If "Other Airflow 3 version" selected, which one?

_No response_

### What happened?

While trying out filter options on /dagruns page, I tried out logical date filter. As far as I understand, when I input the logical date filter in the UI, the runs below are supposed to get filtered. However, when entered, there was no change and all dag runs were shown in the UI. 
I tried with a different field "Run after" field, and it was able to filter it correctly.

### What you think should happen instead?

The dag runs should get filtered correctly within the specified logical date. 

Image

### How to reproduce

1. Go to /dagruns page. Ensure that there are some dag runs already present. 
2. Add a logical date filter

### Operating System

Mac

### Versions of Apache Airflow Providers

NA

### Deployment

Other Docker-based deployment

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Subham-KRLX**
The logical date filter on the /dagruns page was present in the UI but had no effect — selecting a date range did not filter the results.

Root cause: DagRuns.tsx never read logical_date_gte / logical_date_lte from URL search params and never passed logicalDateGte / logicalDateLte to the useDagRunServiceGetDagRuns API call. All other date filters (run_after, start_date, end_date) were correctly wired up.

Fix: Added the missing plumbing in DagRuns.tsx:

Destructure LOGICAL_DATE_GTE and LOGICAL_DATE_LTE from SearchParamsKeys
Read the params from URL via searchParams.get()
Pass them to the useDagRunServiceGetDagRuns hook

Follows the exact same pattern already used in TaskInstances.tsx.
closes: #62799

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/pages/DagRuns.tsx [hunk 1]
```diff
@@ -50,6 +52,8 @@ const {
   DURATION_LTE: DURATION_LTE_PARAM,
   END_DATE_GTE: END_DATE_GTE_PARAM,
   END_DATE_LTE: END_DATE_LTE_PARAM,
+  LOGICAL_DATE_GTE: LOGICAL_DATE_GTE_PARAM,
```
Comment (Prajwal7842) [inline airflow-core/src/airflow/ui/src/pages/DagRuns.tsx:55]: Do we need some validation tests for this ? Or is it auto covered with some existing test ?

Comment (Subham-KRLX) [reply airflow-core/src/airflow/ui/src/pages/DagRuns.tsx:55]: I have added a new unit test DagRuns.test.tsx and a corresponding mock API handler to verify that the logical date parameters are correctly extracted from the URL and passed to the backend API. All local tests (TSC, ESLint, Prettier, and Vitest) are passing.

**Review by bbovenzi — APPROVED** [review]
