### PR TITLE
fix Preserve variable value formatting in edit dialog

### LINKED ISSUE #58648: Variable value formatting no longer preserved in Airflow 3.x UI
### Apache Airflow version

3.1.3

### If "Other Airflow 2/3 version" selected, which one?

_No response_

### What happened?

Starting with Airflow 3.x, the UI no longer preserves the original formatting of variable values.

In Airflow 2.11.x and earlier, when a variable contained structured or multi-line content (e.g., JSON, YAML, or configuration text), the UI displayed the value exactly as stored — including indentation, line breaks, and whitespace. This allowed users to easily read, validate, and edit configuration content directly from the interface.

In Airflow 3.x, the same values are now shown in a compact, single-line format, ignoring all original formatting — even though the value remains correctly formatted in the metadata database. This affects readability and editing, and introduces usability issues for workflows where variables contain structured configuration.

For users storing YAML or other whitespace-sensitive formats, this behavior can also lead to unintentional task failures if the edited, minified content is saved back.

### What you think should happen instead?

When viewing the list of variables, the current behavior — displaying values in a condensed single-line preview — is acceptable and useful.

Image

However, when the user clicks a variable (either through the key link or the "Edit" action), the UI should display the original stored formatting, including:
* line breaks
* indentation
* whitespace

preserving the "original stored" JSON/YAML formatting.

In other words, the variable editor should present the variable exactly as it exists in the metadata database, rather than showing a minified or collapsed version.

This restores the behavior that existed in Airflow ≤ 2.11 and ensures variables containing structured data remain readable and editable within the UI.

### How to reproduce

1. Create a variable using a multi-line formatted value, for example:

```bash
airflow variables set x "$(cat << 'EOF'
{
  "key": "val",
  "key2": "val2"
}
EOF
)"
```

2. Retrieve the value using the CLI to confirm formatting is preserved:

```bash
airflow variables get x
```

Expected output:

```json
{
  "key": "val",
  "key2": "val2"
}
```
3. Open the Airflow UI and navigate to Admin → Variables.
4. Locate and view the same variable in the UI.
5. Observed behavior:

Image

### Operating System

Docker Image

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ricky-chaoju**
**Description**

This PR fixes the variable editor to preserve JSON formatting when editing variables in the Airflow UI.

**Problem:**
In Airflow 3.x, variable values are displayed as minified single-line strings in the edit dialog, making it difficult to read and edit structured data like JSON and YAML.

**Solution:**
Added a `formatValue` function in `EditVariableButton.tsx` that formats JSON values with proper indentation (2 spaces) when the edit dialog is opened. Non-JSON values are preserved as-is.

**Changes:**
- Modified `EditVariableButton.tsx` to add `formatValue` function
- JSON values are formatted using `JSON.stringify(parsed, null, 2)`
- Non-JSON values are displayed unchanged

**Testing:**
1. Created test variable with formatted JSON
2. Verified formatting is preserved in edit dialog
3. Tested with YAML values - preserved as-is

**Screenshots:**

**Before:**
Value field shows: `{"key": "val", "key2": "val2"}`
截圖 2025-11-27 下午2 28 11

**After:**
Value field shows:
```
{
  "key": "val",
  "key2": "val2"
}
```
截圖 2025-11-27 下午2 29 14

**Related Issue(s):**
Closes #58648

### CODE REVIEW

**Review by Lee-W — APPROVED** [review]
I'm good with this change but would be nice if we can have frontend expert take a look. Thanks!

File: airflow-core/src/airflow/ui/src/pages/Variables/ManageVariable/EditVariableButton.tsx [hunk 1]
```diff
@@ -36,6 +36,14 @@ type Props = {
 const EditVariableButton = ({ disabled, variable }: Props) => {
   const { t: translate } = useTranslation("admin");
   const { onClose, onOpen, open } = useDisclosure();
+  const formatValue = (value: string): string => {
+    try {
+      const parsed = JSON.parse(value);
+      return JSON.stringify(parsed, null, 2);
+    } catch {
```
Comment (choo121600) [inline airflow-core/src/airflow/ui/src/pages/Variables/ManageVariable/EditVariableButton.tsx]: The formatting is incorrect. Please adjust the spacing properly.

```
    try {
      const parsed = JSON.parse(value);

      return JSON.stringify(parsed, null, 2);
    } catch {
      return value;
    }
```

Comment (ricky-chaoju) [reply airflow-core/src/airflow/ui/src/pages/Variables/ManageVariable/EditVariableButton.tsx]: Thanks for the review! I've already fixed this in the latest commit. The formatValue function now:
   - Is moved to outer scope
   - Has proper type annotation (const parsed: unknown)
   - Uses undefined instead of null
   
   Please check the updated code.

**Comment by ricky-chaoju** [comment]
Thanks @Lee-W for the review and merge.

**Comment by ctolon** [comment]
Hi, Is this addressed in PR for Apache Airflow 3.2? It's a significant update from a developer UX perspective

**Comment by Lee-W** [comment]
looks like a valid backport. just create a backport PR here https://github.com/apache/airflow/pull/62339
