### PR TITLE
Fix dag import error modal pagination

### LINKED ISSUE #55709: Import errors listed on modal UI are not matching with total import error count
### Apache Airflow version

3.1.0b2

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

Total import error count on UI and DB is not matching with import errors listed on modal UI.
Could be pagination issue

Image

### What you think should happen instead?

_No response_

### How to reproduce

1. Start airflow and make sure we have many dags which are throwing import errors (~100)
2. Notice on UI, total import error count is not matching with the listed import errors on modal UI.

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pierrejeambrun**
Closes: https://github.com/apache/airflow/issues/55709

Implement `pagination` and `search` on the backend. Fix an issue where the modal would only show results of the first `page` results. (limited to 50 items)

https://github.com/user-attachments/assets/5afa7bf3-9407-4f31-b86b-a948736b9f12

### CODE REVIEW

**Review by bbovenzi — APPROVED** [review]
Nice! I'm happy we can get rid of the frontend pagination.

File: airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/DAGImportErrorsModal.tsx [hunk 1]
```diff
@@ -17,62 +17,60 @@
...
 type ImportDAGErrorModalProps = {
-  importErrors: Array<ImportErrorResponse>;
   onClose: () => void;
   open: boolean;
 };
 
 const PAGE_LIMIT = 15;
 
-export const DAGImportErrorsModal: React.FC<ImportDAGErrorModalProps> = ({ importErrors, onClose, open }) => {
+export const DAGImportErrorsModal: React.FC<ImportDAGErrorModalProps> = ({ onClose, open }) => {
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/DAGImportErrorsModal.tsx:38]: Oh we need to update where we call <DAGImportErrorsModal />

**Review by jedcunningham — APPROVED** [review]

File: airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/DAGImportErrorsModal.tsx (hunk 1 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/DAGImportErrorsModal.tsx:38]: Yep, I don't know what happened with the rebase, i did that but it got lost. Ty

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/DAGImportErrorsModal.tsx:38]: done
