### PR TITLE
Fix grid view log try numbers

### LINKED ISSUE #26194: Extra entry for logs generated with 0 try number when clearing any task instances
### Apache Airflow version

main (development)

### What happened

When clearing any task instances an extra logs entry generated with Zero try number.

Screenshot 2022-09-07 at 1 06 54 PM

### What you think should happen instead

It should not create a entry with zero try number

### How to reproduce

Clear a task instance by hitting clear button on UI and then observe the entry for logs in logs tab

### Operating System

mac os

### Versions of Apache Airflow Providers

_No response_

### Deployment

Astronomer

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by bbovenzi**
The try numbers shown in the grid view logs were showing an extra count and just not consistent with how the regular logs page works.

Fixes https://github.com/apache/airflow/issues/26194#issuecomment-1249183346
Other fixes:
- Default selection to the latest try number
- Count try number at 1 instead of 0

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by bbovenzi** [comment]
cc: @pierrejeambrun

File: airflow/www/static/js/dag/details/taskInstance/Logs/index.tsx [hunk 1]
```diff
@@ -99,12 +98,13 @@ const Logs = ({
   tryNumber,
 }: Props) => {
   const [internalIndexes, externalIndexes] = getLinkIndexes(tryNumber);
-  const [selectedAttempt, setSelectedAttempt] = useState(1);
+  const [manuallySelectedAttempt, setSelectedAttempt] = useState<number | undefined>();
```
Comment (pierrejeambrun) [inline airflow/www/static/js/dag/details/taskInstance/Logs/index.tsx]: nit: Should we rename also the setter ? (Not a big fan of having the state and its setter with different names)

**Review by pierrejeambrun — COMMENTED** [review]
LGTM

**Review by pierrejeambrun — APPROVED** [review]

**Review by dstandish — APPROVED** [review]

File: airflow/www/static/js/dag/details/taskInstance/Logs/index.tsx (hunk 1 above)
Comment (bbovenzi) [reply airflow/www/static/js/dag/details/taskInstance/Logs/index.tsx]: I decided to remove all use of "attempt" and use `selectedTryNumber` and `taskTryNumber` instead.
