### PR TITLE
Enhance Grid view to support RWD

### LINKED ISSUE #55715: Task name shrinking and status bar overlapping with dagruns in Gantt view
### Apache Airflow version

3.1.0b2

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

When user opts to see more dagruns from the drop-down like 25 or 50 and click on a dagrun, task name shrinks and gantt progress bar overlaps with dagruns

Image

### What you think should happen instead?

_No response_

### How to reproduce

Use below dag and opts to see 25 dagruns from the dropdown

```python
import datetime

from airflow.providers.standard.operators.bash import BashOperator
from airflow.providers.standard.operators.python import PythonOperator
from airflow.sdk import DAG


dag = DAG(
    'test_api_dag',
    start_date=datetime.datetime(2025, 8,25),
    schedule='@daily',
    is_paused_upon_creation=False,
    catchup=True,
)

hello_task = BashOperator(
    task_id="hello",
    bash_command="echo hello",
    dag=dag
)

bye_task = BashOperator(
    task_id="bye1",
    bash_command="echo bye",
    dag=dag
)

hello_again = BashOperator(
    task_id="hello_again",
    bash_command="echo hello_again",
    dag=dag
)

hello_task >> bye_task >> hello_again

``` 

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by guan404ming**
## Related Issue

closes #55715

## How

- Implemented responsive breakpoints for Gantt mode:
  - XL (≥1600px): limit 100, options ["5", "10", "25", "50"]
  - LG (≥1024px): limit 25, options ["5", "10", "25"]
  - MD (≥768px): limit 10, options ["5", "10"]
  - SM (<768px): limit 5, options ["5"]
- Added automatic limit setting when the container width is changed and current dag run limit is invalid
- Minor refactor of run type filter display logic

https://github.com/user-attachments/assets/602cc83f-3ffe-4f61-aa74-4d8b6e1db5e5

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/layouts/Details/PanelButtons.tsx [hunk 1]
```diff
@@ -75,16 +77,25 @@ const getOptions = (translate: (key: string) => string) =>
...
-});
+const getWidthBasedConfig = (width: number, showGantt: boolean) => {
+  const breakpoints = showGantt
+    ? [
+        { limit: 100, min: 1600, options: ["5", "10", "25", "50", "100"] }, // xl: extra large screens
+        { limit: 25, min: 1024, options: ["5", "10", "25"] }, // lg: large screens
+        { limit: 10, min: 768, options: ["5", "10"] }, // md: medium screens
+        { limit: 5, min: 0, options: ["5"] }, // sm: small screens and below
+      ]
+    : [{ limit: 5, min: 0, options: ["5", "10", "25", "50", "100", "365"] }];
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/layouts/Details/PanelButtons.tsx]: While we're changing this. Let's just get rid of 100 and 365 options

Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/layouts/Details/PanelButtons.tsx]: Sure, that would be great. I've updated.

**Review by bbovenzi — APPROVED** [review]
