### PR TITLE
Fix #47671: Task name and status overlap in Airflow 3 grid view

### LINKED ISSUE #47671: Task name is overlapping with task status checks in Airflow 3 grid view
### Apache Airflow version

3.0.0b2

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

Task name is overlapping with task status checks in Airflow 3 grid view

Image

### What you think should happen instead?

Task name should not overlap.

### How to reproduce

On AF3 UI, go to Dag details page and scroll the side bar, see the task name is overlapping with task status checks.

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by diogotrodrigues**
## Why:
Issue: #47671 

## The problem:

In the grid view of Airflow 3, task names were overlapping with task status check bars when resizing the window, and the status check bars were also being dragged incorrectly. 

## Solution:

To fix this, i added a check to determine the longest task name and align the fixed starting position of the status check bars accordingly. Additionally, padding adjustments were introduced to prevent overlap, ensuring proper alignment even for short task names by applying a pixel adjustment factor.

## Testing:

 The fix was tested with various task name lengths and complex DAGs containing multiple task names in the grid view.

## Small video showing the before and after:

https://github.com/user-attachments/assets/c658e4a3-52d7-4949-8cb9-611052c16ee6

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by pierrejeambrun — COMMENTED** [review]
Nice, thanks for the comprehensive video.

I think we should Truncate and ellipsis the task name so it is still possible to drag and reduce the space taken by the task name column. (We had a component to do that, the old version of `TruncatedText` maybe)

I can easily imagine a really long task id that will take up half the screen and we will not be able to drag the drawer to the left to make the detail pane bigger.

**Comment by bbovenzi** [comment]
I likle this approach, its much simpler than how I solved this problem in airflow 2.x. But +1 to Pierre's suggestion to set a max length for task names, `TruncatedText` is still a component we can reuse

**Comment by diogotrodrigues** [comment]
Thank you both, @pierrejeambrun and @bbovenzi, for the review! Would you like me to implement those changes? If so, could you clarify them a bit more? I’m not sure I fully understand the concept.

**Comment by pierrejeambrun** [comment]
@diogotrodrigues of course. 

You can re-use the `TruncatedText` that will allow text wrapping on multiple lines when the space becomes too small for the task id to fit.

What Brent suggested on top of that is to use breakpoints responsively change the maxWidth of the container based on the width of the panel. (basically when the panel is big we allow the task_id text to take more space, and when the panel is small we give a smaller value to the `TruncateText` component that will enable text wrapping on multiple line for the column to take less horizontal space)

**Comment by diogotrodrigues** [comment]
@pierrejeambrun but wouldn't this "text wrapping on multiple lines" mess up the grid aliment making it look weird? because the names are aligned with icons that show the task run result.

**Comment by pierrejeambrun** [comment]
That's why I also suggested 'ellipsis' => `task_id_too_long...` But it's worth a try, and we can still alway vertical align the task status icon.

**Comment by diogotrodrigues** [comment]
Ok thanks! I’m still a student and don’t have much experience, but I will try my best !

**Comment by diogotrodrigues** [comment]
Hi @pierrejeambrun and @bbovenzi! Quick update. I managed to truncate the text when it exceeds a certain length so that it’s displayed in two lines. However, I’m having trouble aligning the status icons with the text. Any tips or ideas? Thanks for the help!

Also a quick question my dev-mode stoped working when I try to start airflow in dev-mode and open the local host it just displays a white screen but when running normally it works normally, any idea what could be? already tried in different browsers cleaning the cookies just wait...

**Comment by bbovenzi** [comment]
A few thoughts:

- You might need to rebase since we merged another Grid view change: https://github.com/apache/airflow/pull/47900
- You may also need to rebuild your image if the apiserver is failing
- Can you provide a screenshot of the icons being misaligned?
- Checking out the latest you have pushed. It looks like we lost the "crosshairs" when hovering over a task
Screenshot 2025-03-26 at 12 47 18 PM

**Comment by diogotrodrigues** [comment]
Thanks for the heads up! I already rebased my branch.

Here is a screenshot of what I was saying  of course this is a bit exaggerated normally I would put the max name length bigger but its just for testing purposes and I m having trouble alining the tick marks:

Screenshot 2025-03-26 at 17 30 55

**Comment by diogotrodrigues** [comment]
Ok, will try it Thanks!

**Comment by diogotrodrigues** [comment]
ok I've implemented that but how would you say that a user can see the full name? like by clicking on it or hovering over it and if so should it be fully displayed on the grid ? @bbovenzi

**Comment by diogotrodrigues** [comment]
here is a quick video to demonstrate.

https://github.com/user-attachments/assets/58609adb-9299-4a38-8736-c995e4f34493

Thanks for all the help!

File: airflow-core/src/airflow/ui/src/layouts/Details/Grid/TaskNames.tsx [hunk 1]
```diff
@@ -86,12 +93,20 @@ export const TaskNames = ({ nodes }: Props) => {
...
               isMapped={Boolean(node.is_mapped)}
               label={node.label}
+              overflow="hidden"
               paddingLeft={node.depth * 3 + 2}
               setupTeardownType={node.setup_teardown_type}
+              style={{
+                WebkitBoxOrient: "vertical",
+                WebkitLineClamp: 1,
+              }}
+              title={node.label}
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Details/Grid/TaskNames.tsx]: I don't think title has any effect here ? (title)

File: airflow-core/src/airflow/ui/src/layouts/Details/Grid/TaskNames.tsx [hunk 2]
```diff
@@ -86,12 +93,20 @@ export const TaskNames = ({ nodes }: Props) => {
...
               fontWeight="normal"
               isMapped={Boolean(node.is_mapped)}
               label={node.label}
+              overflow="hidden"
               paddingLeft={node.depth * 3 + 2}
               setupTeardownType={node.setup_teardown_type}
+              style={{
+                WebkitBoxOrient: "vertical",
+                WebkitLineClamp: 1,
+              }}
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Details/Grid/TaskNames.tsx]: To avoid styling duplication, this could be moved inside the `TaskName` component. 

This way `TaskLink` in the Graph can also ellipsis if too long. (We need some adjustment there).

File: airflow-core/src/airflow/ui/src/layouts/Details/Grid/Grid.tsx [hunk 3]
```diff
@@ -73,13 +73,21 @@ export const Grid = ({ limit }: Props) => {
...
   );
 
+  const maxTaskNameLength = Math.max.apply(
+    undefined,
+    flatNodes.map((node) => node.label.length),
+  );
+
+  const extraPadding = maxTaskNameLength < 20 ? 30 : 0;
+  const taskNameWidth = maxTaskNameLength > 30 ? "150px" : `${maxTaskNameLength * 8 + extraPadding}px`;
+
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Details/Grid/Grid.tsx]: I'm not a big fan of all that calculation to fix the columns width.

Can we make it relative maybe `20%` of the available pane space. (The left pane allocated to the grid display).

Just an idea.

File: airflow-core/src/airflow/ui/src/layouts/Details/Grid/Grid.tsx [hunk 4]
```diff
@@ -73,13 +73,21 @@ export const Grid = ({ limit }: Props) => {
...
   return (
-    <Flex justifyContent="flex-end" mr={3} position="relative" pt={50} width="100%">
-      <Box position="absolute" top="150px" width="100%">
+    <Flex justifyContent="flex-start" mr={3} position="relative" pt={50} width="100%">
+      <Box position="absolute" top="150px" width={taskNameWidth}>
         <TaskNames nodes={flatNodes} />
       </Box>
       <Box>
-        <Flex position="relative">
+        <Flex ml={taskNameWidth} position="absolute">
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Details/Grid/Grid.tsx]: I don't understand that, this looks hacky, why do we add a gigantic marging left so the column is not overlapped by the rest of the component and place it `absolute` ?

**Review by pierrejeambrun — COMMENTED** [review]
Thanks.

A few suggestions. :)

Also I think the grid should take all the space available, and only ellipsis / collapse when there is not enough space.

Screenshot 2025-03-31 at 10 04 05

File: airflow-core/src/airflow/ui/src/layouts/Details/Grid/Grid.tsx (hunk 4 above)
Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/layouts/Details/Grid/Grid.tsx]: Yes, we probably need to rearrange a bit of this css so the task name column can do something like flexGrow={1} to fit the available space instead of needing this absolute positioning.

**Comment by diogotrodrigues** [comment]
Sorry for the noise! Accidentally triggered CODEOWNERS by pushing an incorrect commit — it's already reverted.

File: airflow-core/src/airflow/ui/src/layouts/Details/Grid/TaskNames.tsx (hunk 1 above)
Comment (diogotrodrigues) [reply airflow-core/src/airflow/ui/src/layouts/Details/Grid/TaskNames.tsx]: Its there so when you hover over the ellipsis it shows that label with the full name like this:

Screenshot 2025-04-06 at 19 19 09

**Comment by diogotrodrigues** [comment]
I have updated the code with the changes you asked @bbovenzi and @pierrejeambrun, to avoid styling duplication, I moved it inside the TaskName component and also Updated the grid layout so that the status bars are now fully visible, while task names use the remaining space. If a task name doesn’t fit, it’s truncated with an ellipsis, and hovering over it reveals the full name in a tooltip.

Thank you for all the help, ideas, and support throughout this process!

Here is a quick video demonstrating the changes:

https://github.com/user-attachments/assets/2e65c62e-9764-4d6a-9904-489c91fa2d0e

**Comment by diogotrodrigues** [comment]
Hi @pierrejeambrun I saw your PR regarding the toggle group button. I've already rebased my code to use the new feature.

I added a new box to handle the case where the method returns undefined when groups don't exist. Without it, the task names were getting misaligned with the icons.

**Comment by diogotrodrigues** [comment]
Quick update! I saw Brent’s PR about the toggle group button being moved to the panel buttons banner. I’ve already rebased and made the necessary adjustments on my end.

**Review by ashb — APPROVED** [review]
LGTM, but I'd like @pierrejeambrun or @bbovenzi to review before we merge.

@diogotrodrigues Are the screenshots in the PR desc up to date with latest changes?

**Comment by diogotrodrigues** [comment]
Yes @ashb, the last video is up to date with the current changes. The only thing missing is the new toggle group button, as that DAG didn't include groups. However, I've rebased and ensured that everything works properly with my changes. If you'd like, I can create a new video that includes a DAG with groups.

File: airflow-core/src/airflow/ui/src/layouts/Details/Grid/Grid.tsx [hunk 5]
```diff
@@ -71,11 +71,11 @@ export const Grid = ({ limit }: Props) => {
   );
 
   return (
-    <Flex justifyContent="flex-end" position="relative" pt={50} width="100%">
-      <Box position="absolute" top="150px" width="100%">
+    <Flex justifyContent="flex-start" position="relative" pt={50} width="100%">
+      <Box mr="10px" position="relative" top="100px">
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Details/Grid/Grid.tsx]: mr={3}

Chakra standardise such value 3 = 9px I think, which is the closest to 10

File: airflow-core/src/airflow/ui/src/components/TaskName.tsx [hunk 6]
```diff
@@ -51,15 +51,31 @@ export const TaskName = ({
...
     );
   }
 
   return (
-    <Text fontSize={isZoomedOut ? "lg" : "md"} fontWeight="bold" {...rest}>
+    <Text
+      fontSize={isZoomedOut ? "lg" : "md"}
+      fontWeight="bold"
+      style={{
+        WebkitBoxOrient: "vertical",
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/components/TaskName.tsx]: What’s the rational behind using only WebKit css props, and not the default ones ?

**Review by pierrejeambrun — APPROVED** [review]
Code looks code, just a few nit / questions for my own understanding. 

Reviewing from my phone, I was not able to test this locally

File: airflow-core/src/airflow/ui/src/components/TaskName.tsx (hunk 6 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/components/TaskName.tsx]: I think flexbox supersed box orient and all.

Comment (diogotrodrigues) [reply airflow-core/src/airflow/ui/src/components/TaskName.tsx]: white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
I can do it like this, right @pierrejeambrun ? I see it can be simpler, I will only try to use default css in the past I wasn't able to that effect that the name collapses when you make the window smaller but I will look in to it.

File: airflow-core/src/airflow/ui/src/layouts/Details/Grid/Grid.tsx (hunk 5 above)
Comment (diogotrodrigues) [reply airflow-core/src/airflow/ui/src/layouts/Details/Grid/Grid.tsx]: Ok! I will change to that, thanks!

**Review by bugraoz93 — APPROVED** [review]
Found time to test it locally. Names collapse correctly with task boxes. Looks good on the user end!

**Comment by diogotrodrigues** [comment]
You were right, @pierrejeambrun  there was no need to use WebKit. I rewrote the code using just the default props, and it works exactly as before (like in the last video). I also applied your suggestion to change mr="10px" to mr={3}. Thanks for the help! Let me know if there’s anything else you’d like me to adjust.

File: airflow-core/src/airflow/ui/src/components/TaskName.tsx (hunk 6 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/components/TaskName.tsx]: Yes that sounds better

Comment (diogotrodrigues) [reply airflow-core/src/airflow/ui/src/components/TaskName.tsx]: I already fixed it!

**Review by pierrejeambrun — APPROVED** [review]
Nice thanks.

**Comment by pierrejeambrun** [comment]
I just pushed a commit so the grid grow/expand to use all the available space in the left pane:
Screenshot 2025-04-10 at 11 31 12
Screenshot 2025-04-10 at 11 31 18

**Comment by diogotrodrigues** [comment]
@pierrejeambrun I tested your addition locally. The only minor “issue” is that, with the flex growth enabled, the task run results now shift to the right along with the resize bar. Previously, they would remain fixed at the end of the full displayed name. It’s really just a matter of preference, though.

**Comment by pierrejeambrun** [comment]
Yes that's the goal of this change, we don't want to have most of the screen displayed with just empty space
Screenshot 2025-04-10 at 11 56 23

**Comment by diogotrodrigues** [comment]
Perfect then! I was just confirming.

**Comment by pierrejeambrun** [comment]
Thanks for your contribution!

**Comment by diogotrodrigues** [comment]
Thanks for all the support and help though the process!
