### PR TITLE
 UI: Show clear permission toast for 403 errors on user actions

### LINKED ISSUE #61460: When a DAG Viewer tries to trigger a DAG, the action fails with 403
### Apache Airflow version

3.1.7

### If "Other Airflow 3 version" selected, which one?

_No response_

### What happened?

When a DAG Viewer tries to trigger a DAG, the action fails with 403, and the Home → View History also shows 403 without clearly indicating it’s an authorization issue.
From a user experience perspective, it might be clearer if permission-related failures explicitly mention insufficient permissions / role restrictions

### What you think should happen instead?

it might be clearer if permission-related failures explicitly mention insufficient permissions / role restrictions

### How to reproduce

Testing during DAG level roles implementation on the Astronomer Astro client -- requires internal Astro access

### Operating System

macOS sequoia 15.7.3

### Versions of Apache Airflow Providers

_No response_

### Deployment

Astronomer

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Abhishekmishra2808**
## Description 
Fixes #61460

This PR improves the user experience when an action fails due to insufficient permissions.

A global React Query `MutationCache` error handler now intercepts HTTP **403 (Forbidden)** responses and displays a clear toast message:

> **Insufficient Permissions — You do not have permission to perform this action.**

The toast is deduplicated to prevent spam when multiple mutations fail simultaneously. Existing retry behavior and error propagation remain unchanged.
Scope is intentionally limited to **mutations (user actions)** to avoid noisy background query refresh toasts.
This provides clearer feedback for protected UI actions (such as triggering DAGs or editing resources) with minimal risk and no behavioral side effects.
### AFTER
image

### CODE REVIEW

**Comment by jscheffl** [comment]
Static checks are failing, please take a look to setup local validations: https://github.com/apache/airflow/blob/main/contributing-docs/03a_contributors_quick_start_beginners.rst

**Comment by choo121600** [comment]
It would be helpful for the review if you could add a screenshot showing how the toast message looks😀

**Comment by bbovenzi** [comment]
Instead of manually writing error messages in the UI, it would be better to make sure that fastapi is sending the correct error messages or that the UI is using the correct error message that is coming from the API.

File: airflow-core/src/airflow/ui/src/queryClient.ts [hunk 1]
```diff
@@ -39,6 +40,31 @@ const retryFunction = (failureCount: number, error: unknown) => {
...
+
+  if (status === 403) {
+    // Only show one 403 toast at a time to prevent toast spam
+    // when multiple mutations fail simultaneously
+    if (active403ToastId === undefined || !toaster.isActive(active403ToastId)) {
+      active403ToastId = toaster.create({
+        description: "You do not have permission to perform this action.",
+        title: "Insufficient Permissions",
+        type: "error",
+      });
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/queryClient.ts:61]: This can't be hard coded but needs a translation.

File: airflow-core/src/airflow/ui/src/queryClient.ts [hunk 2]
```diff
@@ -39,6 +40,31 @@ const retryFunction = (failureCount: number, error: unknown) => {
...
+  // Using nullish coalescing to safely find the status regardless of error shape
+  const status =
+    (error as { status?: number }).status ??
+    (error as { response?: { status?: number } }).response?.status;
+
+  if (status === 403) {
+    // Only show one 403 toast at a time to prevent toast spam
+    // when multiple mutations fail simultaneously
+    if (active403ToastId === undefined || !toaster.isActive(active403ToastId)) {
+      active403ToastId = toaster.create({
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/queryClient.ts:57]: When are we releasing the tracking? For other 403 errors to actually show a message? Example in the video above.

**Review by pierrejeambrun — COMMENTED** [review]
Good idea, thanks for the PR.

Also we probably need to do some cleaning because in multiple places we still have the specific mutation onError hook that will also raise a toaster. We end up displaying  two toasters.

https://github.com/user-attachments/assets/9a5ea188-6d70-423d-befd-8de685e46672

File: airflow-core/src/airflow/ui/src/queryClient.ts (hunk 1 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/queryClient.ts:61]: https://github.com/apache/airflow/pull/61560 will take care of this and introduce a common 'handler' with existing toaster.

Then in this PR we can centralize all the calls to the toaster handler into this MutationCache we created. (And remove all of the manual toaster creation call we have everywhere)

**Comment by Abhishekmishra2808** [comment]
Hi @pierrejeambrun,
I’ve addressed all the suggestions you shared. I’ve also attached a screenshot showing the updated behavior, the duplicate toaster issue is now resolved.

Please let me know if anything else needs improvement.

File: airflow-core/src/airflow/ui/src/queryClient.ts (hunk 1 above)
Comment (Abhishekmishra2808) [reply airflow-core/src/airflow/ui/src/queryClient.ts:61]: I’ve updated the PR to use the translation system instead of hard-coded strings and centralized the 403 handling in MutationCache. Mutation-level toasters now skip 403 errors, so duplicates are no longer shown.

File: airflow-core/src/airflow/ui/src/queryClient.ts (hunk 2 above)
Comment (Abhishekmishra2808) [reply airflow-core/src/airflow/ui/src/queryClient.ts:57]: The 403 handling is already centralized in `MutationCache`, so it applies to all mutations returning 403, not just the case shown in the video. Other 403 errors will also display the global permission message.

This works independently but aligns with the common handler introduced in #61560.

File: airflow-core/src/airflow/ui/src/queryClient.ts [hunk 3]
```diff
@@ -39,6 +41,33 @@ const retryFunction = (failureCount: number, error: unknown) => {
...
+    (error as { status?: number }).status ?? (error as { response?: { status?: number } }).response?.status;
+
+  if (status === 403) {
+    // Only show one 403 toast at a time to prevent toast spam
+    // when multiple mutations fail simultaneously
+    if (active403ToastId === undefined || !toaster.isActive(active403ToastId)) {
+      active403ToastId = toaster.create({
+        description: i18n.t(
+          "errors.forbidden.description",
+          "You do not have permission to perform this action.",
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/queryClient.ts]:
```suggestion
```

File: airflow-core/src/airflow/ui/src/queries/useClearRun.ts
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/queries/useClearRun.ts]: I think we need to extract this into a utility function to not have this piece of code duplicated all over the place. (from handling the error and skipping the toaster creation, to calling the 'toaster.create....`.
```ts
const createErrorToaster = (error, titleKey, ...) => {}
```

**Review by pierrejeambrun — COMMENTED** [review]
Looking good and working as expected. 

Just a couple suggestions and we should be able to move merge.

File: airflow-core/src/airflow/ui/src/queries/useClearRun.ts
Comment (Abhishekmishra2808) [reply airflow-core/src/airflow/ui/src/queries/useClearRun.ts]: Good point. I’ll extract this into a shared utility to avoid duplication and update the existing usages accordingly.

**Comment by Abhishekmishra2808** [comment]
@pierrejeambrun fixed all the changes suggested by you, could you please review it now?

File: airflow-core/src/airflow/ui/src/queryClient.ts [hunk 4]
```diff
@@ -39,6 +41,32 @@ const retryFunction = (failureCount: number, error: unknown) => {
...
+  // Using nullish coalescing to safely find the status regardless of error shape
+  const status =
+    (error as { status?: number }).status ?? (error as { response?: { status?: number } }).response?.status;
+
+  if (status === 403) {
+    // Only show one 403 toast at a time to prevent toast spam
+    // when multiple mutations fail simultaneously
+    if (active403ToastId === undefined || !toaster.isActive(active403ToastId)) {
+      active403ToastId = toaster.create({
+        description: i18n.t(
```
Comment (choo121600) [inline airflow-core/src/airflow/ui/src/queryClient.ts]: It looks like the static checks are failing here.
Could you please take a look?

File: airflow-core/src/airflow/ui/src/queries/useDagParsing.ts [hunk 5]
```diff
@@ -30,7 +30,16 @@ export const useDagParsing = ({ dagId }: { readonly dagId: string }) => {
   const queryClient = useQueryClient();
   const { t: translate } = useTranslation("dag");
 
-  const onError = () => {
+  const onError = (error: unknown) => {
+    // Get status from error
+    const status =
+      (error as { status?: number }).status ?? (error as { response?: { status?: number } }).response?.status;
+
+    // Skip 403 errors as they are handled by MutationCache
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/queries/useDagParsing.ts]: Can you reuse the 'createErrorToaster' here?

File: airflow-core/src/airflow/ui/src/queries/useDeleteConnection.ts [hunk 6]
```diff
@@ -27,6 +27,16 @@ export const useDeleteConnection = ({ onSuccessConfirm }: { onSuccessConfirm: ()
   const { t: translate } = useTranslation(["admin", "common"]);
 
   const onError = (error: Error) => {
+    // Get status from error
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/queries/useDeleteConnection.ts]: Probably here too. etc... below other instances.

File: airflow-core/src/airflow/ui/src/queries/useDagParsing.ts (hunk 5 above)
Comment (Abhishekmishra2808) [reply airflow-core/src/airflow/ui/src/queries/useDagParsing.ts]: Yes, I have addressed in the latest commit!

File: airflow-core/src/airflow/ui/src/queries/useDeleteConnection.ts (hunk 6 above)
Comment (Abhishekmishra2808) [reply airflow-core/src/airflow/ui/src/queries/useDeleteConnection.ts]: done !

File: airflow-core/src/airflow/ui/src/queryClient.ts (hunk 4 above)
Comment (Abhishekmishra2808) [reply airflow-core/src/airflow/ui/src/queryClient.ts]: now check ! CI turned green :-)

File: airflow-core/src/airflow/ui/src/queries/useDeleteDag.ts [hunk 7]
```diff
@@ -34,6 +34,16 @@ export const useDeleteDag = ({
   const { t: translate } = useTranslation();
 
   const onError = (error: Error) => {
+    // Get status from error
+    const status =
+      (error as unknown as { status?: number }).status ??
+      (error as unknown as { response?: { status?: number } }).response?.status;
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/queries/useDeleteDag.ts]: I feel like we should pull this out into a util instead of copy-pasting this code all over.

Comment (Abhishekmishra2808) [reply airflow-core/src/airflow/ui/src/queries/useDeleteDag.ts]: @bbovenzi Nice Idea, Please check out the latest commit!

**Review by pierrejeambrun — COMMENTED** [review]
You introduced a new `getErrorStatus` and `getErrorMessage` that is only used in this PR while the entire codebase is still doing manual check everywhere else. It wouldn't be needed if you were using the `createErrorToaster` everywhere as requested above. No idea why the `createErrorToaster` is only used 3 times, and most of the time we still do that creation manually.

This is taking a lot of back and forth and energy for something that isn't suppose to. Please make sure you address properly and spend the time to make the code as maintainable and readable as possible before asking for a final review.

File: airflow-core/src/airflow/ui/src/queryClient.ts [hunk 8]
```diff
@@ -39,6 +41,30 @@ const retryFunction = (failureCount: number, error: unknown) => {
...
+// Track active 403 toast to prevent duplicates when multiple mutations fail
+let active403ToastId: string | undefined;
+
+// Error handler for 403 (Forbidden) responses on user-initiated actions
+const handle403Error = (error: unknown) => {
+  // Check for 403 (Forbidden) only to avoid interfering with 401 (Auth) logic
+  // Using nullish coalescing to safely find the status regardless of error shape
+  const status =
+    (error as { status?: number }).status ?? (error as { response?: { status?: number } }).response?.status;
+
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/queryClient.ts]: Why not use getStatus? Same for other places.

Comment (Abhishekmishra2808) [reply airflow-core/src/airflow/ui/src/queryClient.ts]: addressed in the latest commit.

File: airflow-core/src/airflow/ui/src/queries/useDagParsing.ts [hunk 9]
```diff
@@ -25,15 +25,15 @@ import {
...
-  const { t: translate } = useTranslation(["dag", "common"]);
-  const onError = createErrorToaster(translate, {
-    description: translate("parse.toaster.error.description"),
-    title: translate("parse.toaster.error.title"),
-  });
+  const { t: translate } = useTranslation("dag");
+
+  const onError = (error: unknown) => {
+    createErrorToaster(error, { titleKey: "dag:parse.toaster.error.title" }, translate);
+  };
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/queries/useDagParsing.ts:36]: You need to delete `createErrorToaster` from `src/components/ui/createErrorToaster`, I think it was only used here.

**Review by pierrejeambrun — COMMENTED** [review]
Working as expected a couple of suggestions then we can merge.

File: airflow-core/src/airflow/ui/src/queries/useDagParsing.ts (hunk 9 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/queries/useDagParsing.ts:36]: Weird that the CI doesn't detect dead code

Comment (Abhishekmishra2808) [reply airflow-core/src/airflow/ui/src/queries/useDagParsing.ts:36]: Accepted

**Review by pierrejeambrun — APPROVED** [review]
