### PR TITLE
Fix editing connection with sensitive extra field

### LINKED ISSUE #52301: Editing connection with sensitive extra field saves literal asterisks
### Apache Airflow version

3.0.2 (actually 3.0.0+astro.2)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

If an connection has an extra field with a name like "token" or other sensitive keyword, its value gets masked as "***" when displayed.  If you edit and save the connection (with or without any actual changes to any field), the extra field will get updated to a literal "***".

### What you think should happen instead?

Extra fields which are deemed sensitive should retain their original values when saving, if unmodified.

### How to reproduce

1. In the Airflow UI, add a new connection with any type, e.g. "http".
2. In the "Extra Fields JSON" section, add a sensitive key/value pair such as `{"token": "abcde"}`.
3. Save the connection.
4. Confirm the value saved correctly in an unobfuscated way - for example `airflow connections export ...`.
5. Click to edit the connection.  Note that the value for "token" in Extra Fields renders as "***".
6. Save.
7. Repeat step 4 and note that the value is now the literal "***".

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-http==5.3.0
apache-airflow-providers-standard==1.0.0

### Deployment

Docker-Compose

### Deployment details

Happens in Astronomer, as well as locally.

### Anything else?

Happens always

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by shubhamraj-git**
closes: #52301

1. This will disable the button when there is no changes to save.
2. Would update the conf, only when there is a change.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

**Comment by amoghrajesh** [comment]
Not a critical fix, maybe land it for 3.1?

**Comment by shubhamraj-git** [comment]
@amoghrajesh Updating the connection with sensitive value is a problem and result in failures since it will change the values. Would be good to have fix.

**Comment by jscheffl** [comment]
> Not a critical fix, maybe land it for 3.1?

I'd propose to back-port, else in 3.0.x it messes-up the secrets if you edit and save via connections form.

**Comment by jscheffl** [comment]
I tested locally and the standard fields are still published redacted... and then when savong three stars are stored as password.
image
...and same for a SAS token password:
image

UPDATE: Uuups had an issue to switch to correct branch - after making the review "right" all is working as expected...

**Review by jscheffl — COMMENTED** [review]
I think it is OK but static checks need to be fixed

**Comment by shubhamraj-git** [comment]
Reference to slack discussion: https://apache-airflow.slack.com/archives/C0809U4S1Q9/p1751108215738019

**Review by potiuk — APPROVED** [review]
Looks good - tests are testing the **right**  think but I can't comment too much on the javascript code :)

**Review by jscheffl — APPROVED** [review]
Good for me now if CI is green

**Comment by amoghrajesh** [comment]
Thanks! Yeah I think it should be ok with show unredacted value for people to edit, it is a really bad experience (atleast for me) to find that in the "airflow connections export", change it in the UI, if im experimenting especially. If someone is changing stuff from the UI, they are authenticated at the very least.

File: airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx [hunk 1]
```diff
@@ -94,6 +94,14 @@ const ConnectionForm = ({
     mutateConnection(data);
   };
 
+  const hasChanges = () => {
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx:97]: Nit. functions should start with a verb.

But we don't even need a function here.

`const hasChanges = isDirty || (JSON.stringify(JSON.parse(extra)) !== JSON.stringify(JSON.parse(initialConnection.extra)))`

Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx:97]: And whats the point of parsing first?

Comment (shubhamraj-git) [reply airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx:97]: Actually yes, in current state it shouldn't be, In starting I was doing multiple things and debugging, later should have changed it.
For parsing, A user can add something from cli which would not be in UI formatted way, it should not be treated as different value.

Comment (shubhamraj-git) [reply airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx:97]: Actually yes, in current state func shouldn't be, In starting I was doing multiple things and debugging, later should have changed it.
Reason for parsing, A user can add something from cli which would not be in UI formatted way, it should not be treated as different value.

**Comment by pierrejeambrun** [comment]
I am really surprised to see that we are not redacting sensitive fields from connection anymore, this seems to go against the security model. (any authenticated user with access to connection can retrieve any sensitive fields).

Do you mind explaining the reason for that change (beside the linked issue that could be solved differently, for instance detect and ignore sentitive extra fields when updating)

**Comment by pierrejeambrun** [comment]
Related issue: https://github.com/apache/airflow/issues/53753

**Comment by shubhamraj-git** [comment]
@pierrejeambrun This was discussed at slack [thread](https://apache-airflow.slack.com/archives/C0809U4S1Q9/p1751108215738019). Reason for not redacting the sensitive value was since the user is authenticated, they should be able to see it. We expose this via cli too. Also, connection being a privileged role.
cc: @potiuk

**Comment by ashb** [comment]
> We expose this via cli too

CLI is a very different security model to an API, so I don't think that is relevant here.


Regardless, there are better ways we can let the connection be edited without exposing the password (think a PATCH request to only update edited fields etc.)

**Comment by shubhamraj-git** [comment]
I agree, Actually this was not done just to edit field.
This might give the user perception that secret credentials are hashed but it isn't and the reason discussed was that it just don't show up on the screen which could be handled by having a reveal button as like passwords.
Yes, but if we want to redact this via api, it's okay since we have a different flow for the execution APIs which might need to have access.

**Comment by potiuk** [comment]
> CLI is a very different security model to an API, so I don't think that is relevant here.

> Regardless, there are better ways we can let the connection be edited without exposing the password (think a PATCH request to only update edited fields etc.)

Sure. This is a new feature that we might think of adding to make it "safer" but it has **always** been like that (at least for editing not for viewing). Note that if we do it - we also have to do it for all the other sensitive fields passed in JSON extra - a number of connections have sensitive fields - such as private keys so would have to implement incremental patching of the JSON extras if we want to implement such model.

**Comment by bugraoz93** [comment]
Small note, this is not related to the `airflow` CLI as a direct correlation but this is directly impacting how `airflowctl` behaves since it purely depends on the API in a way that, anything visible on the API will be in `airflowctl` too
