### PR TITLE
Persisting filter by tag

### LINKED ISSUE #60590: DAG list `Filter by tag` state not persisted in Airflow 3.x
### Apache Airflow version

3.1.6

### If "Other Airflow 3 version" selected, which one?

_No response_

### What happened?

In Airflow 3.1.6, the `Filter by tag` selection on the DAGs list page does not persist:

* Navigating away from the DAGs list and back
* Closing and reopening the browser tab

The selected tag filter is cleared each time, requiring the user to re-select the tag(s).

Observed behavior:
* Tag selection only lives in in-memory UI state
* No persistence via URL query params, browser storage, or server session

Regression context
* In Airflow `2.10.5`, tag filtering does persist across navigation and browser restarts.
* In Airflow `2.x` this behavior is implemented server-side via Flask session storage (`flask.session["tags_filter"]`) in `airflow/www/views.py`.

### What you think should happen instead?

The DAG tag filter should persist across:
* Page navigation
* Browser restarts

This is important for usability when working with large DAG inventories or tag-based workflows.

What likely went wrong

During the Airflow 3.x UI migration from server-rendered Flask views to a React-based UI:

* The legacy persistence mechanism (Flask session + redirect logic) was removed
* No equivalent client-side persistence was introduced

As a result, the DAG tag filter state is not stored in:

* URL query parameters
* localStorage / sessionStorage
* Any server-side user preference store

### How to reproduce

https://github.com/user-attachments/assets/5f631e79-58a6-431f-aba9-a5470650df5e

### Operating System

LM 21.3 with docker python:3.12-slim-bookworm

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by zachliu**
* closes: https://github.com/apache/airflow/issues/60590

I followed the existing pattern established by [src/components/DataTable/useTableUrlState.ts](https://github.com/zachliu/airflow/blob/main/airflow-core/src/airflow/ui/src/components/DataTable/useTableUrlState.ts), which persists table sort preferences to `localStorage` using the same approach.

 

---

##### Was generative AI tooling used to co-author this PR?

- [ ] Yes (please specify the tool below)

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments). You can add this file in a follow-up commit after the PR is created so you know the PR number.

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+
+export const useTagFilter = () => {
+  const [searchParams, setSearchParams] = useSearchParams();
+  const [savedTags, setSavedTags] = useLocalStorage<Array<string>>(TAGS, []);
+  const [savedTagMatchMode, setSavedTagMatchMode] = useLocalStorage<TagMatchMode>(TAGS_MATCH_MODE, "any");
+
+  const urlTags = searchParams.getAll(TAGS);
+  const urlMatchMode = searchParams.get(TAGS_MATCH_MODE);
+
+  // URL params take precedence; fall back to localStorage when URL has no tags.
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts:36]: I'd rather we just rely on url params and not have a competing source of truth with localStorage

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+    searchParams.delete(OFFSET);
+    setSearchParams(searchParams);
+    setSavedTags(tags);
+  };
+
+  const setTagFilterMode = (mode: TagMatchMode) => {
+    searchParams.set(TAGS_MATCH_MODE, mode);
+    setSearchParams(searchParams);
+    setSavedTagMatchMode(mode);
+  };
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts:60]: I think it would be great to have some unit tests for these functions. Adding/removing tags, toggling any/all, especially when tags length changes from below to above 2

**Review by bbovenzi — COMMENTED** [review]
Nice! Just two comments.

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts (hunk 1 above)
Comment (zachliu) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts:36]: but isn't relying solely on url params causing the issue in the first place?
for example, i do a page navigation by clicking the "Dags", the url takes me to `.../dags` with no params, i lost all previously set tag filters

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts (hunk 2 above)
Comment (zachliu) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts:60]: gotcha, will do :rocket:

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts (hunk 1 above)
Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts:36]: Ok ignore this then.

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts (hunk 2 above)
Comment (zachliu) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts:60]: unit tests added :heavy_check_mark:

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.test.tsx [hunk 3]
```diff
@@ -0,0 +1,311 @@
...
+    });
+
+    act(() => {
+      result.current.setSelectedTags([]);
+    });
+
+    expect(result.current.selectedTags).toEqual([]);
+  });
+
+  it("resets match mode to 'any' when fewer than 2 tags", () => {
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.test.tsx]: I'm not sure about that. If someone edits the tags and want to replace one, removing and then adding another one, this can change the match mode while this is not expected. 

(I want "all", then I realize tags aren't correct, remove the incorrect tag, add the correct one, match mode is gone back to 'any' which isn't what I want)

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+    }
+    searchParams.delete(OFFSET);
+    setSearchParams(searchParams);
+    setSavedTags(tags);
+  };
+
+  const setTagFilterMode = (mode: TagMatchMode) => {
+    searchParams.set(TAGS_MATCH_MODE, mode);
+    setSearchParams(searchParams);
+    setSavedTagMatchMode(mode);
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts:59]: We should probably also reset OFFSET when changing the match mode. Going from one to another could leave us on a blank page. For instance from going to 'any' to 'all'.

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.test.tsx (hunk 3 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.test.tsx]: I would simplify this and not have any side effect from one filter to another. Let the user handle them separately.

**Review by pierrejeambrun — COMMENTED** [review]
Thanks for the PR!

LGTM just a few nits / suggestions.

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.test.tsx (hunk 3 above)
Comment (zachliu) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.test.tsx]: good point about the ux — that replace-one-tag workflow would be frustrating. i just wanted to flag that this behavior was carried over from the existing code on main [DagsFilters.tsx](https://github.com/apache/airflow/blob/48ec002f4ebb7f868a7f3f789496b384e224cd24/airflow-core/src/airflow/ui/src/pages/DagsList/DagsFilters/DagsFilters.tsx#L142):

https://github.com/apache/airflow/blob/48ec002f4ebb7f868a7f3f789496b384e224cd24/airflow-core/src/airflow/ui/src/pages/DagsList/DagsFilters/DagsFilters.tsx#L142-L144


happy to remove it as part of this pr and make the two filters fully independent — just want to confirm that's what you'd prefer, since it would be a behavior change from what's currently shipped

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts (hunk 4 above)
Comment (zachliu) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts:59]: good point. i'll reset offset too 👍

Comment (zachliu) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.ts:59]: done :rocket:

File: airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.test.tsx (hunk 3 above)
Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.test.tsx]: Yes let's remove it.

Comment (zachliu) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.test.tsx]: on it :rocket:

Comment (zachliu) [reply airflow-core/src/airflow/ui/src/pages/DagsList/useTagFilter.test.tsx]: @bbovenzi @pierrejeambrun done :rocket:

**Review by pierrejeambrun — APPROVED** [review]
LGTM
