### PR TITLE
Fix links for DurationChart

### LINKED ISSUE #57582: Getting 404 error on clicking the overview for task runs of a mapped task
### Apache Airflow version

3.1.1

### If "Other Airflow 2/3 version" selected, which one?

_No response_

### What happened?

For the mapped tasks under a dag, when the overview section is clicked to get further insights on the task run, 404 error as shown in the attached screenshot is seen.
This issue is not seen for the tasks that do not have mapped tasks. 

Image

### What you think should happen instead?

The task instance run details should be loaded similar to the details loaded on clicking the individual task instances under "Task Instances" sections of mapped tasks.

### How to reproduce

- Deploy a dag with the tasks containing mapped tasks.
- Run the task and verify the overview section of the task with mapped instances
- Click on one of the task instance runs from the "Overview" section - Last 14 Task Instances.
- Verify if the task instance details are loaded

### Operating System

os

### Versions of Apache Airflow Providers

_No response_

### Deployment

Astronomer

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pierrejeambrun**
Closes: https://github.com/apache/airflow/issues/57582

### After:
https://github.com/user-attachments/assets/a79d9288-99c0-4fa2-a9cb-458aab8c1f46

### CODE REVIEW

**Review by choo121600 — APPROVED** [review]
It looks good to me :-D

File: airflow-core/src/airflow/ui/src/components/DurationChart.tsx [hunk 1]
```diff
@@ -191,9 +192,17 @@ export const DurationChart = ({
               }
               case "Task Instance": {
                 const entry = entries[element.index] as TaskInstanceResponse | undefined;
-                const baseUrl = `/dags/${entry?.dag_id}/runs/${entry?.dag_run_id}`;
 
-                navigate(`${baseUrl}/tasks/${entry?.task_id}`);
+                const baseUrl = buildTaskInstanceUrl({
+                  currentPathname: location.pathname,
+                  dagId: entry?.dag_id ?? "",
```
Comment (jedcunningham) [inline airflow-core/src/airflow/ui/src/components/DurationChart.tsx]: Is it possible for dag_id, run_id, and task_id to be null?

**Review by jedcunningham — APPROVED** [review]

File: airflow-core/src/airflow/ui/src/components/DurationChart.tsx (hunk 1 above)
Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/components/DurationChart.tsx]: We could add a quick check to make sure entry isn't undefined before creating the baseUrl. Then we wouldn't need so many conditions

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/components/DurationChart.tsx]: Yes I was able to rewrite that in a cleaner way.
