### PR TITLE
UI: Add Expand/Collapse all to XComs page

### LINKED ISSUE #56061: No expand/collapse option on the Xcoms page
### Apache Airflow version

3.0.6

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

Xcoms page:
Image

Audit logs page:
Image

### What you think should happen instead?

_No response_

### How to reproduce

Navigate to the Xcoms page via 'Browse' nav bar and xcom expand/collapse option should be there as its present in the Audit logs page

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by KatalKavya96**
UI: Restore “Expand/Collapse all” on XComs page
closes: #56061 

### What’s changed

- Added Expand all / Collapse all controls to the XComs page toolbar, matching the Audit Logs page.

- Plumbed a boolean open state (via Chakra’s useDisclosure) into the XComs table and forwarded it to each row’s value renderer.

- Updated XComEntry to accept an optional open prop and pass collapsed: !open to RenderedJsonField so JSON objects/arrays expand or collapse globally.

- Kept scalar values rendering as plain text; added lightweight URL auto-linking for better readability.

### Rationale

- The Audit Logs page exposes a global expand/collapse control for JSON content, but XComs did not. This restores UI parity and improves usability when scanning large XCom payloads.

### Implementation notes

- No API or backend changes.

- Reused existing i18n keys from Audit Logs for button labels (auditLog.actions.expandAllExtra, auditLog.actions.collapseAllExtra).

- No changes to table sorting, pagination, or filters.

### Demo Video

https://github.com/user-attachments/assets/ef7273bd-2169-488a-88c0-2fc1d9f59043

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/pages/XCom/XComEntry.tsx [hunk 1]
```diff
@@ -72,31 +87,22 @@ export const XComEntry = ({ dagId, mapIndex, runId, taskId, xcomKey }: XComEntry
...
+  return (
     <HStack>
-      {isObjectOrArray ? (
-        <RenderedJsonField content={xcomValue as object} enableClipboard={false} />
+      {isObjectLike(value) ? (
+        <RenderedJsonField content={value} jsonProps={{ collapsed: !open }} />
       ) : (
         <Text>{renderTextWithLinks(valueFormatted)}</Text>
       )}
-      {xcomValue === undefined || xcomValue === null ? undefined : (
```
Comment (RoyLee1224) [inline airflow-core/src/airflow/ui/src/pages/XCom/XComEntry.tsx:95]: The copy-to-clipboard button seems to be missing for non-JSON/string values now.
CleanShot 2025-09-26 at 14 03 12

File: airflow-core/src/airflow/ui/src/pages/XCom/XComEntry.tsx
Comment (RoyLee1224) [inline airflow-core/src/airflow/ui/src/pages/XCom/XComEntry.tsx:1]: It seems there might be a few unrelated changes and refactors included as well. For example, the renderTextWithLinks function was reworked, and the clipboard button was removed.

To keep make it easier to review, would it be possible to scale it back to just the necessary changes for the new feature? Thanks!

**Comment by KatalKavya96** [comment]
@RoyLee1224 Sure i will re apply all changes that are unrelated and removed. Thanks for the review

File: airflow-core/src/airflow/ui/src/pages/XCom/index.ts [hunk 2]
```diff
@@ -18,3 +18,4 @@
  */
 
 export { XCom } from "./XCom";
+export { XComEntry } from "./XComEntry";
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/XCom/index.ts]: Don't think this is necessary

**Review by bbovenzi — APPROVED** [review]

**Review by pierrejeambrun — APPROVED** [review]
Nice thanks

**Comment by KatalKavya96** [comment]
Thanks a lot @bbovenzi , @pierrejeambrun , and @RoyLee1224 for reviewing and giving your time on this PR. Really appreciate the feedback and guidance that helped get this in smoothly.
