### PR TITLE
#55020 gantt view is not getting updatedin realtime

### LINKED ISSUE #55020: Gantt view is not getting updated in realtime
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

When a dag is running for longer time then dag progress bar is not keeping up with the dag duration time.

https://github.com/user-attachments/assets/97ddee9b-3fa6-41f2-86e7-9acae1f79ccc

### What you think should happen instead?

_No response_

### How to reproduce

Use below dag to reproduce the issue:

```python
import datetime

from airflow.providers.standard.operators.bash import BashOperator
from airflow.sdk import DAG

dag = DAG(
    'test_api_dag',
    start_date=datetime.datetime(2025, 7,1),
    schedule='@daily',
    is_paused_upon_creation=False,
    catchup=True,
)

hello_task = BashOperator(
    task_id="sleeeeeep",
    bash_command="sleep 300",
    dag=dag
)

hello_task

``` 

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by yimingpeng**
Hello there,

This PR is an attempt to fix #55020 where the gantt chart wasn't showing real-time progress for running tasks.

closes: #55020 

After applying the fix: 

https://github.com/user-attachments/assets/5a121f1b-f8ab-4395-9c69-929f937d4309

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx [hunk 1]
```diff
@@ -123,6 +124,20 @@ export const Gantt = ({ limit }: Props) => {
 
   const isLoading = runsLoading || structureLoading || summariesLoading || tiLoading;
 
+  useEffect(() => {
```
Comment (guan404ming) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx]: `taskInstancesData` would auto-refresh here so I think it could work without this `useEffect`.
https://github.com/apache/airflow/blob/2b91be8e490714b4fef68a6d89a695caa1003745/airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx#L109-L120

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx [hunk 2]
```diff
@@ -123,6 +124,20 @@ export const Gantt = ({ limit }: Props) => {
...
+    const hasRunningTasks = taskInstancesData?.task_instances.some((ti) => isStatePending(ti.state));
+
+    if (hasRunningTasks) {
+      const interval = setInterval(() => {
+        setCurrentTime(new Date().toISOString());
```
Comment (guan404ming) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx]: We could get current time with `selectedTimezone` easily with `dayjs`

```js
const { selectedTimezone } = useTimezone();

// Make the value timezone-aware
setCurrentTime(dayjs().tz(selectedTimezone).format("YYYY-MM-DD HH:mm:ss"))
```

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts [hunk 3]
```diff
@@ -81,93 +81,98 @@ export const createChartOptions = ({
...
-    duration: 100,
-  },
-  indexAxis: "y" as const,
-  maintainAspectRatio: false,
-  onClick: handleBarClick,
-  onHover: (event: ChartEvent, elements: Array<ActiveElement>) => {
-    const target = event.native?.target as HTMLElement | undefined;
+}: ChartOptionsParams) => {
+  const isRunning = selectedRun?.state === "running";
+  const effectiveEndDate = isRunning ? new Date().toISOString() : selectedRun?.end_date;
```
Comment (guan404ming) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts]: Also here

**Review by guan404ming — COMMENTED** [review]
Thanks for fix, left some comments~

**Comment by yimingpeng** [comment]
Hello @guan404ming,

Thanks for all the great suggestions, I believe I have addressed them, also made a few more changes, e..g, expanding to other pending tasks (`isStatePending`) which was checking `running` only.  Please help review again, thanks.

Here is the expanded test dag from the original issue post: 

```python
from datetime import datetime, timedelta

from airflow import DAG
from airflow.providers.standard.operators.bash import BashOperator
from airflow.providers.standard.operators.python import PythonOperator
from airflow.providers.standard.sensors.filesystem import FileSensor
from airflow.utils.task_group import TaskGroup

def task_that_fails():
    raise Exception("This task always fails for testing")

def task_that_succeeds():
    print("This task succeeds")
    return "success"

dag = DAG(
    'test_gantt_chart_dag',
    start_date=datetime(2025, 7, 1),
    schedule=None,
    is_paused_upon_creation=False,
    catchup=False,
    max_active_runs=1,
    default_args={
        'retries': 2,
        'retry_delay': timedelta(seconds=10),
    }
)

long_running_task = BashOperator(
    task_id="long_running_task",
    bash_command="echo 'Starting long task'; sleep 180; echo 'Long task completed'",
    dag=dag
)

queued_task = BashOperator(
    task_id="queued_task", 
    bash_command="echo 'Queued task executed'; sleep 30",
    dag=dag,
    pool='default_pool',
    pool_slots=10
)

failing_task = PythonOperator(
    task_id="failing_task",
    python_callable=task_that_fails,
    dag=dag
)

waiting_sensor = FileSensor(
    task_id="waiting_sensor",
    filepath="/tmp/nonexistent_file_for_testing.txt",
    timeout=300,
    poke_interval=30,
    dag=dag
)

scheduled_task = BashOperator(
    task_id="scheduled_task",
    bash_command="echo 'Scheduled task executed'; sleep 15",
    dag=dag
)

quick_success_task = PythonOperator(
    task_id="quick_success_task",
    python_callable=task_that_succeeds,
    dag=dag
)

upstream_failed_task = BashOperator(
    task_id="upstream_failed_task",
    bash_command="echo 'This should not run due to upstream failure'",
    dag=dag
)

with TaskGroup("processing_group", dag=dag) as processing_group:
    
    group_start = BashOperator(
        task_id="group_start",
        bash_command="echo 'Group starting'; sleep 5",
        dag=dag,
    )
    
    parallel_task_1 = BashOperator(
        task_id="parallel_task_1", 
        bash_command="echo 'Parallel task 1 running'; sleep 60",
        dag=dag,
    )
    
    parallel_task_2 = PythonOperator(
        task_id="parallel_task_2",
        python_callable=task_that_fails,
        dag=dag,
    )
    
    parallel_task_3 = BashOperator(
        task_id="parallel_task_3",
        bash_command="echo 'Parallel task 3 running'; sleep 45",
        dag=dag,
    )
    
    group_end = BashOperator(
        task_id="group_end",
        bash_command="echo 'Group completed'; sleep 10",
        trigger_rule="none_failed_min_one_success",
        dag=dag,
    )
    
    group_start >> [parallel_task_1, parallel_task_2, parallel_task_3] >> group_end

final_task = BashOperator(
    task_id="final_task",
    bash_command="echo 'All processing completed'",
    dag=dag
)

long_running_task >> scheduled_task
quick_success_task >> queued_task
failing_task >> upstream_failed_task
waiting_sensor >> scheduled_task
processing_group >> final_task
```

Here is the new recording after the fix is applied:

https://github.com/user-attachments/assets/f93615d0-8fba-4842-bebc-f5d580c16730

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx [hunk 4]
```diff
@@ -33,6 +33,9 @@ import {
 import "chart.js/auto";
 import "chartjs-adapter-dayjs-4/dist/chartjs-adapter-dayjs-4.esm";
 import annotationPlugin from "chartjs-plugin-annotation";
+import dayjs from "dayjs";
+import timezone from "dayjs/plugin/timezone";
+import utc from "dayjs/plugin/utc";
```
Comment (guan404ming) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx:38]: Is there any special reason for using this?

Comment (guan404ming) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx]: Is there any special reason for using this?

**Review by guan404ming — APPROVED** [review]
Overall looks good, one nit

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx (hunk 4 above)
Comment (yimingpeng) [reply airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx]: oh, good catch, those imports are redundant, as well as L58-L60 down below. Sorry, not very familiar with `dayjs` so missed that. Fixing it now, thanks for the review!

**Review by guan404ming — APPROVED** [review]
Overall looks good!

cc @bbovenzi @pierrejeambrun 
would appreciate it if you could take another look when you have a moment, thanks!

**Comment by guan404ming** [comment]
@yimingpeng please help rebase and fix the tests, thanks!

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx [hunk 5]
```diff
@@ -127,6 +128,8 @@ export const Gantt = ({ limit }: Props) => {
 
   const isLoading = runsLoading || structureLoading || summariesLoading || tiLoading;
 
+  const currentTime = dayjs().tz(selectedTimezone).format("YYYY-MM-DD HH:mm:ss");
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx]: Let's use the `defaultFormatWithTZ` var

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx [hunk 6]
```diff
@@ -157,14 +160,17 @@ export const Gantt = ({ limit }: Props) => {
...
+
             return {
               isGroup: node.isGroup,
               isMapped: node.is_mapped,
               state: taskInstance.state,
               taskId: taskInstance.task_id,
               x: [
                 formatDate(taskInstance.start_date, selectedTimezone, "YYYY-MM-DD HH:mm:ss.SSS"),
-                formatDate(taskInstance.end_date, selectedTimezone, "YYYY-MM-DD HH:mm:ss.SSS"),
+                formatDate(endTime, selectedTimezone, "YYYY-MM-DD HH:mm:ss.SSS"),
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx]:
```suggestion
                formatDate(endTime, selectedTimezone, defaultFormatWithTZ),
```

**Comment by yimingpeng** [comment]
hello @bbovenzi, thanks for the code review, I guess you meant `DEFAULT_DATETIME_FORMAT_WITH_TZ `? Can you have another review pls? if I misunderstood anything here, please correct me, thanks

**Review by bbovenzi — APPROVED** [review]
