### PR TITLE
UI: Fix log line number gaps caused by group markers

### LINKED ISSUE #47888: Some irregularities on the web UI logs tab
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

Small feedback for the UI folks here, the UI logs tab is slightly weird when it comes to viewing logs.
- The line number alignment is off for cases when logs lines are long, wrapped or unwrapped
- Line number "1" is missing? (or hidden)
- And on expanding the "Log message source details sources" dropdown, there's a line number "0", "2"....(no "1")

Image
Image
Image

### What you think should happen instead?

- Line number alignment shouldn't be this way
- Fix line numbering (on and off expanding the dropdown)

### How to reproduce

- Run `breeze start-airflow`
- Run a dag and go to dags view
- I opened it on Chrome incognito but shoudlnt matter

### Operating System

NA

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by dandanseo123**
### Description
Group markers (`::group::` / `::endgroup::`) consumed line number indices but were removed during group processing, leaving gaps in the displayed line numbers (e.g. 0, 2, 3 instead of 0, 1, 2). Also fixed line number alignment on wrapped log lines.

- Pre-scan log data to assign sequential display line numbers that skip group markers
- Pin wrapped line numbers to the top with `alignItems: flex-start`
 
closes: https://github.com/apache/airflow/issues/47888

### Screenshot
Screenshot 2026-04-10 at 8 37 50 PM

  ---

  ##### Was generative AI tooling used to co-author this PR?

  - [X] Yes — Claude Code

  Generated-by: Claude Code following [the guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#gen-ai-assisted-contributions)

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/queries/useLogs.tsx [hunk 1]
```diff
@@ -75,6 +75,20 @@ const parseLogs = ({
   const logLink = taskInstance ? `${getTaskInstanceLink(taskInstance)}?try_number=${tryNumber}` : "";
 
   try {
+    let lineNumber = 0;
+    const lineNumbers = data.map((datum, dataIndex) => {
+      const text = typeof datum === "string" ? datum : datum.event;
+
+      if (text.includes("::group::") || text.includes("::endgroup::")) {
+        return dataIndex;
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/queries/useLogs.tsx]: We can just return undefined here

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/Logs.test.tsx [hunk 2]
```diff
@@ -133,4 +133,38 @@ describe("Task log grouping", () => {
...
+    fireEvent.click(summaryPre);
+    await waitFor(() => expect(screen.getByText(/starting attempt 1 of 3/iu)).toBeVisible());
+
+    const summaryPost = screen.getByTestId("summary-Post task execution logs");
+
+    fireEvent.click(summaryPost);
+    await waitFor(() => expect(screen.queryByText(/Marking task as SUCCESS/iu)).toBeVisible());
+
+    // Collect all rendered line number links
+    const lineNumbers = [...document.querySelectorAll<HTMLAnchorElement>("a[id]")]
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/Logs.test.tsx]: This is looking across the whole document. Let's look only inside the Log Code component

**Review by bbovenzi — APPROVED** [review]
Nice work. Just two nits.

File: airflow-core/src/airflow/ui/src/queries/useLogs.tsx (hunk 1 above)
Comment (dandanseo123) [reply airflow-core/src/airflow/ui/src/queries/useLogs.tsx]: done

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/Logs.test.tsx (hunk 2 above)
Comment (dandanseo123) [reply airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/Logs.test.tsx]: done

**Comment by dandanseo123** [comment]
@bbovenzi addressed PR comments!

**Comment by bbovenzi** [comment]
Thanks! Looks like we just need to fix one react test

**Comment by dandanseo123** [comment]
@bbovenzi fixed
