### PR TITLE
Fix missing translation keys for blocking dependencies in UI (#61314)

### LINKED ISSUE #61314: Task Scheduling Blocking Depdendency Reason missing translation keys
### Apache Airflow version

Other Airflow 3 version (please specify below)

### If "Other Airflow 3 version" selected, which one?

3.1.7rc1

### What happened?

Running a Dag an checking for reasons why tasks are not scheduling, translations keys in UI seem to be missing in 3.1.7rc1 (at least, maybe also in previous versions)

- dag.blockingDeps.title
- dag.blockingDeps.dependency
- dag.blockingDeps.reason

Image

### What you think should happen instead?

UI should be fully translated.

### How to reproduce

Start Airflow 3.1.7 (rc1) and start a Dag run. Go to a taks that is not (yet) scheduled and click on the "Details" panel. See that translation keys for the headings are missing in the details panel.

### Operating System

Ubuntu 24.04

### Versions of Apache Airflow Providers

unrelevant

### Deployment

Other

### Deployment details

`breeze start-airflow --load-example-dags --use-airflow-version 3.1.7rc1`

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by SakshamSinghal20**
This PR resolves an issue where translation keys for "Blocking Dependencies" in the Task Instance Details panel were missing (e.g., `dag.blockingDeps.title`, `dag.blockingDeps.dependency`), displaying raw keys instead of the localized text.

The `dag` and `tasks` translation files existed in the locales directory but were not registered in the i18n configuration ([config.ts](cci:7://file:///c:/Users/Saksham%20Singhal/OneDrive/Desktop/Airflowww/airflow/airflow-core/src/airflow/ui/src/i18n/config.ts:0:0-0:0)), preventing them from being loaded. This change adds both namespaces to the configuration to ensure the translations are applied correctly.

closes: #61314

---

##### Was generative AI tooling used to co-author this PR?
No

### CODE REVIEW

**Review by RoyLee1224 — COMMENTED** [review]
Thanks for the PR! However, I think the current changes do not seem to address the root cause.

The issue is that the `BlockingDeps` component needs to load the `dag` namespace to access the keys in `airflow-core/src/airflow/ui/public/i18n/locales/en/dag.json`.

To fix this, please revert the changes in this PR and instead modify `BlockingDeps.tsx` as follows:

1. Update the hook to load the namespace:
```
const { t: translate } = useTranslation("dag");
```
2. Remove the `dag.` prefix from the keys (since we are already in the dag namespace):
```
// Change this:
{translate("dag.blockingDeps.title")}
// To this:
{translate("blockingDeps.title")}
```
(Please apply this pattern to `dependency` and `reason` headers as well.)

**Comment by SakshamSinghal20** [comment]
Thank you so much for letting me know I will fix this ASAP.

**Comment by SakshamSinghal20** [comment]
@RoyLee1224 I hope The following commit will solve this issue

File: airflow-core/src/airflow/ui/src/components/Clear/TaskInstance/ClearTaskInstanceDialog.tsx [hunk 1]
```diff
@@ -63,7 +63,7 @@ const ClearTaskInstanceDialog = ({ onClose: onCloseDialog, open: openDialog, tas
   const upstream = selectedOptions.includes("upstream");
   const downstream = selectedOptions.includes("downstream");
   const [runOnLatestVersion, setRunOnLatestVersion] = useState(false);
-  const [preventRunningTask, setPreventRunningTask] = useState(true);
+  const [preventRunningTask, setPreventRunningTask] = useState(false);
```
Comment (RoyLee1224) [inline airflow-core/src/airflow/ui/src/components/Clear/TaskInstance/ClearTaskInstanceDialog.tsx]: Do we need to modify this?

Comment (SakshamSinghal20) [reply airflow-core/src/airflow/ui/src/components/Clear/TaskInstance/ClearTaskInstanceDialog.tsx]: Yes — this change is intentional.

The previous default (true) caused the dialog to assume task prevention even when the option wasn’t selected, which led to inconsistent UI state and incorrect dependency handling.
Initializing it to false aligns with the actual default behavior and ensures the UI reflects user-selected options correctly.

Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/components/Clear/TaskInstance/ClearTaskInstanceDialog.tsx]: - Line 66: State initialized to true                                                                                      
- Line 186: Checkbox renders checked={preventRunningTask} → checkbox starts checked    
- Line 231: API sends { prevent_running_task: true } only when state is truthy                                            
                                                                                         
All three are in sync. State is true → checkbox shows checked → API sends the flag. I think there is no inconsistency, could you please help confirm this? Feel free to correct me if I'm wrong. Thanks!

**Review by guan404ming — COMMENTED** [review]
One question left, otherwise looks good.

File: airflow-core/src/airflow/ui/src/components/Clear/TaskInstance/ClearTaskInstanceDialog.tsx (hunk 1 above)
Comment (SakshamSinghal20) [reply airflow-core/src/airflow/ui/src/components/Clear/TaskInstance/ClearTaskInstanceDialog.tsx]: You’re right that the state, checkbox, and API were in sync technically. My intention with this change is to align the default with the desired behavior (opt‑in prevention), so users aren’t opted in without interacting with the checkbox.

Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/components/Clear/TaskInstance/ClearTaskInstanceDialog.tsx]: This change still seems unrelated to the i18n fix. Changing the default value of preventRunningTask from true to false alters the behavior of the Clear Task Instance dialog, which is outside the scope of this PR. I'd suggest either reverting this line or splitting it into a separate PR with an explanation for why the default should change.

Comment (SakshamSinghal20) [reply airflow-core/src/airflow/ui/src/components/Clear/TaskInstance/ClearTaskInstanceDialog.tsx]: okay then i will change this line back.

**Comment by SakshamSinghal20** [comment]
@guan404ming I have change its state to true and i hope this solves the current issue.
Thanks,

File: airflow-core/src/airflow/ui/src/i18n/config.ts
Comment (guan404ming) [inline airflow-core/src/airflow/ui/src/i18n/config.ts:1]: Do we need this change?

Comment (SakshamSinghal20) [reply airflow-core/src/airflow/ui/src/i18n/config.ts:1]: I mean no its the same thing i just changed the line.

Comment (guan404ming) [reply airflow-core/src/airflow/ui/src/i18n/config.ts:1]: Let's revert this change.

Comment (SakshamSinghal20) [reply airflow-core/src/airflow/ui/src/i18n/config.ts:1]: sure

**Review by guan404ming — APPROVED** [review]

**Comment by guan404ming** [comment]
Thanks!
