### PR TITLE
Fix regression in security iframe navigation logic with basename

### LINKED ISSUE #63111: Regression in security iframe navigation logic (ignores basename)
### Apache Airflow version

3.1.7

### If "Other Airflow 3 version" selected, which one?

_No response_

### What happened?

A regression was introduced in PR #58997 regarding how the security iframe handles redirection. The current logic checks for a hardcoded pathname starting with /auth/, which fails when Airflow is configured with a non-root base_url (e.g., when hosted at /airflow/).

https://github.com/apache/airflow/blob/d38400997bcef9570246abae3e3ba80983c9d11a/airflow-core/src/airflow/ui/src/pages/Security.tsx#L43-L49

### What you think should happen instead?

_No response_

### How to reproduce

1. Configure Airflow to run behind a prefix (e.g., AIRFLOW__API__BASE_URL=/airflow).
2. Access the UI and navigate to security tabs.
3. The onLoad handler in the security iframe triggers.
4. iframe.contentWindow.location.pathname returns /airflow/auth/....
5. The check .startsWith("/auth/") returns false.
6. The router incorrectly calls navigate("/"), redirecting the user to the root instead of the dashboard.

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Subham-KRLX**
Fixes a regression where the security iframe ignores the configured `AIRFLOW__API__BASE_URL` (basename), causing valid navigation within the iframe to incorrectly redirect users to the root dashboard. 

The fix updates [Security.tsx](cci:7://file:///Users/subhamsangwan/airflow/airflow-core/src/airflow/ui/src/pages/Security.tsx:0:0-0:0) to read the `<base>` tag's `href` (the same approach used by [router.tsx](cci:7://file:///Users/subhamsangwan/airflow/airflow-core/src/airflow/ui/src/router.tsx:0:0-0:0)) and safely strips the basename from the iframe's pathname before checking if it starts with `/auth/`.

closes: #63111

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/pages/Security.tsx [hunk 1]
```diff
@@ -43,8 +43,18 @@ export const Security = () => {
   const onLoad = () => {
     const iframe: HTMLIFrameElement | null = document.querySelector("#security-iframe");
 
-    if (iframe?.contentWindow && !iframe.contentWindow.location.pathname.startsWith("/auth/")) {
-      void Promise.resolve(navigate("/"));
+    if (iframe?.contentWindow) {
+      const baseUrl = document.querySelector("base")?.href ?? "http://localhost:8080/";
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/Security.tsx]: We shouldn't hardcode `localhost:8080` here.

Comment (Subham-KRLX) [reply airflow-core/src/airflow/ui/src/pages/Security.tsx]: Removed the hardcoded localhost:8080 fallback. Now when no <base> tag is found, [basename](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) defaults to "" (empty string), so the path is checked as-is. Also added a newsfragment.

File: airflow-core/src/airflow/ui/src/pages/Security.tsx [hunk 2]
```diff
@@ -43,8 +43,18 @@ export const Security = () => {
   const onLoad = () => {
     const iframe: HTMLIFrameElement | null = document.querySelector("#security-iframe");
 
-    if (iframe?.contentWindow && !iframe.contentWindow.location.pathname.startsWith("/auth/")) {
-      void Promise.resolve(navigate("/"));
+    if (iframe?.contentWindow) {
+      const baseHref = document.querySelector("base")?.href;
+      const basename = baseHref === undefined ? "" : new URL(baseHref).pathname.replace(/\/$/u, "");
```
Comment (JC-comp) [inline airflow-core/src/airflow/ui/src/pages/Security.tsx]: Since we're already within a routing context, we can avoid manual DOM scraping of the `<base>` tag. Using [`useHref`](https://reactrouter.com/api/hooks/useHref) to resolve `/auth` automatically respects the `basename` configured in the Router provider. This makes the logic cleaner and removes the need to manually slice or parse the `iframePath`.
```js
const authPath = useHref("/auth");
...
const onLoad = () => {
  if (!iframePath.startsWith(authPath)) {
  ...
  }
```

**Review by JC-comp — CHANGES_REQUESTED** [review]

File: airflow-core/newsfragments/63141.bugfix.rst [hunk 3]
```diff
@@ -0,0 +1 @@
+Fix security iframe navigation when AIRFLOW__API__BASE_URL basename is configured
```
Comment (pierrejeambrun) [inline airflow-core/newsfragments/63141.bugfix.rst:1]: We do not use newsframgnets for bugfixes. Only for 'significant' ones. 

Can you remove this file please.

File: airflow-core/src/airflow/ui/src/pages/Security.tsx [hunk 4]
```diff
@@ -43,8 +43,18 @@ export const Security = () => {
...
+
+      const iframePath = iframe.contentWindow.location.pathname;
+      const pathWithoutBase = iframePath.startsWith(basename)
+        ? iframePath.slice(basename.length)
+        : iframePath;
+
+      if (!pathWithoutBase.startsWith("/auth/")) {
+        void Promise.resolve(navigate("/"));
+      }
     }
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/Security.tsx:51]: This is overly complicated I believe:
```suggestion
    if (iframe?.contentWindow) {
      const base = new URL(document.baseURI).pathname.replace(/\/$/u, ""); // Remove trailing slash if exists

      if (!iframe.contentWindow.location.pathname.startsWith(`${base}/auth/`)) {
        void Promise.resolve(navigate("/"));
      }
    }
  };

```

**Review by pierrejeambrun — COMMENTED** [review]
Thanks for catching this. I believe it can be simplified. Tested and working as expected.

**Review by bbovenzi — APPROVED** [review]

**Review by pierrejeambrun — APPROVED** [review]
