### PR TITLE
fix(AssetSchedule): fix how asset_expression is accessed

### LINKED ISSUE #49197: Dags page error "Cannot read properties of undefined (reading '0')" when running two @assets that depend on each other
### Apache Airflow version

3.0.0

### If "Other Airflow 2 version" selected, which one?

v3-0-test

### What happened?

When running two assets that depend on each other the Dags page displays an error. The dags run correctly, but the overview page does not load anymore.

```
from airflow.sdk import asset

@asset(schedule="@daily") 
def test_asset(): 
    pass


@asset(schedule=test_asset)
def test_asset_2():
    pass

```

Image

Movie version:

https://github.com/user-attachments/assets/36007147-9c66-42e6-9a10-89ccb414b86d

### What you think should happen instead?

_No response_

### How to reproduce

1. Add the two assets above.
2. Unpause both assets
3. Run the upstream asset
4. See the error when trying to load the Dags page

### Operating System

MacOs

### Versions of Apache Airflow Providers

breeze versions

### Deployment

Other

### Deployment details

breeze

### Anything else?

This does **not** happen with the following dags:

```
from airflow.sdk import Asset, dag, task


@dag
def upstream():
    @task(outlets=[Asset("my_asset")])
    def my_task():
        pass

    my_task()


upstream()


@dag(
    schedule=[Asset("my_asset")],
)
def downstream():
    @task
    def my_task2():
        pass

    my_task2()


downstream()
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Lee-W**
## Why
asset_expression was wrongly accessed in AssetSchedule

close: #49197 

## What
Fix how `asset_expression` is accessed

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]
Looks good to me, need to fix type checks.

File: airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ export const AssetSchedule = ({ dag }: Props) => {
         <Button loading={isLoading} paddingInline={0} size="sm" variant="ghost">
           <FiDatabase style={{ display: "inline" }} />
           {nextRunEvents.length === 1 ? (
-            ((nextRun?.asset_expression as { all: Array<AssetResponse> }).all[0]?.name ??
+            ((nextRun?.asset_expression as { expr: AssetResponse | undefined }).expr?.name ??
```
Comment (tirkarthi) [inline airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx:56]: AFAIK `as` does only type checking and this won't cause the `nextRun?.asset_expression` to become `{"expr": nextRun?.asset_expression}` for `.expr` attribute access, thus causing this to always print uri. Earlier only `all` was expected and handled. Now it needs to handle `all`, `any` and `asset` of below structures.

```js
{
  "asset": {
    "uri": "s3://test_asset/",
    "name": "test_asset",
    "group": "asset",
    "id": 184
  }
}
```

```js
{
  "all": [
    {
      "asset": {
        "uri": "s3://test_asset/",
        "name": "test_asset",
        "group": "asset",
        "id": 184
      }
    }
  ]
}
```

```js
{
  "any": [
    {
      "asset": {
        "uri": "s3://test_asset/",
        "name": "test_asset",
        "group": "asset",
        "id": 184
      }
    },
    {
      "asset": {
        "uri": "s3://test_asset/",
        "name": "test_asset",
        "group": "asset",
        "id": 184
      }
    }
  ]
}
```

Sample dag : 

```python
from airflow.sdk import asset

@asset(schedule="@daily", uri="s3://test_asset")
def test_asset():
    pass

@asset(schedule=test_asset)
def test_asset_single():
    pass

@asset(schedule=[test_asset])
def test_asset_and():
    pass

@asset(schedule=test_asset | test_asset)
def test_asset_or():
    pass

```

https://stackoverflow.com/questions/55781559/what-does-the-as-keyword-do

Comment (tirkarthi) [reply airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx:56]: Something along the lines of below

```diff
diff --git a/airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx b/airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx
index 749017b257..854ca8cdb6 100644
--- a/airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx
+++ b/airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx
@@ -53,7 +53,11 @@ export const AssetSchedule = ({ dag }: Props) => {
         <Button loading={isLoading} paddingInline={0} size="sm" variant="ghost">
           <FiDatabase style={{ display: "inline" }} />
           {nextRunEvents.length === 1 ? (
-            ((nextRun?.asset_expression as { all: Array<AssetResponse> }).all[0]?.name ??
+            ((nextRun?.asset_expression as { all: Array<{ asset: AssetResponse }> | undefined }).all?.at(0)
+              ?.asset.name ??
+            (nextRun?.asset_expression as { any: Array<{ asset: AssetResponse }> | undefined }).any?.at(0)
+              ?.asset.name ??
+            (nextRun?.asset_expression as { asset: AssetResponse | undefined }).asset?.name ??
             nextRunEvents[0]?.uri)
```

Comment (Lee-W) [reply airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx:56]: Unfortunately, I'm not that familiar with how typescript handles it. I'll merge it as a temp solution to avoid breaking the dag page, but I might need some help from @pierrejeambrun or @bbovenzi. Thanks!

Comment (Lee-W) [reply airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx:56]: Just noticed the comment. Thanks @tirkarthi . tested it locally and sent a PR

Comment (Lee-W) [reply airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx:56]: https://github.com/apache/airflow/pull/49225

Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx:56]: Sorry, just going through all my notifications now. I think this PR should simplify this a good deal: https://github.com/apache/airflow/pull/49137
