### PR TITLE
fix(DagCalendarTab): improve background color retrieval and loading overlay handling

### LINKED ISSUE #63409: E2E: Improve Playwright test patterns in dag-calendar-tab.spec.ts
### Description

Improve Playwright test patterns in dag-calendar-tab.spec.ts and related page object to align with Playwright Best Practices.

This PR focuses on improving test patterns only.
It does not change test coverage or behavior.

### Checklist
- [ ] page.waitForFunction() with DOM queries → locator-based waiting
- [ ] page.waitForTimeout() → state-based waiting
- [ ] waitForLoadState("networkidle") → wait for specific UI state
- [ ] Manual assertions → web-first assertions
- [ ] page.evaluate() for DOM manipulation → observe UI state instead
- [ ] CSS :has-text() → user-facing locators
- [ ] flaky check

### Scope
This issue covers improvements in:
- specs/dag-calendar-tab.spec.ts
- pages/DagCalendarTab.ts

### Use case/motivation

_No response_

### Related issues

Part of #63036

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by MFWhen**
Refactor Playwright page object for the DAG Calendar Tab to use getComputedStyle and web-first assertions

 

---

##### Was generative AI tooling used to co-author this PR?

- [x] Yes (please specify the tool below)

Generated-by: Github Copilot following [the guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#gen-ai-assisted-contributions)

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments). You can add this file in a follow-up commit after the PR is created so you know the PR number.

### CODE REVIEW

File: airflow-core/src/airflow/ui/tests/e2e/pages/DagCalendarTab.ts [hunk 1]
```diff
@@ -115,16 +128,16 @@ export class DagCalendarTab extends BasePage {
 
     const overlay = this.page.getByTestId("calendar-loading-overlay");
 
-    if (await overlay.isVisible().catch(() => false)) {
-      await overlay.waitFor({ state: "hidden", timeout: 120_000 });
+    try {
+      await overlay.waitFor({ state: "hidden", timeout: 10_000 });
```
Comment (choo121600) [inline airflow-core/src/airflow/ui/tests/e2e/pages/DagCalendarTab.ts]: Would it make sense to switch these to `expect().toBeVisible()` instead of `waitFor()`?
This could make the test more explicit and rely on Playwright’s built-in retry + assertion behavior.

File: airflow-core/src/airflow/ui/tests/e2e/pages/DagCalendarTab.ts [hunk 2]
```diff
@@ -115,16 +128,16 @@ export class DagCalendarTab extends BasePage {
...
 
     await this.page.getByTestId("calendar-grid").waitFor({ state: "visible", timeout: 120_000 });
 
-    await this.page.waitForFunction(() => {
-      const cells = document.querySelectorAll('[data-testid="calendar-cell"]');
+    const cells = this.page.getByTestId("calendar-cell");
 
-      return cells.length > 0;
-    });
+    await cells.first().waitFor({ state: "attached", timeout: 120_000 });
```
Comment (choo121600) [inline airflow-core/src/airflow/ui/tests/e2e/pages/DagCalendarTab.ts]: this too :)

File: airflow-core/src/airflow/ui/tests/e2e/pages/DagCalendarTab.ts (hunk 1 above)
Comment (MFWhen) [reply airflow-core/src/airflow/ui/tests/e2e/pages/DagCalendarTab.ts]: alright ill try

File: airflow-core/src/airflow/ui/tests/e2e/pages/DagCalendarTab.ts (hunk 2 above)
Comment (MFWhen) [reply airflow-core/src/airflow/ui/tests/e2e/pages/DagCalendarTab.ts]: alright made those changes. please check them.

**Comment by potiuk** [comment]
@MFWhen This PR has been converted to **draft** because it does not yet meet our [Pull Request quality criteria](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-quality-criteria).

**Issues found:**
- :x: **Meaningful description**: The PR body contains no meaningful description of what the bug is, what the root cause is, or why these specific code changes fix it. The body is entirely the unfilled PR template — only the Gen-AI checkbox was touched; the actual description area above the '---' separator is completely blank.
- :x: **Unresolved merge conflict markers**: The file airflow-core/src/airflow/ui/tests/e2e/pages/DagCalendarTab.ts contains unresolved Git merge conflict markers (<<<<<<< HEAD, =======, >>>>>>> 4bce21a34c62fcdb5b920d6c7535a6f9684cf079) inside the navigateToCalendar method. The file is broken and cannot be compiled or run as submitted.
- :x: **Gen-AI disclosure**: The author checked the Gen-AI box but left the tool name as the template placeholder '(please specify the tool below)' without naming the actual tool. The 'Generated-by' line is still commented out with '[Tool Name]' unfilled. The disclosure is incomplete per project guidelines.
- :warning: **Coherent changes**: dev/update_github_branch_config.py is included with a file-mode change (100755 → 100644) that is completely unrelated to any DagCalendarTab fix. Unrelated changes should be removed before submitting for review.

**What to do next:**
- The comment informs you what you need to do.
- Fix each issue, then mark the PR as "Ready for review" in the GitHub UI - but only after making sure that all the issues are fixed.
- There is no rush — take your time and work at your own pace. We appreciate your contribution and are happy to wait for updates.
- Maintainers will then proceed with a normal review.

Converting a PR to draft is **not** a rejection — it is an invitation to bring the PR up to the project's standards so that maintainer review time is spent productively. There is no rush — take your time and work at your own pace. We appreciate your contribution and are happy to wait for updates. If you have questions, feel free to ask on the [Airflow Slack](https://s.apache.org/airflow-slack).

---

_Note: This comment was drafted by an AI-assisted triage tool and may contain mistakes. Once you have addressed the points above, an Apache Airflow maintainer — a real person — will take the next look at your PR. We use this [two-stage triage process](https://github.com/apache/airflow/blob/main/contributing-docs/25_maintainer_pr_triage.md#why-the-first-pass-is-automated) so that our maintainers' limited time is spent where it matters most: the conversation with you._

File: dev/update_github_branch_config.py
Comment (bbovenzi) [inline dev/update_github_branch_config.py:1]: This change is unrelated. Please undo

**Review by bbovenzi — CHANGES_REQUESTED** [review]
One comment

File: dev/update_github_branch_config.py
Comment (MFWhen) [reply dev/update_github_branch_config.py:1]: undo what?

Comment (bbovenzi) [reply dev/update_github_branch_config.py:1]: The file mode was changed. Please run
```git update-index --chmod=+x dev/update_github_branch_config.py```
The commits on this pull request should only show one file changed.

Comment (MFWhen) [reply dev/update_github_branch_config.py:1]: is it all good now?

Comment (bbovenzi) [reply dev/update_github_branch_config.py:1]: Yes. thanks!

**Review by bbovenzi — APPROVED** [review]

**Comment by vatsrahul1001** [comment]
Manual backport PR https://github.com/apache/airflow/pull/66860 up for review @choo121600 @bbovenzi
