### PR TITLE
UI: Fix note modal does not change markdown text after change

### LINKED ISSUE #56078: Note modal does not change markdown text after change
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

3.1.0rc2

### What happened?

When creating or changing a task instance note in the popup-modal, after exiting the editor the preview of markdown text is not updated. The markdown is always showing the previous text (when entering the modal). 

See screen recording:

https://github.com/user-attachments/assets/f3a75644-3980-4119-863d-70db5d2bcf9b

Nevertheless when saving it is OK.

Same problem on Dag run notes

### What you think should happen instead?

- Note text should be updated in Markdown after editing as preview
- Layout nit: The markdown preview and editor should have the same size such that the modal is not flipping size

### How to reproduce

Run web UI on 3.1.0rc2 - make the same steps liek in screen recording

### Operating System

Linux with Firefox

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

Breeze

### Anything else?

I assume this is a small nit and not critical blocking rc2. But if there are other bugs fould would be cool to add a fix for this in 3.1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by yangyulely**
closes: #56078 
related: #56078 

## Root Cause
The note editable component was using the prop value (`mdContent`) directly for both the editor and preview. When users made changes and exited the editor, the preview continued to show the initial prop value instead of the current edited content.

## Solution
Added a local state variable `currentValue` to track the current content being edited, and updated the preview to use this local state instead of the prop directly. This ensures the preview shows the current content when the user exits the editor.

## Result

- The preview now correctly updates for both task instance notes and DAG run notes when users exit the modal editor.
- Both the preview and editor have the same size

note-review

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/components/EditableMarkdownArea.tsx [hunk 1]
```diff
@@ -31,36 +32,51 @@ const EditableMarkdownArea = ({
...
-        gap="0"
-        overflowY="auto"
-        width="100%"
+}) => {
+  const [currentValue, setCurrentValue] = useState(mdContent ?? "");
+
+  // Sync local state with prop changes
+  useEffect(() => {
+    setCurrentValue(mdContent ?? "");
+  }, [mdContent]);
```
Comment (jscheffl) [inline airflow-core/src/airflow/ui/src/components/EditableMarkdownArea.tsx]: useEffect should only be used where needed. Can you please make a solution without?

Comment (yangyulely) [reply airflow-core/src/airflow/ui/src/components/EditableMarkdownArea.tsx]: Thanks for the review! maybe useRef is better! I've replace useEffect by it.

**Review by jscheffl — APPROVED** [review]
Thanks for the fix!
