### PR TITLE
Fix details tab not showing when using dynamic task mapping

### LINKED ISSUE #36481: Empty Details tab after upgrading to Airflow 2.8.0 (Dynamic Task Mapping)
### Apache Airflow version

2.8.0

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

After upgrading to Airflow 2.8.0, I've found out that the `Details` tab is empty for mapped tasks
image

### What you think should happen instead?

Details tab should appear, just like before

### How to reproduce

1. Run the following DAG
  ```python
    with DAG(
        dag_id="test_mapped_tasks_ui",
        schedule=None,
        catchup=False,
        max_active_runs=1,
        render_template_as_native_obj=True,
    ) as dag:
    
        @task
        def my_task(idx: int) -> None:
            print(f"Task {idx} done")
    
        my_task.expand(idx=list(range(1, 10)))

  ```
2. Open the `Details` tab of `my_task`

### Operating System

Airflow in Kubernetes

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by shohamy7**
---

closes: #36481
This PR solves the problem of details tab is empty in the Airflow Web UI when using dynamic task mapping.

### CODE REVIEW

File: airflow/www/static/js/dag/details/index.tsx [hunk 1]
```diff
@@ -301,7 +302,7 @@ const Details = ({
           <TabPanel height="100%">
             {isDag && <DagContent />}
             {isDagRun && <DagRunContent runId={runId} />}
-            {isTaskInstance && (
+            {shouldShowDetailsTab && (
```
Comment (bbovenzi) [inline airflow/www/static/js/dag/details/index.tsx]:
```suggestion
            {!!runId && !!taskId && (
```
Let's just do it in a single line since we don't use the variable anywhere else.

Comment (shohamy7) [reply airflow/www/static/js/dag/details/index.tsx]: resolved :)

**Review by bbovenzi — APPROVED** [review]
