### PR TITLE
Fix Mark Instance state buttons stay disabled if user lacks permission (#37451)

### LINKED ISSUE #37451: Marking task state as Failed or Success without taskinstance edit role is resulting into partial empty screen
### Apache Airflow version

2.8.1

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

Marking task state as Failed or Success without task instance edit role is resulting into partial empty screen as shown below instead of Access Denied message. 

### What you think should happen instead?

We should show proper messaging saying user is lacking permission. 

### How to reproduce

1. Create new user and assign user with can edit dags, can read dag runs, can edit dag runs permissions.
2. Try to login with user and click on the specific Dag. 
3. Select task and try to mark it as Failed or Success. 

### Operating System

mac os

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by RodrigoGanancia**
closes: #37451

This bug adresses a visual issue occuring when attempting to mark task states as Failed or Sucess, or when using clear button without the 'can edit on Task Instances' role. This resulted in a not expected partially empty screen in the dag menu.

The fix resolves the issue by disabling both the "Clear Task" and "Mark state as…" buttons when the user lacks permission, same as the behavior when the user can't edit on DAGs.

Now, in 'views.py', an additional meta named 'can_edit_taskintances' is passed to 'grid.html' based on the user's task instance edit permission, same as the meta 'can_edit' from user's dag edit permission defined in 'dag.html'.

Both 'canEdit' and 'canEditTaskInstances' definitions were moved inside the React components. This was necessary just for the variables to be mockable during testing, as these variables were defined before the component was loaded.

### CODE REVIEW

File: airflow/www/static/js/dag/details/taskInstance/taskActions/ClearInstance.tsx [hunk 1]
```diff
@@ -242,21 +243,23 @@ const ClearInstance = ({
   useKeysPress(keyboardShortcutIdentifier.taskRunClear, onOpen);
 
   const clearLabel = "Clear and retry task.";
+  const canEdit = getMetaValue("can_edit") === "True";
```
Comment (bbovenzi) [inline airflow/www/static/js/dag/details/taskInstance/taskActions/ClearInstance.tsx]: `canEdit` is specified twice. Let's delete one

Comment (RodrigoGanancia) [reply airflow/www/static/js/dag/details/taskInstance/taskActions/ClearInstance.tsx]: Ok seems right

Comment (RodrigoGanancia) [reply airflow/www/static/js/dag/details/taskInstance/taskActions/ClearInstance.tsx]: Coming back to this, after some rethinking canEdit and canEditTaskInstance should just be declared once at the start of the file. This changes were only made for being able to create tests, which I find them not that necessary since these changes are so small. Should I remove the tests files and move the declarations to the top of the file? What do you think?

**Comment by RodrigoGanancia** [comment]
Hey, the code is now ready, since the fix is pretty simple I removed the test case which was not needed. I'm sorry for the latest commit, It's my first time contributing and I messed up the rebase. I have already fixed it having now only one commit.

**Review by bbovenzi — APPROVED** [review]
