### PR TITLE
fix: xcom_push raises 422 error when value is set to None 

### LINKED ISSUE #55062: xcom_push raises 422 error when value is set to None
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

having `context["ti"].xcom_push(key="number_of_people_in_space", value=None)` in a task will fail with below error. I tested the same in AF2 and it works without issues. 

```
[2025-08-29, 15:46:18] ERROR - Task failed with exception: source="task"
AirflowRuntimeError: API_SERVER_ERROR: {'status_code': 422, 'message': 'Remote server returned validation error', 'detail': {'detail': [{'type': 'missing', 'loc': ['body'], 'msg': 'Field required', 'input': None}]}}

File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/task_runner.py", line 920 in run

File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/task_runner.py", line 1302 in _execute_task

File "/opt/airflow/task-sdk/src/airflow/sdk/bases/operator.py", line 414 in wrapper

File "/opt/airflow/task-sdk/src/airflow/sdk/bases/decorator.py", line 252 in execute

File "/opt/airflow/task-sdk/src/airflow/sdk/bases/operator.py", line 414 in wrapper

File "/opt/airflow/providers/standard/src/airflow/providers/standard/operators/python.py", line 216 in execute

File "/opt/airflow/providers/standard/src/airflow/providers/standard/operators/python.py", line 239 in execute_callable

File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/callback_runner.py", line 82 in run

File "/files/dags/aa.py", line 75 in get_astronauts

File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/task_runner.py", line 414 in xcom_push

File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/task_runner.py", line 561 in _xcom_push

File "/opt/airflow/task-sdk/src/airflow/sdk/bases/xcom.py", line 86 in set

File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/comms.py", line 207 in send

File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/comms.py", line 271 in _get_response

File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/comms.py", line 258 in _from_frame
```

### What you think should happen instead?

It should created an XCOM with the given key and value set to None

### How to reproduce

```

from airflow.sdk.definitions.asset import Asset
from airflow.decorators import dag, task
from pendulum import datetime
import requests


# Define the basic parameters of the DAG, like schedule and start_date
@dag(
    start_date=datetime(2024, 1, 1),
    schedule="@daily",
    catchup=False,
    doc_md=__doc__,
    default_args={"owner": "Astro", "retries": 3},
    tags=["example"],
)
def example_astronauts():
    # Define tasks
    @task(
        # Define a dataset outlet for the task. This can be used to schedule downstream DAGs when this task has run.
        outlets=[Asset("current_astronauts")]
    )  # Define that this task updates the `current_astronauts` Dataset
    def get_astronauts(**context) -> list[dict]:
        context["ti"].xcom_push(
            key="number_of_people_in_space", value=None
        )
        return [{"craft": "ISS", "name": "Oleg Kononenko"},]

    @task
    def print_astronaut_craft(greeting: str, person_in_space: dict) -> None:

        craft = person_in_space["craft"]
        name = person_in_space["name"]

        print(f"{name} is currently in space flying on the {craft}! {greeting}")

    # Use dynamic task mapping to run the print_astronaut_craft task for each
    # Astronaut in space
    print_astronaut_craft.partial(greeting="Hello! :)").expand(
        person_in_space=get_astronauts()  # Define dependencies using TaskFlow API syntax
    )


# Instantiate the DAG
example_astronauts()

```

### Operating System

macos

### Versions of Apache Airflow Providers

_No response_

### Deployment

Astronomer

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by rawwar**
fixes #55062

### CODE REVIEW

**Comment by rawwar** [comment]
When XCom value was null in DB, UI showed error:
image

With the changes in the PR, it now shows "null"
image

File: airflow-core/src/airflow/ui/src/pages/XCom/XComEntry.tsx [hunk 1]
```diff
@@ -86,16 +87,16 @@ export const XComEntry = ({ dagId, mapIndex, runId, taskId, xcomKey }: XComEntry
...
     <HStack>
-      {["array", "object"].includes(typeof data?.value) ? (
-        <RenderedJsonField content={data?.value as object} enableClipboard={false} />
+      {isObjectOrArray ? (
+        <RenderedJsonField content={xcomValue as object} enableClipboard={false} />
       ) : (
         <Text>{renderTextWithLinks(valueFormatted)}</Text>
       )}
-      {Boolean(data?.value) ? (
+      {xcomValue === undefined ? undefined : (
```
Comment (jscheffl) [inline airflow-core/src/airflow/ui/src/pages/XCom/XComEntry.tsx]: Nit: `null` does nto make sense to copy, can you remove the clipboard icon when `null` value?

**Review by jscheffl — APPROVED** [review]
Interesting find! I am sure we had the same error in 2.9 or 2.10 when I added the JSON view to XCom that I was running into the same trap and forgot to check "null" values. Thanks for fixing!

Can you fix the small nit? Then good to merge I think

File: airflow-core/src/airflow/api_fastapi/execution_api/versions/__init__.py [hunk 2]
```diff
@@ -25,11 +25,14 @@
...
-from airflow.api_fastapi.execution_api.versions.v2025_09_23 import AddDagVersionIdField
+from airflow.api_fastapi.execution_api.versions.v2025_09_23 import (
+    AcceptNullXComSetValue,
+    AddDagVersionIdField,
+)
 
 bundle = VersionBundle(
     HeadVersion(),
-    Version("2025-09-23", AddDagVersionIdField),
+    Version("2025-09-23", AddDagVersionIdField, AcceptNullXComSetValue),
```
Comment (kaxil) [inline airflow-core/src/airflow/api_fastapi/execution_api/versions/__init__.py]: We are ok without the migration since technically this was a bug in FastAPI.

Code:

```py
from fastapi import FastAPI, Body
from fastapi.testclient import TestClient
from pydantic import JsonValue
from typing import Annotated


app = FastAPI()

@app.post('/echo')
async def echo(body: Annotated[JsonValue, Body()]):
    return {'received': body, 'type': str(type(body))}

client = TestClient(app)

print('1. Testing json=None (empty body):')
try:
    response = client.post('/echo', json=None)
    print('  Status:', response.status_code)
    if response.status_code == 200:
        print('  Response:', response.json())
    else:
        print('  Error:', response.text)
except Exception as e:
    print('  Exception:', e)

print()
print('2. Testing content=\"null\" (actual JSON null):')
try:
    response = client.post('/echo', content='null', headers={'Content-Type': 'application/json'})
    print('  Status:', response.status_code)
    if response.status_code == 200:
        print('  Response:', response.json())
    else:
        print('  Error:', response.text)
except Exception as e:
    print('  Exception:', e)

```

```
1. Testing json=None (empty body):
  Status: 422
  Error: {"detail":[{"type":"missing","loc":["body"],"msg":"Field required","input":null}]}

2. Testing content="null" (actual JSON null):
  Status: 422
  Error: {"detail":[{"type":"missing","loc":["body"],"msg":"Field required","input":null}]}

```

File: airflow-core/src/airflow/api_fastapi/execution_api/versions/v2025_09_23.py [hunk 3]
```diff
@@ -28,3 +28,12 @@ class AddDagVersionIdField(VersionChange):
...
     instructions_to_migrate_to_previous_version = (schema(TaskInstance).field("dag_version_id").didnt_exist,)
+
+
+class AcceptNullXComSetValue(VersionChange):
+    """Allow POST /xcoms/... value body to be JSON null in addition to JSON strings/objects/arrays."""
+
+    description = __doc__
+    # This is a backward-compatible relaxation of input validation; older clients are unaffected.
+    # No response transformation is needed when downgrading.
+    instructions_to_migrate_to_previous_version = ()
```
Comment (kaxil) [inline airflow-core/src/airflow/api_fastapi/execution_api/versions/v2025_09_23.py]: We can remove this since technically `pydanticJsonValue` supports `None`

Comment (kaxil) [reply airflow-core/src/airflow/api_fastapi/execution_api/versions/v2025_09_23.py]: (so no server changes)

**Review by kaxil — APPROVED** [review]

File: airflow-core/src/airflow/ui/src/pages/XCom/XComEntry.tsx (hunk 1 above)
Comment (rawwar) [reply airflow-core/src/airflow/ui/src/pages/XCom/XComEntry.tsx]: Done. 
image

**Review by amoghrajesh — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by jscheffl** [comment]
I propose we should backport this to 3.0-line as well.

**Comment by amoghrajesh** [comment]
Yeah, it is a bug-fix

**Comment by amoghrajesh** [comment]
@jscheffl the backport tool won't work post merge. Manual port will be required

**Comment by amoghrajesh** [comment]
@rawwar could you please create a manual backport?

**Comment by jscheffl** [comment]
@amoghrajesh did it already in https://github.com/apache/airflow/pull/55095

**Comment by prakharcode** [comment]
I have a question regarding this fix, I am on airflow version 3.0.6 and using `apache/airflow:slim-3.0.6-python3.11`. I don't see this fix in that image. Is this not available in `3.0.6` or am I missing something? 

EDIT: I see the fix in the changelog [here](https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#id18) in v3.1.0. Do I have to update to 3.1.0?

**Comment by pierrejeambrun** [comment]
@prakharcode Yes, we do not backport bugfixes to older versions, it was fixed and merged for 3.1.0, you need to upgrade to benefit from this. (or cherry pick that patch and build your own airflow, but that's more effort)

**Comment by emilsauer** [comment]
Also seeing this on Airflow 3.0.6. AWS MWAA currently does not offer Airflow 3.1 Environments, so it's very unfortunate this bug fix cannot be applied for older versions.

**Comment by potiuk** [comment]
> Also seeing this on Airflow 3.0.6. AWS MWAA currently does not offer Airflow 3.1 Environments, so it's very unfortunate this bug fix cannot be applied for older versions.

It can be. Those who run managed service can backport any change to their versions. This is open source and people work here mostly as volunteers and you get what you pay for - i.e. you pay 0 to airflow community and you pay maintenance fee to whoever you bought managed service frome.

It seems pretty eggregious to demand people who work for free to do something to do  "extra effort" rather than those who get money for maintenace. I guess you should be demanding more from those who your money are directed to, rather than those who you paid exactly 0. @emilsauer .

Or am I missing something?

**Comment by emilsauer** [comment]
> > Also seeing this on Airflow 3.0.6. AWS MWAA currently does not offer Airflow 3.1 Environments, so it's very unfortunate this bug fix cannot be applied for older versions.
> 
> It can be. Those who run managed service can backport any change to their versions. This is open source and people work here mostly as volunteers and you get what you pay for - i.e. you pay 0 to airflow community and you pay maintenance fee to whoever you bought managed service frome.
> 
> It seems pretty eggregious to demand people who work for free to do something to do "extra effort" rather than those who get money for maintenace. I guess you should be demanding more from those who your money are directed to, rather than those who you paid exactly 0. @emilsauer .
> 
> Or am I missing something?

I appreciate the context. I think there was a misunderstanding of my intent. I certainly wasn't demanding a backport or suggesting extra effort from the community.

My comment was meant to document that the issue persists in 3.0.6 for the benefit of other users who, like me, are currently restricted to that version. Since this bug is not trivial to diagnose, I wanted to provide a reference point for others to share findings or workarounds. I just wanted to clarify my intent here. Thanks for the work on the project.
