### PR TITLE
Pause auto-refresh when page is hidden

### LINKED ISSUE #21302: Pause auto-refresh when the document becomes hidden
### Description

When running Airflow it can be common to leave some tabs of Airflow open but not active. I believe (but not 100% sure, if I am wrong I can close this issue) Airflow's auto-refresh keeps refreshing when the document becomes hidden (for example, you switched to another browser tab).

This is not desirable in the cases when you are running the Airflow services on your same machine and you have a long-running DAG (taking hours to run). This could cause your CPU utilization to ramp up in this scenario (which can be quite common for users, myself included):

1. You are running the Airflow services on your same machine
2. Your machine is not that powerful
3. You have a long-running DAG (taking hours to run)
4. You leave a auto-refreshing page(s) of that DAG open for a long time (such as tree or graph) in hidden (or non-focused) tabs of your browser
    - What can make this even worse is if you have multiple tabs like this open, you are multiplying the extra processing power to refresh the page at a short interval
5. You have not increased the default `auto_refresh_interval` of 3

### Use case/motivation

I am proposing the following improvements to the auto-refresh method to improve this situation:

1. When you change tabs in your browser, there is a feature of Javascript in modern browsers called "Page Visibility API". It allows for the use of listeners on a `visibilitychange` event to know when a document becomes visible or hidden. This can be used to pause auto-refresh when the document becomes hidden.
    - Discussion on Stack Overflow: https://stackoverflow.com/questions/1060008/is-there-a-way-to-detect-if-a-browser-window-is-not-currently-active
    - MDN: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
    - W3C: https://www.w3.org/TR/page-visibility/
2. We should provide a message in the UI to alert the user that the auto-refreshing is paused until the page regains focus.
3. Lastely, the option to only auto-refresh if the document is visible should be a configurable setting.

Additionally, the older `onblur` and `onfocus` listeners on the entire document could be used too. That way if a user switches to a different window while the page is still visible, the auto-refresh can pause (although this might not be desirable if you want to have Airflow open side-by-side with something else, so maybe this will be overboard)

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by bbovenzi**
This PR adds an event listener for the grid and graph views to pause auto-refresh when the tab or browser is no longer active. When the page is refocused, auto-refresh will turn on if there are still pending tasks.

In our react grid view, we are using `react-query` as it comes with this and caching out-of-the-box. And will be more useful as we do more API calls in that view.

Also, I decided to pass the dagRun data to each table row via props instead of hooks cause it was causing extraneous rerenders.

Closes: #21302

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

File: airflow/www/static/js/utils.js [hunk 1]
```diff
@@ -41,3 +41,23 @@ export const finalStatesMap = () => new Map([
   ['skipped', 0],
   ['no_status', 0],
 ]);
+
+// Get hidden and visibility strings depending on browser
+export const getVisibilityVars = () => {
+  let hidden;
+  let visibilityChange;
+  if (typeof document.hidden !== 'undefined') { // Opera 12.10 and Firefox 18 and later support
```
Comment (ashb) [inline airflow/www/static/js/utils.js]: What browsers do we actually need this conditional for? Opera 12 and FF 18 are Oooold.

**Comment by bbovenzi** [comment]
- Simplified the event listener in graph view.
- Now using `react-query` for the grid view to make that hook work more efficiently and set the grid view up for more API calls in later PRs

**Review by ryanahamilton — APPROVED** [review]
LGTM!
