### PR TITLE
56058: Removing refresh state consumption for Dag header

### LINKED ISSUE #56058: Dag unpause loading issue on UI
### Apache Airflow version

3.1.0RC1

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

https://github.com/user-attachments/assets/9e622796-aca4-4c3f-9d9e-6a6c67d11479

### What you think should happen instead?

_No response_

### How to reproduce

Unpause any dag via UI and see the loading issue.

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by viveknanda**
closes: #56058

---
Change in this PR aim to remove the spinner from Dag Header as suggested by @bbovenzi [here](https://github.com/apache/airflow/issues/56058#issuecomment-3386572268)

**GIF**
dag-loading

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/pages/Dag/Dag.tsx [hunk 1]
```diff
@@ -106,13 +106,7 @@ export const Dag = () => {
   return (
     <ReactFlowProvider>
       <DetailsLayout error={error ?? runsError} isLoading={isLoading || isLoadingRuns} tabs={displayTabs}>
-        <Header
-          dag={dag}
-          isRefreshing={
-            latestRun ? Boolean(isStatePending(latestRun.state) && Boolean(refetchInterval)) : false
-          }
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/Dag/Dag.tsx:126]: You also need to delete the implementation of the refresh in the header itself since we will not need it anymore.

**Review by pierrejeambrun — COMMENTED** [review]
Thanks for the pull request.

You also need to update the behavior for other types of `Header`. There are multiple Header components with a similar behavior, for instance `Run/Header.tsx`, `TaskInstance/Header.tsx` and so on. We should also remove the spinner there.

**Comment by viveknanda** [comment]
> Thanks for the pull request.
> 
> You also need to update the behavior for other types of `Header`. There are multiple Header components with a similar behavior, for instance `Run/Header.tsx`, `TaskInstance/Header.tsx` and so on. We should also remove the spinner there.

@pierrejeambrun sure I will update likewise. I did [ask the same question in the ticket](https://github.com/apache/airflow/issues/56058#issuecomment-3535572137), but given no response, I tried to be conservative and only touched this particular component.

**Review by bbovenzi — APPROVED** [review]
