### PR TITLE
Fix grid links for tasks with retries

### LINKED ISSUE #56977: Web UI returns 404 when switching between task logs with different try numbers
### Apache Airflow version

3.1.0

### If "Other Airflow 2/3 version" selected, which one?

_No response_

### What happened?

There is a bug in the Airflow Web UI when switching between task logs of different tasks within the same DAG run.
If you open the log of a task that has multiple tries(e.g. second try) and then switch to another task that has fewer tries, the Web UI tries to load the same try_number as before - resulting in a 404 error.

Image

### What you think should happen instead?

When switching between tasks, the Web UI should automatically reset the try_number to 1(or to the latest available try for that task), rather than reusing the previous try number.

### How to reproduce

1. Open the log for a task that has more than one try, e.g.
`/dags/some_dag_name/runs/scheduled__2025-10-21T16:03:00+00:00/tasks/task_name?try_number=2`
2. In the Web UI, switch to another task that has only one try.
3. The UI requests the same try_number=2 for the new task, which doesn’t exist.
4. The request returns 404 Not Found.
5. If you remove `?try_number=2` from the URL, the log loads correctly.

### Operating System

Debian

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

This issue makes it confusing when browsing logs for tasks with different retry counts - the page fails instead of gracefully showing the available log.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pierrejeambrun**
closes: https://github.com/apache/airflow/issues/56977

It's super cool to keep search params when navigating between tasks in the grid, so we can keep log filtering (source, level etc...), but try_number should always be reseted. This will cause the UI to default to the latest try_number and prevent the issue reported #56977

(also moved the searchparams hook down to the GridTI component, we were passing those as prop for no reason)

### CODE REVIEW

**Review by eladkal — APPROVED** [review]

File: airflow-core/src/airflow/ui/src/layouts/Details/Grid/GridTI.tsx [hunk 1]
```diff
@@ -84,6 +85,8 @@ const Instance = ({ dagId, instance, isGroup, isMapped, onClick, runId, search,
     [dagId, isGroup, isMapped, location.pathname, runId, taskId],
   );
 
+  searchParams.delete("try_number");
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/layouts/Details/Grid/GridTI.tsx:91]: Wait, what is this doing?

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/layouts/Details/Grid/GridTI.tsx:91]: Removing the 'try_number' from the `searchParams` object, without operating a `setSearchParam`, so when we do 
`searchParams.toString()` a little bit further down in the same component to create the Link URL, `try_number` won't be there in the generated target link. (The goal is to remove the `try_number` query param from the redirection url)

Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/layouts/Details/Grid/GridTI.tsx:91]: Mind leaving a comment for it? I think its a bit confusing seeing it sitting in the middle of the component without context

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/layouts/Details/Grid/GridTI.tsx:91]: Of course, I just updated the PR.

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/layouts/Details/Grid/GridTI.tsx:91]: https://github.com/apache/airflow/pull/57063/commits/00c8d5634e35ecf620c262d98b901ffc4b33cb19

**Review by bbovenzi — APPROVED** [review]
