### PR TITLE
Tree View UI for larger DAGs & more consistent spacing in Tree View

### LINKED ISSUE #16238: Airflow Tree View for larger dags
Hi, Airflow Web UI shows nothing on tree view for larger dags (more than 100 tasks), although it's working fine for smaller dags. Anything that is needed to be configured in `airflow.cfg` to support larger dags in the UI?

alt larger

Smaller Dag:

alt smaller

**Apache Airflow version**: 2.1.0 (Celery)

**Environment**: 

- **Cloud provider or hardware configuration**: `AWS EC2`
- **OS** (e.g. from /etc/os-release): `Ubuntu 18.04`
- **Kernel** (e.g. `uname -a`): `5.4.0-1045-aws`
- **Install tools**: `pip`

**What you expected to happen**:
It is rendering correctly on `Airflow 1.10.13 (Sequential)`

image

**How to reproduce it**:
Create a sample dag with `>=` 100 tasks

**Anything else we need to know**:
The cli command for viewing dag tree is working correctly `airflow tasks list services_data_sync --tree`

### PR DESCRIPTION
**Pull request by freget**
closes: #16238

Currently, the space available for the tree and operator names in the tree view is calculated by substracting a quite a few things from the screen width. This does not really make sense. It would be better to calculate the required width of the tree and add some more for operator names.

This PR makes a suggestion accordingly. 

Note: It might be even better to calculate the required width for operator names dynamically.

### CODE REVIEW

**Comment by freget** [comment]
@bbovenzi Maybe you can have a look.

File: airflow/www/static/js/tree.js [hunk 1]
```diff
@@ -73,7 +73,7 @@ document.addEventListener('DOMContentLoaded', () => {
   treeDepth += 1;
 
   const innerWidth = window.innerWidth > 1200 ? 1200 : window.innerWidth;
```
Comment (bbovenzi) [inline airflow/www/static/js/tree.js]:
```suggestion
```
This line is no longer necessary.

Comment (freget) [reply airflow/www/static/js/tree.js]: @bbovenzi Thanks, I should have checked that upfront.

**Review by bbovenzi — APPROVED** [review]
lgtm

**Review by ryanahamilton — APPROVED** [review]
