### PR TITLE
Format more dates with timezone

### LINKED ISSUE #9221: UI/TZ issue: incorectly mapping DAGs
**Apache Airflow version**:
1.10.9 and 1.10.10

**Environment:**:

- MySQL 5.7, TZ=PST
- airflow.cfg tested with time_zone=system, Los_Angeles/America, utc

**What happened**:

1. From a schedule view by clicking on DAG with Execution date 18:00 PST it maps me to 18:00 UTC DAG instance
2. In Browse TASK INSTANCE view, sorted by state failed displays correct tasks but when I choose to clear them it clears  task with UTC  execution dates

**How to reproduce it**:

In UI click under "Schedule" on gray schedule time button for any DAG 
Take first DAG and check its "Execution date" 

Screen Shot 2020-06-10 at 4 12 46 PM

click on it 

Screen Shot 2020-06-10 at 4 14 59 PM

open log and compare time stamps inside the log with "Execution date"

Screen Shot 2020-06-10 at 4 16 56 PM

**Bonus: miscalculating execution time in UI when in TZ aware**:

**1.10.10**

UI TZ=UTC - Correct Execution time stamp

Screen Shot 2020-06-10 at 4 28 43 PM

UI TZ=PST - Incorrect Execution time stamp

Screen Shot 2020-06-10 at 4 25 16 PM

### PR DESCRIPTION
**Pull request by bbovenzi**
A bunch of dates in the UI were not being formatted with the user's selected timezone from the dropdown in top navigation. I went through and updated as many as I could find.

Closes: #9221

One exception, for some reason, the task instance start date had an explicit comment to not format it, https://github.com/apache/airflow/blame/10ed42a837e11d8e954c1f885e289a4248edd2ca/airflow/www/static/js/task_instances.js#L82, @ashb should that remain the case?

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

File: airflow/www/static/js/datetime_utils.js [hunk 1]
```diff
@@ -88,6 +88,12 @@ export function updateAllDateTimes() {
   $('.datetime input').each((_, el) => {
     el.value = moment(el.value).format();
   });
+
+  $('.format-date').each((_, el) => {
```
Comment (ryanahamilton) [inline airflow/www/static/js/datetime_utils.js]:
```suggestion
  $('.js-format-date').each((_, el) => {
```

File: airflow/www/static/js/task.js [hunk 2]
```diff
@@ -17,11 +17,18 @@
...
-// reformat execution date to be more human-readable
+// reformat task details to be more human-readable
 document.addEventListener('DOMContentLoaded', () => {
-  const date = document.getElementById('ti_execution_date');
-  date.innerHTML = formatDateTime(date.innerHTML);
+  document.querySelectorAll('.ti-attr').forEach((attr) => {
+    const value = attr.innerHTML;
+    if (value.length === 32 && moment(value, 'YYYY-MM-DD').isValid()) {
+      // 32 is the length of our timestamps
+      attr.className = 'format-date';
```
Comment (ryanahamilton) [inline airflow/www/static/js/task.js]:
```suggestion
      attr.className = 'js-format-date';
```

File: airflow/www/static/js/ti_log.js [hunk 3]
```diff
@@ -113,7 +115,9 @@ function autoTailingLog(tryNumber, metadata = null, autoTailing = false) {
 
         // The message may contain HTML, so either have to escape it or write it as text.
         const escapedMessage = escapeHtml(item[1]);
-        const linkifiedMessage = escapedMessage.replace(urlRegex, (url) => `<a href="${url}" target="_blank">${url}</a>`);
+        const linkifiedMessage = escapedMessage
+          .replace(urlRegex, (url) => `<a href="${url}" target="_blank">${url}</a>`)
+          .replaceAll(dateRegex, (date) => `<span class="format-date">${formatDateTime(`${date}+00:00`)}</span>`);
```
Comment (ryanahamilton) [inline airflow/www/static/js/ti_log.js]:
```suggestion
          .replaceAll(dateRegex, (date) => `<span class="js-format-date">${formatDateTime(`${date}+00:00`)}</span>`);
```

File: airflow/www/templates/airflow/dag_details.html [hunk 4]
```diff
@@ -50,11 +50,11 @@ <h3>{{ title }}</h3>
     </tr>
     <tr>
       <th>Start Date</th>
-      <td>{{ dag.start_date }}</td>
+      <td class="format-date">{{ dag.start_date }}</td>
```
Comment (ryanahamilton) [inline airflow/www/templates/airflow/dag_details.html]:
```suggestion
      <td class="js-format-date">{{ dag.start_date }}</td>
```

File: airflow/www/templates/airflow/dag_details.html [hunk 5]
```diff
@@ -50,11 +50,11 @@ <h3>{{ title }}</h3>
...
     </tr>
     <tr>
       <th>End Date</th>
-      <td>{{ dag.end_date }}</td>
+      <td class="format-date">{{ dag.end_date }}</td>
```
Comment (ryanahamilton) [inline airflow/www/templates/airflow/dag_details.html]:
```suggestion
      <td class="js-format-date">{{ dag.end_date }}</td>
```

File: airflow/www/templates/airflow/task_instance.html [hunk 6]
```diff
@@ -26,7 +26,7 @@
   <br>
   <h4>
     <span class="text-muted">Task Instance:</span> <span>{{ task_id }}</span>
-    <span class="text-muted">at</span> <span id="ti_execution_date">{{ execution_date }}</span>
+    <span class="text-muted">at</span> <span class="format-date">{{ execution_date }}</span>
```
Comment (ryanahamilton) [inline airflow/www/templates/airflow/task_instance.html]:
```suggestion
    <span class="text-muted">at</span> <span class="js-format-date">{{ execution_date }}</span>
```

**Review by ryanahamilton — CHANGES_REQUESTED** [review]
Overall looks good. One request—I've been attempting to introduce this `js-` prefix pattern anywhere classes are needed as selectors. It makes it clear that they are not for styling purpose (nor should they be used for both) when you encounter a class name in an HTML file.

File: airflow/www/static/js/task.js [hunk 7]
```diff
@@ -17,11 +17,18 @@
...
-/* global document */
-import { formatDateTime } from './datetime_utils';
+/* global document, moment */
 
-// reformat execution date to be more human-readable
+// reformat task details to be more human-readable
 document.addEventListener('DOMContentLoaded', () => {
-  const date = document.getElementById('ti_execution_date');
-  date.innerHTML = formatDateTime(date.innerHTML);
+  document.querySelectorAll('.ti-attr').forEach((attr) => {
```
Comment (ryanahamilton) [inline airflow/www/static/js/task.js]: Sorry I didn't catch this last time, but should we change this one as well?
```suggestion
  document.querySelectorAll('.js-ti-attr').forEach((attr) => {
```

**Review by ryanahamilton — APPROVED** [review]
