### PR TITLE
Fix missing expand/collapse buttons in Grid view using shared group sync hook (#53919)

### LINKED ISSUE #53919: Task expand/collapse is intermittently available in grid view
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

Task expand/collapse option in grid view is only available after visiting the graph view.

https://github.com/user-attachments/assets/96ca68b0-bc23-4b9e-8c9a-da7a10cdc8de

### What you think should happen instead?

_No response_

### How to reproduce

Have any taskmap dag and start airflow instance, when you first open the dag details view, notice expand/collapse option is not available and only available once user opens graph view.

```python
from airflow.sdk import DAG
from airflow.decorators import task
from datetime import datetime, timedelta
from airflow.utils.task_group import TaskGroup


@task
def onetwothree():
    return [1, 2, 3]


@task
def consumer(value):
    print(value)


with DAG(
    dag_id="with_rename",
    start_date=datetime(1970, 1, 1),
    schedule=None,
    tags=["taskmap"]
) as dag:

    with TaskGroup("tg"):
        consumer(1)  # consumer
        consumer(2)  # consumer__1
        consumer.expand(value=[1, 2, 3])

``` 

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by sujitha-saranam**
This PR replaces #54172 (that PR was auto-closed after the branch was deleted).

#### Overview
This PR addresses https://github.com/apache/airflow/issues/53919 ensures that the Expand/Collapse all groups buttons are consistently visible in both the Grid and Graph views.

#### Root Cause:
The Expand/Collapse all groups buttons are visible only when the DAG contains task groups. These task groups (allGroupIds) were being calculated only in graph.tsx, but not in grid.tsx. As a result, the buttons were not rendered in the Grid view unless the Graph view was opened first,  which triggered the group ID calculation and updated OpenGroups.

#### Solution:
Moved the task group calculation and syncing logic into OpenGroupsProvider so it is initialized regardless of whether Graph or Grid view is loaded first. This ensures allGroupIds is always available in context and the Expand/Collapse all buttons render consistently in both views.

#### Changes Made:

- Updated `OpenGroupsProvider` to fetch and flatten DAG task group nodes and keep `allGroupIds` in sync with the DAG structure.
- `grid.tsx` now automatically has the group data via `OpenGroupsContext`, without needing a separate hook or logic duplication.

closes: #53919
related: #53919

### CODE REVIEW

**Review by pierrejeambrun — COMMENTED** [review]
Are you able to reproduce the issue on latest main? 

https://github.com/user-attachments/assets/b3c7ab68-b1b7-4cb8-800a-4f0341c00b60

**Comment by sujitha-saranam** [comment]
> Are you able to reproduce the issue on latest main?
> 
>  Screen.Recording.2025-08-08.at.18.27.01.mov

@pierrejeambrun yes.

https://github.com/user-attachments/assets/5d2af899-6908-41e0-bb4c-3b5d88fb04b8

If it’s still not reproducible, please try clearing the cache and check again. The issue is reproducible on my end.

I have attached a recording showing the issue being reproduced after clearing the cache.

https://github.com/user-attachments/assets/f3a0a173-cab9-48d8-8bbc-6d7d21bc891b

**Review by pierrejeambrun — COMMENTED** [review]
I can reproduce now, thanks.

We can either:
Move this up into the `OpenGroupsProvider`. As soon as we provide, we should fetch the structure and `setAllGroupIds` appropriately. (SInce both grid + graph need those)

Or if we want to be more efficient, in the grid, when getting the grid response, compute the `group ids` based on the response, and set the groups ids accordingly. Because otherwise we add a call to the 'structure' when we are just displaying the "Grid"  needed for the 'collapase/expand' buttons. That might not be necessary if we can compute groups based on the `grid` data instead.

File: airflow-core/src/airflow/ui/src/hooks/useGraphStructureSync.tsx [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+import { useEffect } from "react";
+import { useParams } from "react-router-dom";
+import { useLocalStorage } from "usehooks-ts";
+
+import { useStructureServiceStructureData } from "openapi/queries";
+import { useOpenGroups } from "src/context/openGroups";
+import useSelectedVersion from "src/hooks/useSelectedVersion";
+import { flattenGraphNodes } from "src/layouts/Details/Grid/utils.ts";
+
+export const useGraphStructureSync = () => {
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/hooks/useGraphStructureSync.tsx]: I think we should change this name. It's not descriptive enough, 'sync' doesn't mean much in this context. And most of this is not needed for the grid.

Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/hooks/useGraphStructureSync.tsx]: `useCalculateGraphGroups()`? Still kind of clunky

**Comment by bbovenzi** [comment]
Let's move this logic into the opengroups provider instead of making a separate hook. It's critical to how the provider works and the hook calls are confusing without necessary context which could lead to maintenance issues

**Comment by sujitha-saranam** [comment]
Hi @pierrejeambrun and @bbovenzi 
I’ve updated the PR based on your feedback. Please review the changes and let me know if any further adjustments are needed.

**Review by bbovenzi — APPROVED** [review]
