### PR TITLE
Fix asset name overflow in DAG list view

### LINKED ISSUE #56669: Dag schedules with longer asset names overlap with the entry in the latest run field in dag list
### Apache Airflow version

3.1.0

### If "Other Airflow 2/3 version" selected, which one?

3.0.0 onwards

### What happened?

For the airflow 3 versions, when the dag schedule is based on an asset with the longer name, the name of the asset extends to overlap with the last run field and makes it hard to read the timestamp of the last run , for the user .

Image

### What you think should happen instead?

The name of the assets should be handled in such a way that the field values don't overlap with each other

### How to reproduce

1. Deploy the dags with asset based schedule to airflow version 3.0.0 based deployment
2. Run the dags and verify if the name of the asset overlaps the last run field

### Operating System

os

### Versions of Apache Airflow Providers

Official Apache Airflow Helm Chart

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

Related to https://github.com/apache/airflow/issues/55721

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by TyrellHaywood**
**Description:**

Fixes asset names overlapping with the "Latest Run" field in the DAG list view by adding `maxWidth` constraints to `HStack` containers in the `AssetSchedule` component.

When DAGs have asset-based schedules with long asset names, the names were extending beyond their column boundaries and overlapping with the "Latest Run" timestamp field, making it difficult to read.

This change adds `maxWidth="200px"` to the `HStack` containers wrapping asset names in the `AssetSchedule` component, ensuring proper text truncation and preventing overlap with adjacent columns.

closes: #56669

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

**Review by pierrejeambrun — COMMENTED** [review]
Can you add a screenshot after this change? 

I'm not a fan of adding hard coded width in pixel. That could still happen on small screens I guess. Instead we could wrap/word break if it's too big.

**Comment by TyrellHaywood** [comment]
@pierrejeambrun 

Thanks for the feedback! Yes that makes more sense. I've updated the approach to use word-break instead of a hard-coded pixel width. The asset names now wrap to a maximum of 2 lines before truncating with ellipsis, which prevents overflow while keeping the layout clean.

Here's a screenshot showing the fix with long asset names:
image

Let me know if this looks good!

File: airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx [hunk 1]
```diff
@@ -61,9 +61,23 @@ export const AssetSchedule = ({ assetExpression, dagId, latestRunAfter, timetabl
...
+            textOverflow: "ellipsis",
+            WebkitBoxOrient: "vertical",
+            WebkitLineClamp: 2,
+            wordBreak: "break-word",
+          }}
+          display="-webkit-box"
+          flex="1"
+          fontSize="sm"
+          minWidth="0"
+        >
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx]: There is already a `TruncatedText` component to achieve exactly that.

**Comment by pierrejeambrun** [comment]
I just pushed a commit to use the existing component instead:
Screenshot 2025-10-27 at 16 07 42

File: airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx (hunk 1 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/DagsList/AssetSchedule.tsx]: Done

**Review by pierrejeambrun — APPROVED** [review]
