### PR TITLE
Logout functionality should respect `base_url` config in `api` section

### LINKED ISSUE #49534: Logout broken if base_url has a suffix in 3.0.0rc4
### Apache Airflow version

3.0.0

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

In airflow 3.0.0rc4, my api.base_url is `https://mycompany.com/airflow` . All the FastAPI calls have the `/airflow/` prefix set correctly. However, the logout calls `/api/v2/auth/logout` directly without the `/airflow` prefix. This causes my nginx to error out. ( this screenshot is from my scratch airflow dev env where I can see the issue )

Image

my nginx settings 
```
    location /airflow {
            proxy_buffers 16 4k;
            proxy_buffer_size 2k;
            proxy_set_header host $host;
            proxy_set_header x-real-ip $remote_addr;
            proxy_set_header x-forwarded-host $host:$server_port;
            proxy_set_header x-forwarded-server $host;
            proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
            proxy_set_header x-forwarded-proto $scheme;

            proxy_pass http://airflow-apiserver:8080;
            proxy_read_timeout 90;

            proxy_redirect http://airflow-apiserver:8080 https://_;
    }
```

### What you think should happen instead?

the GET should hit `/airflow/api/v2/auth/logout`

### How to reproduce

you should be able to observer this in the logs with just the airflow defaults. You just need 
```
airflow api-server
```
let it spin the db and airflow.cfg

### Operating System

Ubuntu

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else?

cc: @ashb @Dev-iL 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by amoghrajesh**
closes: https://github.com/apache/airflow/issues/49534

The logout functionality should respect the "base_url" that is set. It wasn't doing so because there was a hardcoded occurrence: https://github.com/apache/airflow/blob/main/airflow-core/src/airflow/ui/src/layouts/Nav/LogoutModal.tsx#L35.

With base_url set:
Played around a bit on the console:
```
const baseHref = "/airflow/"
  const baseUrl = new URL(baseHref, globalThis.location.origin);
  const logoutPath = new URL("api/v2/auth/logout", baseUrl).pathname;


logoutPath
'/airflow/api/v2/auth/logout'
```

Without:
```
      const baseHref = document.querySelector("head>base")?.getAttribute("href") ?? "";
      const baseUrl = new URL(baseHref, globalThis.location.origin);
      const logoutPath = new URL("api/v2/auth/logout", baseUrl).pathname;
logoutPath
'/api/v2/auth/logout'
```

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/layouts/Nav/LogoutModal.tsx [hunk 1]
```diff
@@ -31,8 +31,12 @@ const LogoutModal: React.FC<LogoutModalProps> = ({ isOpen, onClose }) => (
   <ConfirmationModal
     header="Logout"
     onConfirm={() => {
+      const baseHref = document.querySelector("head>base")?.getAttribute("href") ?? "";
+      const baseUrl = new URL(baseHref, globalThis.location.origin);
+      const logoutPath = new URL("api/v2/auth/logout", baseUrl).pathname;
+
       localStorage.removeItem(TOKEN_STORAGE_KEY);
-      globalThis.location.replace(`/api/v2/auth/logout`);
+      globalThis.location.replace(logoutPath);
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Nav/LogoutModal.tsx:39]: Nit: I think we should extract a small utility function for this piece of code. To not duplicate it from the `main.tsx` file.

Basically something like. `getRedictPath(targetPath)`. (That will read the tag and take this into account.

**Review by pierrejeambrun — APPROVED** [review]
Nice thanks.

One small suggestion. But non blocking.

File: airflow-core/src/airflow/ui/src/layouts/Nav/LogoutModal.tsx (hunk 1 above)
Comment (amoghrajesh) [reply airflow-core/src/airflow/ui/src/layouts/Nav/LogoutModal.tsx:39]: Yeah sure we can do that. But you mean only for this one occurence right? Or reuse that function across main.tsx and this one?

**Review by vincbeck — APPROVED** [review]

File: airflow-core/src/airflow/ui/src/layouts/Nav/LogoutModal.tsx (hunk 1 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/layouts/Nav/LogoutModal.tsx:39]: The utility function should be used across main and this one. We can merge that now to fix the issue, and we can always cleanup in follow up PRs if you'd like

Comment (amoghrajesh) [reply airflow-core/src/airflow/ui/src/layouts/Nav/LogoutModal.tsx:39]: Yeah makes sense. Let me clean it in a follow up
