### PR TITLE
Fix Legacy UI Button Navigation Issue

### LINKED ISSUE #46516: "Legacy UI" button in New UI does not work
### Apache Airflow version

3.0.0a1

### If "Other Airflow 2 version" selected, which one?

3.0.0a1

### What happened?

"Legacy UI" button in New UI does not work (I think it links to 28080 instead of 8080)

### What you think should happen instead?

It should go back to the old UI

### How to reproduce

```sh
uv venv --python 3.12

uv pip install \
    --find-links https://dist.apache.org/repos/dist/dev/airflow/3.0.0a1/ \
    apache-airflow==3.0.0a1 \
    apache-airflow-task-sdk==1.0.0a1 \
    apache-airflow-providers-standard==0.1.0a1 \
    apache-airflow-providers-fab==2.0.0a1 \
    apache-airflow-providers-celery==3.11.0a1
export AIRFLOW_HOME=`pwd`

uv run airflow db migrate
uv run airflow standalone
```

1. Open `http://localhost:9091`
2. Click the "Legacy UI" button

### Operating System

macOS 15.3

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==3.11.0a1
apache-airflow-providers-common-compat==1.3.0
apache-airflow-providers-common-io==1.5.0
apache-airflow-providers-common-sql==1.21.0
apache-airflow-providers-fab==2.0.0a1
apache-airflow-providers-ftp==3.12.0
apache-airflow-providers-http==5.0.0
apache-airflow-providers-imap==3.8.0
apache-airflow-providers-smtp==1.9.0
apache-airflow-providers-sqlite==4.0.0
apache-airflow-providers-standard==0.1.0a1

### Deployment

Other

### Deployment details

`airflow standalone`

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by SaumilPatel03**
**What was wrong:** 
The "Legacy UI" button in the New UI was misdirecting users by linking to an incorrect URL (wrong port), which prevented proper navigation to the legacy interface.

**What was changed:**
I updated the "Legacy UI" button to navigate to https://localhost:28080/

Closes: #46516 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

File: airflow/ui/src/layouts/Nav/Nav.tsx [hunk 1]
```diff
@@ -59,7 +59,7 @@ export const Nav = () => {
         <NavButton
           icon={<FiCornerUpLeft size="1.75rem" />}
           title="Legacy UI"
-          to={import.meta.env.VITE_LEGACY_API_URL}
+          to="http://0.0.0.0:28080/home"
```
Comment (jscheffl) [inline airflow/ui/src/layouts/Nav/Nav.tsx]: Mhm, 0.0.0.0 is not a valid address - Why are you sure this is fixing the button?
I assume per default to link is broken if the ENV file is not adjusted.

**Review by jscheffl — APPROVED** [review]
