### PR TITLE
fix: use Dag form when materializing asset

### LINKED ISSUE #63807: No option to provide partition key while materialising an asset
### Apache Airflow version

main (development)

### If "Other Airflow 3 version" selected, which one?

_No response_

### What happened?

Image

### What you think should happen instead?

_No response_

### How to reproduce

1. Start airflow instance on main branch.
2. Go to 'Assets' page and try to materialise an asset, notice there is no option to provide the partition key.

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Lee-W**
## Why
Closes: #63807

## What
Use Dag from when materializing the asset
image
image

 

---

##### Was generative AI tooling used to co-author this PR?

- [x] Yes (please specify the tool below)

Generated-by: Cursor following [the guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#gen-ai-assisted-contributions)

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments). You can add this file in a follow-up commit after the PR is created so you know the PR number.

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/components/TriggerDag/TriggerDAGForm.tsx [hunk 1]
```diff
@@ -58,21 +60,30 @@ type TriggerDAGFormProps = {
...
+    error: triggerError,
+    isPending: isTriggerPending,
+    triggerDagRun,
+  } = useTrigger({ dagId, onSuccessConfirm: onClose });
   const { conf, initialParamDict, setConf, setInitialParamDict } = useParamStore();
   const [unpause, setUnpause] = useState(true);
-
+  const submitError = submitErrorOverride ?? triggerError;
+  const submitPending = isPendingOverride ?? isTriggerPending;
+  const submitTrigger = onSubmitTrigger ?? triggerDagRun;
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/components/TriggerDag/TriggerDAGForm.tsx]: Nit. we can drop "submit" from all of these. The function should also be a verb like "onTrigger"

**Review by bbovenzi — COMMENTED** [review]
Looks good.

But I am wondering if creating the concept of "materialize" has added unnecessary overhead. Now, we can do all of this with the existing trigger dag post endpoint except for having a different run type.

File: airflow-core/src/airflow/ui/src/components/TriggerDag/TriggerDAGForm.tsx [hunk 2]
```diff
@@ -58,21 +60,30 @@ type TriggerDAGFormProps = {
 const TriggerDAGForm = ({
   dagDisplayName,
   dagId,
+  error: submitErrorOverride,
   hasSchedule,
   isPartitioned,
   isPaused,
+  isPending: isPendingOverride,
   onClose,
+  onSubmitTrigger,
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/components/TriggerDag/TriggerDAGForm.tsx]: If we stay with materialize and trigger being two different actions then I think we should remove the direct `useTrigger` API call from this component. Then we don't need any overrides.

Only keeping pause toggle when submitting

File: airflow-core/src/airflow/ui/src/components/TriggerDag/TriggerDAGForm.tsx (hunk 1 above)
Comment (Lee-W) [reply airflow-core/src/airflow/ui/src/components/TriggerDag/TriggerDAGForm.tsx]: due to another comment, this no longer exists

File: airflow-core/src/airflow/ui/src/components/TriggerDag/TriggerDAGForm.tsx (hunk 2 above)
Comment (Lee-W) [reply airflow-core/src/airflow/ui/src/components/TriggerDag/TriggerDAGForm.tsx]: updated. Thanks!

File: airflow-core/src/airflow/api_fastapi/core_api/datamodels/assets.py [hunk 3]
```diff
@@ -185,3 +192,21 @@ def set_from_rest_api(cls, v: dict) -> dict:
         return v
 
     model_config = ConfigDict(extra="forbid")
+
+
+class MaterializeAssetBody(TriggerDAGRunPostBody):
+    """Materialize asset request."""
+
+    logical_date: AwareDatetime | None = None
```
Comment (jason810496) [inline airflow-core/src/airflow/api_fastapi/core_api/datamodels/assets.py:200]: We already had `logical_date` field for `TriggerDAGRunPostBody`, do we still need to add it again here?

https://github.com/apache/airflow/blob/13f3e267fb85970de7b25bf41019fcfade8ba014/airflow-core/src/airflow/api_fastapi/core_api/datamodels/dag_run.py#L103

File: airflow-core/tests/unit/api_fastapi/core_api/routes/public/test_assets.py [hunk 4]
```diff
@@ -1408,6 +1408,36 @@ def test_should_respond_200(self, test_client):
...
+        partition_key = "2026-03-23"
+        response = test_client.post("/assets/1/materialize", json={"partition_key": partition_key})
+        assert response.status_code == 200
+        assert response.json()["partition_key"] == partition_key
+
+    @pytest.mark.usefixtures("configure_git_connection_for_dag_bundle")
+    def test_should_respond_200_with_trigger_fields(self, test_client):
+        payload = {
+            "conf": {"foo": "bar"},
+            "dag_run_id": "asset_materialization_run_1",
```
Comment (jason810496) [inline airflow-core/tests/unit/api_fastapi/core_api/routes/public/test_assets.py:1422]: Should we leave `dag_run_id` unset here to verify the behavior of `MaterializeAssetBody.validate_context`?

**Review by jason810496 — COMMENTED** [review]
LGTM overall on the API side.

File: airflow-core/src/airflow/api_fastapi/core_api/datamodels/assets.py (hunk 3 above)
Comment (Lee-W) [reply airflow-core/src/airflow/api_fastapi/core_api/datamodels/assets.py:200]: to set the default as None

File: airflow-core/tests/unit/api_fastapi/core_api/routes/public/test_assets.py (hunk 4 above)
Comment (Lee-W) [reply airflow-core/tests/unit/api_fastapi/core_api/routes/public/test_assets.py:1422]: yep, let me add one such case

Comment (Lee-W) [reply airflow-core/tests/unit/api_fastapi/core_api/routes/public/test_assets.py:1422]: just added

**Review by jason810496 — APPROVED** [review]
LGTM on API side.

**Review by bbovenzi — APPROVED** [review]
