### PR TITLE
Display plugin import errors in the UI

### LINKED ISSUE #48994: Broken plugin details not showing on UI
### Apache Airflow version

3.0.0

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

In AF2, if we had an issue with plugins used to get error banner in UI, However, in AF3 We are not getting that. I just see an error message in the scheduler logs.

**AF2**

Image

**AF3 UI**

Image

**AF3 scheduler logs**

Image

### What you think should happen instead?

Broken plugin details should be visible in UI

### How to reproduce

Try to add a broken plugin

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pierrejeambrun**
closes: https://github.com/apache/airflow/issues/48994

Depends on https://github.com/apache/airflow/pull/49436

I plan a follow up PR to re-organize files and factorize code between the DagImportErrors and PluginImportErrors.

Screenshot 2025-04-23 at 19 58 10
Screenshot 2025-04-23 at 19 58 18
Screenshot 2025-04-23 at 20 04 42

### CODE REVIEW

**Comment by bbovenzi** [comment]
Was this rebased against main after https://github.com/apache/airflow/pull/49519 was merged?

File: airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/PluginImportErrorsModal.tsx [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+    setFilteredErrors(filtered);
+    setPage(1);
+  }, [searchQuery, importErrors]);
+
+  return (
+    <Dialog.Root onOpenChange={onOpenChange} open={open} scrollBehavior="inside" size="xl">
+      <Dialog.Content backdrop>
+        <Dialog.Header>
+          <HStack fontSize="xl">
+            <LuFileWarning />
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/PluginImportErrorsModal.tsx:68]: Wanna use the plugin icon here instead?

File: airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/PluginImportErrors.tsx [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+        <>
+          {iconOnly ? (
+            <StateBadge
+              as={Button}
+              colorPalette="failed"
+              height={7}
+              onClick={onOpen}
+              title={pluralize("Plugin Import Error", importErrorsCount)}
+            >
+              <AiOutlineApi size="0.5rem" />
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/PluginImportErrors.tsx]: Let's use the same Plugin icon we use in the Navbar: `<LuPlug />`

**Review by bbovenzi — COMMENTED** [review]
Let's include this on the Admin -> Plugins page too

**Comment by pierrejeambrun** [comment]
> Was this rebased against main after https://github.com/apache/airflow/pull/49519 was merged?

Yes it was

File: airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/PluginImportErrorsModal.tsx (hunk 1 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/PluginImportErrorsModal.tsx:68]: Done thanks

File: airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/PluginImportErrors.tsx (hunk 2 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/Dashboard/Stats/PluginImportErrors.tsx]: Yes you'r right thanks

**Comment by pierrejeambrun** [comment]
User without permissions to view the plugins:

Screenshot 2025-04-24 at 11 33 10

**Review by bbovenzi — APPROVED** [review]
