### PR TITLE
Fix UI keeps poking pools API when no permission

### LINKED ISSUE #54969: Pool summary widget is stuck in retry loop when user has no access to read pools
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

When a user has no access to pools then the API call for pools returns 403 and the frontend keeps retrying the request. We have some roles where pool access including menu access is not granted to the users.

### What you think should happen instead?

_No response_

### How to reproduce

1. Update user role to remove can read pools access.
2. Go to home page and pools widget keeps trying to load though pools API returns 403.

### Operating System

Ubuntu 20.04

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by yimingpeng**
Closes: #54969 

## Problem Summary
The pools widget on the HomePage is hammering the API when users don't have the `can read on Pools` permission.

## Proposed Solution
- Call the pool API first 
- If the error.status `403` is captured, then we stop all further request retries and disable auto-refresh for this component
- Show `403 Forbidden` 

### Before the fix
Pasted image 20250927212904

### After the fix
Pasted image 20250927224615

## Questions
Dear Committers and Reviewers, 

Just thinking loudly, given the granularity of these permissions, this problem could potentially affect other UI components? I haven't tested others, but happy to investigate further if you think that would make sense?

Looking forward to your comments and review feedbacks
Thanks!

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

**Review by prdai — APPROVED** [review]

File: airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx [hunk 1]
```diff
@@ -17,25 +17,42 @@
...
+    enabled: !hasPermissionError,
+    refetchInterval: hasPermissionError ? false : refetchInterval,
+    retry: (failureCount, retryError) => {
+      if (Boolean(retryError) && (retryError as ExpandedApiError).status === 403) {
+        setHasPermissionError(true);
+
+        return false;
+      }
+
+      return failureCount < 3;
```
Comment (shahar1) [inline airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx]: Small nit - Could you please make `3` a constant? (`MAX_API_POLL_ATTEMPTS`, or something like that)

While 3 is almost a synonym in Airflow for max. number of tries, it will make it easier for other contributors to understand this code part, and it will be easier to make it configurable if we find it necessary at some point.

**Comment by tirkarthi** [comment]
I feel it's better to hide the component itself when there is no permission like how menu links are filtered out.

File: airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx [hunk 2]
```diff
@@ -17,25 +17,42 @@
...
+    },
+  });
+
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx:49]: Instead of state, I think we should just check if the error is a 403 and return undefined. No need to track state and mess with the retry number. I have a separate draft PR to fix the refetchInterval from firing incessantly

**Review by pierrejeambrun — COMMENTED** [review]
I share Brent feeling, maybe we should just render 'nothing' if we get a 403 response, by returning undefined.

That will avoid persisting any states .

File: airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx (hunk 2 above)
Comment (yimingpeng) [reply airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx:49]: Thanks for review, yep, you're right, that's a better approach.

**Comment by yimingpeng** [comment]
Thanks everyone for providing the review feedback.

I've updated accordingly, please have another look whenever you have a chance, the page looks tidier now, and `auto-refresh` will still try 3 times which should be addressed in a separated PR from Brent, thanks 

image

File: airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx [hunk 3]
```diff
@@ -23,19 +23,30 @@ import { Link as RouterLink } from "react-router-dom";
...
+      const apiError = query.state.error as ExpandedApiError | null;
+
+      return apiError?.status === 403 ? false : refetchInterval;
+    },
+  });
+
+  if (Boolean(error) && (error as ExpandedApiError).status === 403) {
+    return undefined;
+  }
+
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx]: You should be able to get away with something like this. It will avoid hard casting at multiple places with `as`.

```suggestion
    const { data, error, isLoading } = usePoolServiceGetPools<
    PoolServiceGetPoolsDefaultResponse,
    AxiosError<HTTPExceptionResponse>
  >(undefined, undefined, {
    refetchInterval: (query) => {
      const apiError = query.state.error;

      return apiError?.status === 403 ? false : refetchInterval;
    },
  });

  if (error?.response?.status === 403) {
    return undefined;
  }
```

**Review by pierrejeambrun — COMMENTED** [review]
Looking much cleaner. 

Just one suggestion to avoid hard casting, and we should be good to merge. Thanks for the PR.

File: airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx (hunk 3 above)
Comment (yimingpeng) [reply airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx]: Thanks for the great suggestion, @pierrejeambrun 

I've been testing the proposed changes and found that using `AxiosError` and `ApiError` produce different UI behaviors? Perhaps I've done something wrong here, so before proceeding further, I would like to seek some clarification on expected behavoirs, also I am still learning and investigating why, it would be appreciated if you can share some insights, thanks. 

The following is a summary of the differences.

### Test Scenario 1: Only `can read on Pools` (menu access stays)
Simply put, using the `ApiError` will hide everything relating to Pools Slots/Menu whereas using `AxiosError` will leave a lable of `Pool Slots` & `Manage Pools` on the UI. 
#### using `AxiosError`
Pasted image 20251002161504

#### using `ApiError`
Pasted image 20251002161546

### Test Scenario 2: Both `can read on Pools` and `menu access on Pools` removed
The use of the `ApiError` still hides everything about Pools, but if using `AxiosError`, only the label `Pool Slots` left.
#### using `AxiosError`
image

#### using `ApiError`
Pasted image 20251002161546

### Test Scenario 3: Only `menu access on Pools` removed (`can read on Pools` stays)
This should be fine, they are the same. 
#### using `AxiosError`
image

#### using `ApiError`
image

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx]: The important part for type checking issues is:
```
usePoolServiceGetPools<
	    PoolServiceGetPoolsDefaultResponse,
	    AxiosError<HTTPExceptionResponse>
	  >
```

This should have no impact at run-time and you can keep the original version of your code or iteratively check why there is a difference. (and play around with the typing there to make the linter happy)

The expected behavior I think is to see 'nothing' at all related to the PoolSummary component when permissions are not right.

Comment (yimingpeng) [reply airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx]: Thank you @pierrejeambrun, I believe it has been addressed now. Please let me know if anything else should be addressed.

When there are no permissions granted on Pools, the UI now looks as expected.
image

File: airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx [hunk 4]
```diff
@@ -21,21 +21,36 @@ import { useTranslation } from "react-i18next";
...
 
 export const PoolSummary = () => {
   const { t: translate } = useTranslation("dashboard");
   const refetchInterval = useAutoRefresh({ checkPendingRuns: true });
-  const { data, isLoading } = usePoolServiceGetPools(undefined, undefined, {
-    refetchInterval,
-  });
+
   const { data: authLinks } = useAuthLinksServiceGetAuthMenus();
   const hasPoolsAccess = authLinks?.authorized_menu_items.includes("Pools");
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx:36]: I wonder if we should also use this and return undefined before we even try to fetch anything.

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/Dashboard/PoolSummary/PoolSummary.tsx:36]: I think those serve different purpose. This is to display the link to the 'list pools' page, which is similar to show the 'menu item' for pools in a sense. But different from having actual 'read pools' permission.

We could revisit indeed, it's a little bit confusing in a sense.

**Review by pierrejeambrun — APPROVED** [review]
LGTM, thanks.

Tested and working as expected.

**Comment by pierrejeambrun** [comment]
Manual backport https://github.com/apache/airflow/pull/56626
