### PR TITLE
fix(ui): handle pools with unlimited (-1) slots in UI components

### LINKED ISSUE #61115: API - UI Handle pools with "-1" infinity slots.
### Body

The Pool db models accepts "-1" to specify unlimited slots on a pool. 

If we currently try to do that on the API side, it will error and result in a 500. 

This issue is to fix this behavior so the API can actually serialize and return pools with `-1/infinity` specified as slots. (same for create and patch).

Then when the backend returns `-1` or `infinity` for those slots, update the UI to take it into account in the chats. (PoolSummary, PoolBar). (infinity should take over the graph)

### Committer

- [x] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### PR DESCRIPTION
**Pull request by antonio-mello-ai**
## Summary
closes: #61115

Fixes the remaining UI portion of #61115. The backend fix was already merged in #61140.

When a pool has `slots` set to `-1` (unlimited), the UI components now properly handle this case:

- **PoolBar.tsx**: Detects unlimited pools and renders the open slots segment with `∞` symbol instead of computing broken flex ratios from dividing by `-1`
- **PoolBarCard.tsx**: Displays `∞` instead of `-1` in the pool card header (e.g., `my_pool (∞ Slots)`)
- **PoolSummary.tsx**: Correctly aggregates slot counts in the dashboard when any pool is unlimited — avoids corrupting the total by adding `-1`
- **PoolForm.tsx**: Sets `min={-1}` on the slots input and adds a helper text ("Use -1 for unlimited slots.") so users understand the convention
- **admin.json (en)**: Added `slotsHelperText` i18n key

## Testing

1. Create a pool with `-1` slots via the API
2. Navigate to the Pools page — the pool card should show `∞ Slots` with a properly rendered bar
3. Navigate to the Dashboard — the Pool Summary should aggregate correctly
4. Edit a pool — the form should allow `-1` with helper text

Closes #61115

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/components/PoolBar.tsx [hunk 1]
```diff
@@ -67,7 +71,14 @@ export const PoolBar = ({
...
           .map((slot) => {
-            const flexValue = slot.slotValue / totalSlots || 0;
+            const usedSlots = preparedSlots
+              .filter((s) => barSlots.includes(s.slotType) && s.slotValue > 0 && s.slotType !== "open")
+              .reduce((sum, s) => sum + s.slotValue, 0);
+            const flexValue = isUnlimited
+              ? slot.slotType === "open"
+                ? Math.max(1, usedSlots) // open takes at least as much space as all used slots combined
+                : slot.slotValue
+              : slot.slotValue / totalSlots || 0;
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/components/PoolBar.tsx]: This piece is weird. Why don't we just re-use `slot`,  which is already `preparedSlots` but filtered. We just need to further filter on the `open`, but starting again from `preparedSlots` and dupliacting the filters is confusing.

File: airflow-core/src/airflow/ui/src/components/PoolBar.tsx [hunk 2]
```diff
@@ -67,7 +71,14 @@ export const PoolBar = ({
         {preparedSlots
           .filter((slot) => barSlots.includes(slot.slotType) && slot.slotValue > 0)
           .map((slot) => {
-            const flexValue = slot.slotValue / totalSlots || 0;
+            const usedSlots = preparedSlots
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/components/PoolBar.tsx]: This 'usedSlots' is a constant, it doesn't need to be re-computed in each '.map` iteration and can probably be taken out of the loop.

**Review by pierrejeambrun — COMMENTED** [review]
Overall looking good. Thanks for the PR this needs a few adjustment / simplification but working as expected. And CI need fixing, some eslint errors.

File: airflow-core/src/airflow/ui/src/components/PoolBar.tsx (hunk 1 above)
Comment (antonio-mello-ai) [reply airflow-core/src/airflow/ui/src/components/PoolBar.tsx]: Addressed in the second commit. I extracted `displayedSlots` before the JSX return — it applies the same filter once, and `usedSlots` is computed from that filtered list (just excluding `open`). No more re-filtering from `preparedSlots`.

File: airflow-core/src/airflow/ui/src/components/PoolBar.tsx (hunk 2 above)
Comment (antonio-mello-ai) [reply airflow-core/src/airflow/ui/src/components/PoolBar.tsx]: Done — moved it out of the `.map()` in the second commit. Both `displayedSlots` and `usedSlots` are now computed once before the JSX return.

**Review by pierrejeambrun — APPROVED** [review]

**Comment by antonio-mello-ai** [comment]
@eladkal The static check failure (`ts-compile-lint-ui`) appears to be a flake on `main` itself — the latest main CI run also shows failures. Our PR only touches Pool UI components and doesn't affect the eslint/tsc pipeline.

Happy to rebase if needed once main is green again.

**Review by pierrejeambrun — COMMENTED** [review]
@antonio-mello-ai It's not flaky it's failing because of (in PoolBar component)
```
 const usedSlots = displayedSlots
    .filter((s) => s.slotType !== "open")
    .reduce((sum, s) => sum + s.slotValue, 0);
```

Identifier "s" is too small and not descriptive enough.

Do you mind fixing this so we can merge it.

**Review by pierrejeambrun — APPROVED** [review]

**Review by pierrejeambrun — COMMENTED** [review]
There are a few more linting / typing error.

You can run the static check locally. I recommend you install prek and setup the pre-commit hooks so that you will have those checks run locally before pushing your code. More information in our doc `airflow/contributing-docs/08_static_code_checks.rst`

**Review by choo121600 — APPROVED** [review]
Overall looks good to me :)
