### PR TITLE
Store user-adjusted grid width and fix logs height

### LINKED ISSUE #27512: Resizable grid view components
### Description

~1. Ability to change change the split ratio of the grid section and the task details section.~  - already done in #27273 
resizable_horizontal

2. Ability for the log window to be resized.
resizable_vertical

3. Would love if the choices stuck between reloads as well.

### Use case/motivation

I love the new grid view and use it day to day to check logs quickly. It would be easier to do so without having to scroll within the text box if you could resize the grid view to accommodate a larger view of the logs.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by bbovenzi**
When a user manually adjusts the width of the grid + details panel, save the width in localstorage so that is persists across reloads.

Also, make the height of the logs adjust to the size of the browser window.

Closes: #27512

Before:
Screen Shot 2022-11-08 at 10 21 42 AM

After:
Screen Shot 2022-11-08 at 10 21 19 AM

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

File: airflow/www/static/js/dag/Main.tsx [hunk 1]
```diff
@@ -62,6 +64,9 @@ const Main = () => {
     onStatusHover.cancel();
   };
 
+  const gridWidth = localStorage.getItem(`grid-width-${dagId}`) || undefined;
+  const saveWidth = debounce((w) => localStorage.setItem(`grid-width-${dagId}`, w));
```
Comment (pierrejeambrun) [inline airflow/www/static/js/dag/Main.tsx]: Default value for `debounce` is 0 ms (~ no debounce). We should specify a value:
```suggestion
  const saveWidth = debounce((w) => localStorage.setItem(`grid-width-${dagId}`, w), localStorageDelay);
```

I tried that locally, but this change is not enough => then the function is only triggered when we stop resizing. (not during resizing, which could be great if this was expected :joy: ) Also, maybe those functions should be defined outside of the component. I don't think they should change between renders, or should be bound to the component.

File: airflow/www/static/js/dag/Main.tsx [hunk 2]
```diff
@@ -77,9 +82,11 @@ const Main = () => {
   const resize = useCallback((e: MouseEvent) => {
     const gridEl = gridRef.current;
     if (gridEl && e.x > minPanelWidth && e.x < window.innerWidth - minPanelWidth) {
-      gridEl.style.width = `${e.x}px`;
+      const width = `${e.x}px`;
+      gridEl.style.width = width;
+      saveWidth(width);
     }
-  }, [gridRef]);
+  }, [gridRef, saveWidth]);
```
Comment (pierrejeambrun) [inline airflow/www/static/js/dag/Main.tsx]: yep savewidth could be defined outside of the component. I think debounce returns a new function on each render, so this will trigger on each render, making the calledback useless

**Review by pierrejeambrun — COMMENTED** [review]
On the first render, if the logs are 'bigger' than the space available for the logs component I get the UI cut off:
image.


Clicking on 'details' and back to 'logs' fixes it:
image

**Review by pierrejeambrun — APPROVED** [review]
LGTM. Just the changes to the `configure-aws-credentials` submodule that I am not sure about

**Comment by jyotsa09** [comment]
Hi @bbovenzi logs are not visible on UI for some tasks(dynamic task is one of them.)

**Comment by jyotsa09** [comment]
yes @bbovenzi

**Comment by bbovenzi** [comment]
@jyotsa09 what operating system and browser are you using? and there are no network errors?
