### PR TITLE
fix: corrects issues with edge rendering on the graph view

### LINKED ISSUE #35301: New Graph UI seems to struggle with task-to-task dependencies in nested task groups
### Apache Airflow version

2.7.2

### What happened

When rendering task-to-task dependencies between tasks that are buried into nested task groups, the UI tends to draw the relationships and node spacing in unusual ways.

image

image

image

### What you think should happen instead

The UI should render the graph consistently, regardless of what level you have drilled into the task groups.

### How to reproduce

Run this test code to reproduce the issue:

```
from airflow.decorators import dag, task, task_group
import pendulum
from typing import List, Dict
from airflow.models.baseoperator import BaseOperator

_all_tasks: Dict[str, List[BaseOperator]]={}

@dag(
    schedule=None, 
    start_date=pendulum.datetime(2023,1,1),
)
def test_dag():

    def _generate_task_group_callable(group_id, tasks):
        @task_group(group_id=group_id)
        def _task_group():
            [t() for t in tasks]
        return _task_group

    def _generate_task_callable(task_id, task_set):
        def _generate():
            @task(task_id=task_id)
            def _task():
                pass

            if _all_tasks.get(task_set, None) == None:
                _all_tasks[task_set]=list()
            
            _all_tasks[task_set].append(_task())
        return _generate

    _set_callables=list()
    for _set in range(0,2):
        _set_id=f"set_{_set}"
        _group_callables_a=list()
        for _nga in range(0,3):
            _nga_id=f"group_{_nga}"
            _group_callables_b=list()
            for _ngb in range(0,5):
                _ngb_id=f"group_{_ngb}"
                _task_callables=list()
                for _task in range(0,10):
                    _task_id=f"task_{_task}"
                    _callable=_generate_task_callable(_task_id, _set_id)
                    _task_callables.append(_callable)
                _group_callable_inner=_generate_task_group_callable(_ngb_id,_task_callables)
                _group_callables_b.append(_group_callable_inner)
            _group_callable_outer=_generate_task_group_callable(_nga_id, _group_callables_b)
            _group_callables_a.append(_group_callable_outer)
        _set_callable=_generate_task_group_callable(_set_id, _group_callables_a)
        _set_callables.append(_set_callable)
    
    [_s() for _s in _set_callables]

    for i in range(0,len(_all_tasks['set_0'])):
        _all_tasks['set_0'][i] >> _all_tasks['set_1'][i]
        
test_dag()
```

### Operating System

Debian GNU/Linux 11 (bullseye) -- apache/airflow:slim-2.7.2-python3.10 container

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.7.2
apache-airflow-providers-ftp==3.5.2
apache-airflow-providers-hashicorp==3.5.0
apache-airflow-providers-http==4.5.2
apache-airflow-providers-imap==3.3.2
apache-airflow-providers-sqlite==3.4.3

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else

if the grid is is filtered, it has been observed that the graph renders properly in some scenarios.  Doing task-group-to-task-group relationships sometimes renders properly, as well.  

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by codecae**
closes: #35301 

The graph UI has issues rendering edges between dependent tasks nested in task groups.  Edges render with excessive bends in various directions instead of directly between tasks and their parents task groups as they are collapsed and expanded.  They also tend to render vertically off center at node borders.  This PR addresses this edge rendering issue.

Example code that reproduces the issue:
```
from typing import Dict, List
import pendulum
from airflow.sdk import BaseOperator, dag, task, task_group
@dag(
    schedule=None,
    start_date=pendulum.datetime(2023, 1, 1),
)
def test_dag():
    _all_tasks: Dict[str, List[BaseOperator]] = {}
    def _generate_task_group_callable(group_id, tasks):
        @task_group(group_id=group_id)
        def _task_group():
            [t() for t in tasks]
        return _task_group
    def _generate_task_callable(task_id, task_set):
        def _generate():
            @task(task_id=task_id)
            def _task():
                pass
            if _all_tasks.get(task_set) is None:
                _all_tasks[task_set] = []
            _all_tasks[task_set].append(_task())
        return _generate
    _set_callables = []
    for _set in range(0, 2):
        _set_id = f"set_{_set}"
        _group_callables_a = []
        for _nga in range(0, 1):
            _nga_id = f"group_{_nga}"
            _group_callables_b = []
            for _ngb in range(0, 3):
                _ngb_id = f"group_{_ngb}"
                _task_callables = []
                for _task in range(0, 10):
                    _task_id = f"task_{_task}"
                    _callable = _generate_task_callable(_task_id, _set_id)
                    _task_callables.append(_callable)
                _group_callable_inner = _generate_task_group_callable(_ngb_id, _task_callables)
                _group_callables_b.append(_group_callable_inner)
            _group_callable_outer = _generate_task_group_callable(_nga_id, _group_callables_b)
            _group_callables_a.append(_group_callable_outer)
        _set_callable = _generate_task_group_callable(_set_id, _group_callables_a)
        _set_callables.append(_set_callable)
    [_s() for _s in _set_callables]
    for i in range(0, len(_all_tasks["set_0"])):
        _all_tasks["set_0"][i] >> _all_tasks["set_1"][i]
test_dag()
```
**Rendering issue examples:**
image
image
image
image
image

**With this fix:**
image
image
image
image
image
image

---

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/components/Graph/useGraphLayout.ts [hunk 1]
```diff
@@ -210,7 +210,20 @@ const generateElkGraph = ({
...
+    const edgeKey = `${edge.source_id}-${edge.target_id}`;
+
+    if (!edgeMap.has(edgeKey)) {
+      edgeMap.set(edgeKey, edge);
+    }
+  });
+
+  // Convert back to array and create formatted edges
+  const deduplicatedEdges = [...edgeMap.values()];
+  const edges = deduplicatedEdges.map((fe) => formatElkEdge(fe, font));
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/components/Graph/useGraphLayout.ts]: The backend shouldn't return duplicated edges like this. We probably should fix it there.

**Comment by pierrejeambrun** [comment]
Thanks for the PR, indeed that need fixing.

File: airflow-core/src/airflow/ui/src/components/Graph/useGraphLayout.ts (hunk 1 above)
Comment (codecae) [reply airflow-core/src/airflow/ui/src/components/Graph/useGraphLayout.ts]: The duplication is created as a byproduct of changing source and targets from tasks to parent task groups when task groups are collapsed.  There end up being duplicate edges as that transformation occurs.  This deduplication is handled on the front end when a user interacts with the UI.  If I recall, collapsing task groups doesn't create any backend requests, does it?

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/components/Graph/useGraphLayout.ts]: You're right, thanks.

**Review by pierrejeambrun — COMMENTED** [review]
Instead of doing another full pass on `filteredEdges` and creating another big list of edges with many duplicated, move this deduplication step directly in the `formatChildNode` function. This will allow to not insert duplicated edges at all in the first place, removing the need for an extra step in the process.

**Comment by codecae** [comment]
> Instead of doing another full pass on `filteredEdges` and creating another big list of edges with many duplicated, move this deduplication step directly in the `formatChildNode` function. This will allow to not insert duplicated edges at all in the first place, removing the need for an extra step in the process.

The deduplication logic has been moved to `formatChildNode` with reduced complexity.

**Review by pierrejeambrun — APPROVED** [review]
Thanks, looking good!
