### PR TITLE
Fix rendering of dagRunTimeout

### LINKED ISSUE #32442: Dag run timeout with timedelta value is rendered as [object object] in UI
### Apache Airflow version

main (development)

### What happened

Dag run timeout with timedelta value is rendered as [object object] in UI. It seems the data is fetched and string is used to render the value. timedelta is handled for schedule_interval which should also be done here.

image

### What you think should happen instead

timedelta should be handled similar to how it's done in scheduleInterval value here.

https://github.com/apache/airflow/blob/e70bee00cd12ecf1462485a747c0e3296ef7d48c/airflow/www/static/js/dag/details/Dag.tsx#L278C2-L293

### How to reproduce

1. Create a dag with dag_run_timeout as timedelta value.
2. Visit the dag details tab in grid view to check dag_run_timeout

### Operating System

Ubuntu

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by sanjurm16**
This resolves the below issue:
closes: #32442 
The dag details page originally rendered the timedelta value as string. Causing the value of dagRunTImeout to be rendered as [object Object]. This change will handle the rendering of dagRunTimeout separately like scheduleInterval

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

File: airflow/www/static/js/dag/details/Dag.tsx [hunk 1]
```diff
@@ -291,6 +292,19 @@ const Dag = () => {
...
                 </Td>
               </Tr>
+              <Tr>
+                <Td>Dag run timeout</Td>
+                <Td>
+                  {dagDetailsData.dagRunTimeout?.type === undefined ? (
+                    <Text>null</Text>
+                  ) : (
+                    // for TimeDelta and RelativeDelta
+                    <ViewScheduleInterval
```
Comment (tirkarthi) [inline airflow/www/static/js/dag/details/Dag.tsx]: `ViewScheduleInterval` couples this component with dag's schedule interval. Maybe this could be refactored/renamed to `ViewTimeDelta` component to be used in schedule interval and dag run timeout to render timedelta values?

Comment (sanjurm16) [reply airflow/www/static/js/dag/details/Dag.tsx]: Makes sense. Let me take a look and make the change. Cheers.

**Review by bbovenzi — APPROVED** [review]

**Review by pierrejeambrun — APPROVED** [review]
