### PR TITLE
Show dag run duration in grid tooltip

### LINKED ISSUE #65786: Dag run duration is missing from the tooltip
### Under which category would you file this issue?

Airflow Core

### Apache Airflow version

3.2.1

### What happened and how to reproduce it?

DAG run duration is missing from the tooltip.

* 3.2.1

   Image

* 2.11.2

   Image

### What you think should happen instead?

The tooltip should show duration.

### Operating System

LM 21.3 with docker python:3.12-slim-bookworm

### Deployment

Docker-Compose

### Apache Airflow Provider(s)

_No response_

### Versions of Apache Airflow Providers

_No response_

### Official Helm Chart version

Not Applicable

### Kubernetes Version

_No response_

### Helm Chart configuration

_No response_

### Docker Image customizations

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by PrithviBadiga**
Adds DAG run duration to the grid tooltip in the Dag details view.

Updates:
- pass `run.duration` from the grid bar into `GridButton`
- show duration in the grid tooltip alongside run ID and state
- add a focused UI test for the tooltip content

Verification:
- `corepack pnpm exec vitest run src/layouts/Details/Grid/GridButton.test.tsx`
- `corepack pnpm exec eslint src/layouts/Details/Grid/GridButton.tsx src/layouts/Details/Grid/GridButton.test.tsx src/layouts/Details/Grid/Bar.tsx`
- `corepack pnpm exec prettier --check src/layouts/Details/Grid/GridButton.tsx src/layouts/Details/Grid/GridButton.test.tsx src/layouts/Details/Grid/Bar.tsx`

This closes: #65786

### CODE REVIEW

**Comment by zachliu** [comment]
@PrithviBadiga lol you beat me to it :joy:

File: airflow-core/src/airflow/ui/src/layouts/Details/Grid/GridButton.tsx [hunk 1]
```diff
@@ -52,6 +55,8 @@ export const GridButton = ({
       <br />
       {translate("common:runId")}: {runId}
       <br />
+      {translate("duration")}: {renderDuration(duration)}
+      <br />
```
Comment (zachliu) [inline airflow-core/src/airflow/ui/src/layouts/Details/Grid/GridButton.tsx]: shouldn't it be added after the "state"?

Comment (PrithviBadiga) [reply airflow-core/src/airflow/ui/src/layouts/Details/Grid/GridButton.tsx]: Good point. I updated the tooltip so duration is shown after state.

**Comment by bbovenzi** [comment]
Mind including a screenshot?

**Comment by zachliu** [comment]
before:


after:


@bbovenzi

**Review by bbovenzi — APPROVED** [review]
