### PR TITLE
No grid auto-refresh for backfill dag runs

### LINKED ISSUE #24844: grid_data api keep refreshing  when backfill DAG runs
### Apache Airflow version

2.3.2 (latest released)

### What happened

image

### What you think should happen instead

_No response_

### How to reproduce

_No response_

### Operating System

186-Ubuntu 

### Versions of Apache Airflow Providers

2.3.2

### Deployment

Other

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by yingxuanwangxuan**
Don't run auto-refresh for backfill dag runs.
Closes: #24844 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by bbovenzi** [comment]
Issue: https://github.com/apache/airflow/issues/24844

Not sure about the CI failure. I'd say rebase the branch and see if it persists.

**Review by bbovenzi — APPROVED** [review]

File: airflow/www/static/js/api/useGridData.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ const emptyGridData: GridData = {
   },
 };
 
-export const areActiveRuns = (runs: DagRun[] = []) => runs.filter((run) => ['queued', 'running', 'scheduled'].includes(run.state)).length > 0;
+export const areActiveRuns = (runs: DagRun[] = []) => runs.filter((run) => ['manual', 'manual'].includes(run.runType)).filter((run) => ['queued', 'running', 'scheduled'].includes(run.state)).length > 0;
```
Comment (cloventt) [inline airflow/www/static/js/api/useGridData.ts:52]: Surely this should be:
```python
export const areActiveRuns = (runs: DagRun[] = []) => runs.filter((run) => ['scheduled', 'manual'].includes(run.runType)).filter((run) => ['queued', 'running', 'scheduled'].includes(run.state)).length > 0;
```

Comment (yingxuanwangxuan) [reply airflow/www/static/js/api/useGridData.ts:52]: thanks for fix this.  @bbovenzi can you review it again?
