### PR TITLE
Redo the gantt chart

### LINKED ISSUE #56070: Explore rewriting Gantt view
### Body

We've had a lot of bugs with the gantt view built in chartjs. But its been hard to keep all the interactions in sync with the custom-built grid view. I think it's worth looking at custom building the gantt view to actually integrate into the grid view instead of just trying to force it.

### Committer

- [x] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### LINKED ISSUE #63727: Gantt view is not scrollable
### Apache Airflow version

3.1.8

### If "Other Airflow 3 version" selected, which one?

_No response_

### What happened?

Gantt view is not scrollable when there are many tasks that user needs to scroll and see all the tasks

https://github.com/user-attachments/assets/21bb1250-90f3-49c9-9e77-a5bde486ac09

### What you think should happen instead?

_No response_

### How to reproduce

Use the below Dag to reproduce the issue.
Trigger the Dag, exapnd all the task groups and notice task list is scrollable but not the gantt view.

```python
from airflow.sdk import DAG
from airflow.decorators import task
from airflow.providers.standard.operators.empty import EmptyOperator
from airflow.utils.task_group import TaskGroup
from datetime import datetime
from dataclasses import dataclass
from dataclasses_json import dataclass_json
from random import seed, randint


@dataclass_json
@dataclass
class Payload:

    seed: int
    a: str
    b: str
    c: str
    d: str

    def make(i):
        return Payload(
            seed=i, a=str(i) * 5, b=str(i) * 10, c=str(i) * 15, d=str(i) * 20
        )

    def transform(self):
        self.a = str(int(int(self.a) / 5))
        self.b = str(int(int(self.a) / 10))
        self.c = str(int(int(self.a) / 15))
        self.d = str(int(int(self.a) / 20))


@task
def mk_payloads(i):
    return [Payload.make(j).to_dict() for j in range(1, i)]


@task
def transform(_payload):
    payload = Payload.from_dict(_payload)
    payload.transform()
    return payload.to_dict()


@task
def check_transformed(_payload):
    payload: Payload = Payload.from_dict(_payload)
    orig = Payload.make(payload.seed)
    orig.transform()

    # same transformation made to same data
    # results should be same, otherwise something got lost along the way
    assert orig == payload


minmax_map_indices_per_lane = (5, 60)
lanes = 10


with DAG(
    dag_id="many_expand", schedule=None, start_date=datetime(1970, 1, 1), catchup=False,tags=["taskmap"]
) as dag:

    seed(42)  # be deterministic

    for i in range(lanes):
        with TaskGroup(group_id=f"lane{i+1}"):
            min_map, max_map = minmax_map_indices_per_lane
            mapped = randint(min_map, max_map)
            check_transformed.expand(
                _payload=transform.expand(_payload=mk_payloads(mapped))
            )

``` 

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by bbovenzi**
Replace the chartjs gantt chart with a custom implementation that is fully integrated with our grid view. Such as:

- Virtualized gantt chart & synced scrolling
- Same colors and iconography
- No animations between changing views

Closes: https://github.com/apache/airflow/issues/63727
Closes: https://github.com/apache/airflow/issues/56070

Also, added a new Gantt button next to the grid and graph buttons to make it easier to find.

Screenshot 2026-03-27 at 4 37 17 PM

Mar-27-2026 16-40-00

Multiple tries with a queued time:
Screenshot 2026-04-13 at 2 33 11 PM

---

##### Was generative AI tooling used to co-author this PR?

- [x] Yes Claude Sonnet 4.6

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments). You can add this file in a follow-up commit after the PR is created so you know the PR number.

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts [hunk 1]
```diff
@@ -106,74 +112,127 @@ export const transformGanttData = ({
...
+            // The same predicate drives both segment creation and tooltip field inclusion.
+            const willShowQueued =
+              queuedMs !== undefined && (startMs === undefined || startMs - queuedMs >= 1000);
+            const willShowScheduled =
+              scheduledMs !== undefined &&
+              (startMs === undefined ||
+                (!willShowQueued && startMs - scheduledMs >= 1000) ||
+                (willShowQueued && queuedMs - scheduledMs >= 1000));
+
+            const tryWhenForTooltip = {
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts]: nit: I think its fine like this but ideally this should be a percentage of the global window span. (Basically if we're looking at a 3hour long dag run, even a delay of a few seconds can still not be worth to render)

**Review by pierrejeambrun — APPROVED** [review]
Super cool 🎉 ! Looks nice, working as expected

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts (hunk 1 above)
Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/layouts/Details/Gantt/utils.ts]: Yes, I had that in a previous iteration. Let me put it back.
