### PR TITLE
Fix multi-line drag selection in task log view

### LINKED ISSUE #55879: Drag-selecting task logs behaves oddly
### Body

If you drag select over multiple lines in the task log view, instead of behaving normally, as soon as you drag down it "restarts" the selection at the top of the logs, selecting everything from the the top.

(Also, the selection color in light mode is nigh-on-invisible)

https://github.com/user-attachments/assets/76d7fada-a829-4d5d-ab97-257735ffb013

### Committer

- [x] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### PR DESCRIPTION
**Pull request by Brunda10**
Closes : #55879

Previously, dragging across multiple lines in the task log view caused the selection to jump back to the top of the logs, making it impossible to select multiple lines reliably. This was caused by the combination of `position: absolute` and `transform: translateY()` on virtualized rows.

This PR fixes the issue by:

- Removing the `transform` property and relying solely on `top` for positioning.
- Ensuring each row remains virtualized for performance.
- Adjusted selection CSS for better visibility 

Users can now drag-select multiple lines smoothly, improving log readability and overall UX.

[Screencast from 2025-09-29 16-15-40.webm](https://github.com/user-attachments/assets/4a353bbe-75a4-4047-8395-bf8f732ab13c)

### CODE REVIEW

**Review by jscheffl — APPROVED** [review]
Oh, thanks! Much smoother and better to select text now.
Seems some other PR merged and made a conflict - can you resolve and push a change?

Before merge would request another pair of eyes to double check that solution is the best approach as my CSS knowledge is limited.

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/TaskLogContent.tsx [hunk 1]
```diff
@@ -116,7 +116,7 @@ export const TaskLogContent = ({ error, isLoading, logError, parsedLogs, wrap }:
       <Code
         css={{
           "& *::selection": {
-            bg: "brand.subtle",
+            bg: "gray.emphasized",
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/TaskInstance/Logs/TaskLogContent.tsx]: Looks good. We just need to remove this change and rebase

**Review by bbovenzi — APPROVED** [review]

**Comment by bbovenzi** [comment]
CI failures are unrelated
