### PR TITLE
Fix graph view not auto-refreshing task states during DAG run

### LINKED ISSUE #65517: Graph does not seem to refresh properly in 3.2.1rc2
### Under which category would you file this issue?

Airflow Core

### Apache Airflow version

3.2.1rc2

### What happened and how to reproduce it?

It seems that graph view does not refresh properly while tasks are running.

It's 100% reproducible for me in breeze:

1. Start airflow

```bash
breeze start-airflow --use-airflow-version 3.2.1rc2 --allow-pre-releases --load-default-connections --load-example-dags  --backend postgres
```

2. Go to "example_complex"
3. Trigger it
4. All the graph tasks change status to "no status" (expected)
5. After a while tasks on the right change their status to running and complete
6. At the same time Graph does not refresh - all tasks stay in "no status"
7. Unless you click on some tasks or refresh the window - then graph refreshes - but does not continue to refresh after (you need to click any task again) 

I recorded a movie showing it (Attached).

https://drive.google.com/file/d/1RlgRbcD0AWBuuB43J2ZOjtvPFm4IA8Lo/view?usp=sharing

### What you think should happen instead?

Graph should refresh while tasks are changing their state.

### Operating System

Mac OS Tahoe 26.3.1 (25D2128)

### Deployment

Other Docker-based deployment

### Apache Airflow Provider(s)

_No response_

### Versions of Apache Airflow Providers

_No response_

### Official Helm Chart version

Not Applicable

### Kubernetes Version

_No response_

### Helm Chart configuration

_No response_

### Docker Image customizations

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by vatsrahul1001**
Graph view does not refresh task statuses while tasks are running

Before:
image

After:
image

### Root cause
`Graph.tsx` calls `useGridTiSummariesStream` without the `states` prop:
```ts
// Before
useGridTiSummariesStream({ dagId, runIds: runId ? [runId] : [] });
```

Inside useGridTiSummariesStream, the auto-refresh interval only starts when hasActiveRuns is true:

const hasActiveRuns = states?.some((state) => isStatePending(state)) ?? false;
Without states, this is always false → the setInterval never fires → after the initial stream completes the graph freezes.

Grid.tsx already passes states correctly — Graph was missing it.

Fix
Fetch the current dag run state via useDagRunServiceGetDagRun (already cached by React Query — no extra network cost) and pass it as states:

// After
```
const { data: dagRun } = useDagRunServiceGetDagRun(
  { dagId, dagRunId: runId },
  undefined,
  { enabled: Boolean(runId) },
);
useGridTiSummariesStream({
  dagId,
  runIds: runId ? [runId] : [],
  states: dagRun ? [dagRun.state] : undefined,
});
```
Tests
Added Graph.test.tsx with two cases:

Verifies states is forwarded when a runId is present and the run is active
Verifies states is undefined when no runId is present
* closes: https://github.com/apache/airflow/issues/65517

-->

---

##### Was generative AI tooling used to co-author this PR?

- [X] Yes (please specify the tool below)

Generated-by: [Claude following [the guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#gen-ai-assisted-contributions)

---

* Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information. Note: commit author/co-author name and email in commits become permanently public when merged.
* For fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
* When adding dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
* For significant user-facing changes create newsfragment: `{pr_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments). You can add this file in a follow-up commit after the PR is created so you know the PR number.

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/layouts/Details/Graph/Graph.tsx [hunk 1]
```diff
@@ -134,7 +134,15 @@ export const Graph = () => {
...
 
-  const { summariesByRunId } = useGridTiSummariesStream({ dagId, runIds: runId ? [runId] : [] });
+  const { data: dagRun } = useDagRunServiceGetDagRun({ dagId, dagRunId: runId }, undefined, {
+    enabled: Boolean(runId),
+  });
+
+  const { summariesByRunId } = useGridTiSummariesStream({
+    dagId,
+    runIds: runId ? [runId] : [],
+    states: dagRun ? [dagRun.state] : undefined,
```
Comment (phanikumv) [inline airflow-core/src/airflow/ui/src/layouts/Details/Graph/Graph.tsx:144]: This ternary has three reachable states, but the test suite only covers two of them:

| Scenario | `runId` | `dagRun` | `states` result | Tested? |
|---|---|---|---|---|
| Run active | ✓ | resolved object | `["running"]` | ✓ |
| No run selected | ✗ | `undefined` (query disabled) | `undefined` | ✓ |
| **Run selected, still loading** | **✓** | **`undefined` (in-flight)** | **`undefined`** | **✗** |

The third case — `runId` present but `useDagRunServiceGetDagRun` not yet resolved — also produces `states: undefined`, but for a different reason than the no-runId test. It would be good to cover it explicitly:

```ts
it('passes undefined states while dag run is loading', () => {
  mockParams = { dagId: 'test_dag', runId: 'run_1' };
  vi.mocked(useDagRunServiceGetDagRun).mockReturnValue({
    data: undefined,
    isLoading: true,
  } as ReturnType<typeof useDagRunServiceGetDagRun>);

  render(<Graph />, { wrapper: Wrapper });

  expect(vi.mocked(useGridTiSummariesStream)).toHaveBeenCalledWith(
    expect.objectContaining({
      runIds: ['run_1'],
      states: undefined,
    }),
  );
});
```

During this loading window `hasActiveRuns` is `false`, so the auto-refresh timer does not start yet. That is correct behaviour, but making it an explicit test case documents the intent and guards against a future refactor that accidentally passes a stale or partial value instead.

Comment (vatsrahul1001) [reply airflow-core/src/airflow/ui/src/layouts/Details/Graph/Graph.tsx:144]: Thanks @phanikumv added third case

File: airflow-core/src/airflow/ui/src/layouts/Details/Graph/Graph.test.tsx [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+vi.mock("@xyflow/react", async () => {
+  const actual = await vi.importActual("@xyflow/react");
+
+  return {
+    ...actual,
+    ReactFlow: vi.fn(() => null),
+    useReactFlow: vi.fn(() => ({ fitView: vi.fn(), getZoom: vi.fn() })),
+  };
+});
+
```
Comment (phanikumv) [inline airflow-core/src/airflow/ui/src/layouts/Details/Graph/Graph.test.tsx:74]: Top-level `await import()` is fragile with Vitest's ESM mock hoisting. `vi.mock()` calls are hoisted to the top of the file at transform time, but `await import()` evaluates after that — if the module graph shifts this can silently break (mocks not applied in time).

Every other test file in this repo uses a regular top-level import + `vi.mocked()` inline, e.g.:

```ts
// at the top of the file, alongside the other imports
import { useDagRunServiceGetDagRun } from "openapi/queries";
import { useGridTiSummariesStream } from "src/queries/useGridTISummaries.ts";
```

Then in each test:
```ts
vi.mocked(useDagRunServiceGetDagRun).mockReturnValue({ ... });
```

This aligns with the rest of the suite and avoids the hoisting edge case entirely.

**Review by pierrejeambrun — APPROVED** [review]
LGTM, tested and working as expected thanks.
