### PR TITLE
Fix Toggle Wrap on DAG code page

### LINKED ISSUE #17047: Toggle Wrap on DAG code page is broken
**Apache Airflow version**: `apache/airflow:2.1.2-python3.9` and `2.1.0-python3.8`

**Environment**:

- **Cloud provider or hardware configuration**: Docker for Windows, AWS ECS
- **OS** (e.g. from /etc/os-release): Windows 10, AWS ECS Fargate
- **Install tools**: docker compose, ECS
- **Others**: Web browsers: tested this on Chrome and Brave.

**What happened**:

The `Toggle Wrap` button on the DAG code page is not working.

**What you expected to happen**:

It should toggle between wrapped/unwrapped code blocks.

**How to reproduce it**:

1. Spin up an airflow environment using the official docker compose file with DAG examples enabled.
2. Open code page for any DAG that uses the [START xyz] [END xyz] blocks in its source code.
3. Click on the `Toggle Wrap` button in the top right corner of the code.

airflow@chrome

**Additional remarks**

This feature seems to be working totally fine on the TI logs, and by looking at the code they are re-using the same function.

### PR DESCRIPTION
**Pull request by PApostol**
Closes #17047

Root of issue: [ToggleWrap](https://github.com/apache/airflow/blob/main/airflow/www/templates/airflow/dag_code.html#L32) function was undefined.

After applying the changes (see line 31):

- Before clicking `Toggle Wrap` :
before

- After clicking `Toggle Wrap` :
after

### CODE REVIEW

File: airflow/www/static/js/dag_code.js [hunk 1]
```diff
@@ -17,13 +17,10 @@
  * under the License.
  */
 
-/* global $ */
+/* global window, $ */
 
-import getMetaValue from './meta_value';
-
-const isWrapped = getMetaValue('wrapped');
```
Comment (bbovenzi) [inline airflow/www/static/js/dag_code.js:24]: Let's also get rid of

```
{% block head_meta %}
  {{ super() }}
  <meta name="wrapped" content="{{ wrapped }}">
{% endblock %}
```

in `dag_code.html` if we're not using it at all anymore.

**Review by bbovenzi — CHANGES_REQUESTED** [review]

File: airflow/www/static/js/dag_code.js (hunk 1 above)
Comment (PApostol) [reply airflow/www/static/js/dag_code.js:24]: I have updated the PR with the suggested change.

**Review by bbovenzi — APPROVED** [review]
nice work!

File: airflow/www/templates/airflow/dag_code.html [hunk 2]
```diff
@@ -21,11 +21,6 @@
 
 {% block page_title %}{{ dag.dag_id }} - Code - {{ appbuilder.app_name }}{% endblock %}
 
-{% block head_meta %}
-  {{ super() }}
-  <meta name="wrapped" content="{{ wrapped }}">
-{% endblock %}
```
Comment (uranusjr) [inline airflow/www/templates/airflow/dag_code.html]: I think this needs to be added back?

Comment (PApostol) [reply airflow/www/templates/airflow/dag_code.html]: Yep, this is done now.

File: airflow/www/static/js/dag_code.js [hunk 3]
```diff
@@ -17,13 +17,19 @@
...
 import getMetaValue from './meta_value';
 
+function toggleWrap() {
+  $('.code pre').toggleClass('wrap');
+}
+
 const isWrapped = getMetaValue('wrapped');
 
 // pygments generates the HTML so set wrap toggle via js
 if (isWrapped) {
```
Comment (bbovenzi) [inline airflow/www/static/js/dag_code.js]: `isWrapped` is not being translated to a js boolean correctly. Would you mind changing this line?
```suggestion
if (isWrapped === 'True') {
```

**Review by bbovenzi — CHANGES_REQUESTED** [review]

**Review by bbovenzi — APPROVED** [review]

**Comment by PApostol** [comment]
Hi, is there anything else required for this PR?
