### PR TITLE
Fix reversed PanelResizeHandle drag direction after restoring from autoSaveId

### LINKED ISSUE #53145: PanelResizeHandle drag direction reversed after refresh
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

PanelResizeHandle drag direction reversed after refresh

### What you think should happen instead?

_No response_

### How to reproduce

https://github.com/user-attachments/assets/21588a7b-1037-4b09-9f9b-ca55f6d3fe0a

### Operating System

mac os

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by choo121600**
## Problem
- **Initial state**: Panel resize drag works correctly 
- **After refresh**: Drag direction becomes reversed (dragging left expands right panel)
- **Affected views**: Graph and Grid DAG views, Asset view.
- **Root cause**: Internal state conflict in `react-resizable-panels` library due to mismatch between stored panel sizes by `autoSaveId` and current UI direction (direction: LTR/RTL)
- autoSaveId only included dagId or assetId, missing direction info, causing state inconsistency and excessive storage entries

https://github.com/user-attachments/assets/5bfec26c-b7f5-4505-9243-7ac5ca12c0c7

## Solved
* Changed autoSaveId of PanelGroup to include direction info as `${dagView}-${direction}` (for DAG views) or `asset-${direction}` (for Asset view)
* Added explicit `dir` and React `key` props with direction values to ensure proper remount and layout restoration on LTR/RTL switching
* Reduced LocalStorage usage and provided a consistent user experience per direction
* Fixed drag direction reversal and layout corruption issues on direction change

https://github.com/user-attachments/assets/331cbc45-5520-4a24-a73f-fbeb467763b1

closes: https://github.com/apache/airflow/issues/53145

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx [hunk 1]
```diff
@@ -68,6 +76,61 @@ export const DetailsLayout = ({ children, error, isLoading, tabs }: Props) => {
...
+      if (cached !== null && cached !== "") {
+        const parsed: unknown = JSON.parse(cached);
+
+        if (isPanelSizes(parsed)) {
+          return parsed;
+        }
+      }
+    } catch {
+      // Failed to parse saved panel sizes - fallback to default
+    }
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx]: I don't think we can have a failure reeading that. And if we do, that's not normal and we might want to break there instead of silently returning anything.

File: airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx [hunk 2]
```diff
@@ -68,6 +76,61 @@ export const DetailsLayout = ({ children, error, isLoading, tabs }: Props) => {
...
+
+  const savePanelSizes = useCallback(
+    (sizes: Array<number>) => {
+      try {
+        const storageKey = `panel-${dagId}-${dagView}`;
+
+        sessionStorage.setItem(storageKey, JSON.stringify(sizes));
+      } catch {
+        // Failed to save panel sizes - continue silently
+      }
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx]: What are we trying to catch there? This shouldn't fail.

File: airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx [hunk 3]
```diff
@@ -68,6 +76,61 @@ export const DetailsLayout = ({ children, error, isLoading, tabs }: Props) => {
...
+
+    setCurrentSizes(newSizes);
+
+    setShowPanel(false);
+    const timer = setTimeout(() => {
+      setShowPanel(true);
+    }, PANEL_RESET_DELAY);
+
+    return () => clearTimeout(timer);
+  }, [dagView, dagId, getSavedSizes]);
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx]: Ideally we would like a solution without useEffect. Is there a way to do it differently ?

File: airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx [hunk 4]
```diff
@@ -44,6 +44,15 @@ import { Grid } from "./Grid";
...
 import { PanelButtons } from "./PanelButtons";
 
+const PANEL_RESET_DELAY = 10;
+const DEFAULT_GRAPH_SIZES = [70, 30] as const;
+const DEFAULT_GRID_SIZES = [20, 80] as const;
+
+type PanelSizes = readonly [number, number];
+
+const isPanelSizes = (value: unknown): value is PanelSizes =>
+  Array.isArray(value) && value.length === 2 && value.every((size) => typeof size === "number" && size > 0);
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx]: Why do we need that?

**Review by pierrejeambrun — COMMENTED** [review]
The current solution looks overly complicated. I think we need to rework it and remove the non necessary code.

**Comment by bbovenzi** [comment]
Ok after looking into this. If we specify `dir` on PanelGroup it should solve the problem except when switching between RTL and LTR languages. In that case I think we need to force a refresh of the DetailsLayout component. But thats a lesser bug, imo

Issue: https://github.com/bvaughn/react-resizable-panels/issues/446

**Comment by choo121600** [comment]
> Ok after looking into this. If we specify `dir` on PanelGroup it should solve the problem except when switching between RTL and LTR languages. In that case I think we need to force a refresh of the DetailsLayout component. But thats a lesser bug, imo

Wow, your solution is spot on!
I didn’t realize this issue was caused by LTR vs RTL!
Your fix is so much simpler than what I had in mind. Thanks a lot!

File: airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx (hunk 3 above)
Comment (choo121600) [reply airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx]: The panel size logic was more complex before because I didn’t realize it was an LTR/RTL issue.
Thanks to Bovenzi’s insight, I can remove the useEffect and simplify the code.

**Comment by choo121600** [comment]
I fixed the issue using LTR/RTL support as @bbovenzi suggested🙌
It works well now! you can see it in the screen recording below: 


https://github.com/user-attachments/assets/5dc9feef-6786-4828-b6bc-09091f442e47

**Review by pierrejeambrun — COMMENTED** [review]
It looks like the previous and the new approach implementation and intertwined there.

With some changes that are not really related to fixing the mentioned bug.

Can you please remove everything that is not required for solving the bug (and can be included in a different PR), it will make the review easier and also we will have a better time cherry picking this to the release branch.

File: airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx [hunk 5]
```diff
@@ -53,20 +56,29 @@ type Props = {
...
+    dagView === "graph" ? DEFAULT_GRAPH_SIZES : DEFAULT_GRID_SIZES;
+  const savedSizes = sessionStorage.getItem(storageKey);
+
+  if (savedSizes !== null) {
+    const parsed: unknown = JSON.parse(savedSizes);
+
+    if (Array.isArray(parsed) && parsed.length === 2) {
+      initialSizes = parsed as [number, number];
+    }
+  }
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx]: Don't think we need this anymore?

File: airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx [hunk 6]
```diff
@@ -88,101 +100,103 @@ export const DetailsLayout = ({ children, error, isLoading, tabs }: Props) => {
...
-                setDagView={setDagView}
-                setLimit={setLimit}
-              />
+        <PanelGroup
+          dir={direction}
+          direction="horizontal"
+          key={`${dagId}-${dagView}-${direction}`}
+          onLayout={(sizes) => {
+            sessionStorage.setItem(storageKey, JSON.stringify(sizes));
+          }}
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/layouts/Details/DetailsLayout.tsx]: Do we still want this?

**Comment by choo121600** [comment]
If we use autoSaveId, then the manual sessionStorage handling and the initialSizes logic become unnecessary.
Therefore, I revert to using autoSaveId as before, which should automatically handle panel size persistence correctly.

**Comment by choo121600** [comment]
With the current structure, if the number of Dags increase, there’s a risk that too many panel size entries will be stored in localStorage.

So, I’m wondering if including `dagId` in the autoSaveId is really the best approach.
Also, saving different panel sizes for each Dag might reduce consistency and cause confusion.
Therefore, managing autoSaveId using just the `${dagView}-${direction}` instead of `${dagId}-${dagView}-${direction}` might provide a more consistent user experience.
What do you think about this, @pierrejeambrun  and @bbovenzi ?

**Comment by choo121600** [comment]
I will also include the asset part in this PR since it has the same issue and can be fixed in the same way.

File: airflow-core/src/airflow/ui/src/pages/Asset/AssetLayout.tsx [hunk 7]
```diff
@@ -94,7 +95,12 @@ export const AssetLayout = () => {
       </HStack>
       <ProgressBar size="xs" visibility={Boolean(isLoading) ? "visible" : "hidden"} />
       <Box flex={1} minH={0}>
-        <PanelGroup autoSaveId={assetId} direction="horizontal">
+        <PanelGroup
+          autoSaveId={`${assetId}-${direction}`}
+          dir={direction}
+          direction="horizontal"
+          key={`${assetId}-${direction}`}
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/Asset/AssetLayout.tsx]: I don't think we need to update `autoSaveId` and `key` can just be left as `assetId`.

**Review by pierrejeambrun — COMMENTED** [review]
> Therefore, managing autoSaveId using just the ${dagView}-${direction} instead of ${dagId}-${dagView}-${direction} might provide a more consistent user experience.

+1 for this. Having a super fined grained setting per dag, per view, per direction is not necessary I think. 

It forces you to resize the drawer on each Dag, while you just want to see a 'bigger' graph or grid.

Just one nit.

**Comment by choo121600** [comment]
Also, if we simplify autoSaveId to the ${dagView}-${direction} format, we should apply the same logic to the asset view.
So instead of `${assetId}-${direction}`, I’ll change it to `asset-${direction}` for consistency and to avoid unnecessary separation of panel sizes per asset.

**Review by pierrejeambrun — APPROVED** [review]
Love that, thanks.

It felt super weird to me to have the UI shift all over the place between different dag details page / asset page.

**Comment by choo121600** [comment]
Thanks to @bbovenzi and @pierrejeambrun, I was able to wrap this up 🙌
I was going in the wrong direction at first, but your hints and reviews really helped me get on track. Appreciate it!
