### PR TITLE
Use dropdown instead of buttons when there are more than 10 retries in log tab

### LINKED ISSUE #35889: New logs tab is broken for tasks with high retries
### Apache Airflow version

2.7.3

### What happened

One of our users had high number of retries around 600 and the operator was like a sensor that retries on failure till retry limit is reached. The new log page renders the log tab to the bottom making it unusable. In the old page there is still a display of buttons for all retry but scrolling is enabled. To fix this we had to change log from buttons to a drop down where attempt can be selected placing the dropdown before the element to select log level. This is an edge case but we thought to file anyway in case someone is facing this. We are happy to upstream to one of the selected below solutions : 

1. Using dropdown on high number of attempts like after 50 and falling back to buttons. But this is a UX change to use button in one case and dropdown in another that user needs to be educated.
2. Always using dropdown despite low number of attempts with default of latest attempt.

Attaching sample dag code that could lead to this scenario.

Sample scenario : 

image

### What you think should happen instead

_No response_

### How to reproduce

```python
from datetime import datetime, timedelta

from airflow import DAG
from airflow.decorators import task
from airflow.models.param import Param
from airflow.operators.empty import EmptyOperator

from datetime import timedelta


with DAG(
    dag_id="retry_ui_issue",
    start_date=datetime(2023, 1, 1),
    catchup=False,
    schedule_interval="@once",
) as dag:

    @task(retries=400, retry_delay=timedelta(seconds=1))
    def fail_always():
        raise Exception("fail")

    fail_always()
```

### Operating System

Ubuntu

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tirkarthi**
Use dropdown instead of button to select log attempt when there are more than 10 retries.

Less than 10 retries

image

More than 10 retries

image

closes: #35889
related: #35889 

Sample dag :

```python
from datetime import datetime, timedelta

from airflow import DAG
from airflow.decorators import task


with DAG(
    dag_id="retry_issue_dag",
    start_date=datetime(2023, 10, 10),
    catchup=False,
    schedule_interval="@once",
) as dag:

    @task(retries=8, retry_delay=timedelta(seconds=1))
    def retry_less_than_10():
        raise Exception("fail")

    @task(retries=15, retry_delay=timedelta(seconds=1))
    def retry_more_than_10():
        raise Exception("fail")

    retry_less_than_10()
    retry_more_than_10()

```

### CODE REVIEW

File: airflow/www/static/js/dag/details/taskInstance/Logs/index.tsx [hunk 1]
```diff
@@ -193,24 +197,44 @@ const Logs = ({
...
+                  </Flex>
+                </Flex>
+              </Box>
+            )}
             <Flex my={1} justifyContent="space-between" flexWrap="wrap">
               <Flex alignItems="center" flexGrow={1} mr={10}>
+                {showDropdown && (
+                  <Box width="100%" mr={2}>
+                    <Select
+                      placeholder="Select log attempt"
```
Comment (jscheffl) [inline airflow/www/static/js/dag/details/taskInstance/Logs/index.tsx:226]: Can you apply a small nit, such that the size is matching the other dropdowns? Otherwise I tested and looks good! Even if you just restart the 10th time you see the UI immediately switching.
```suggestion
                      size="sm"
                      placeholder="Select log attempt"
```

Comment (tirkarthi) [reply airflow/www/static/js/dag/details/taskInstance/Logs/index.tsx:226]: Thanks @jscheffl , applied your suggestion.

**Review by eladkal — APPROVED** [review]

**Review by jscheffl — APPROVED** [review]

**Review by potiuk — APPROVED** [review]
