### PR TITLE
Fix task id copy button copying wrong id

### LINKED ISSUE #34846: Task ID copy button copying wrong ID
### Apache Airflow version

2.7.1

### What happened

The Task ID copy button in Grid View copies the first Task ID copied until the page refresh

### What you think should happen instead

The corresponding Task ID should be copied

### How to reproduce

1. Go to Grid view and open any task
2. Click the copy button in front of the Task ID
3. The ID in the clipboard is correct
4. Open another task
5. (optional) Copy any stuff to reset the clipboard
6. Click the copy button again
7. The ID in the clipboard is the ID from Step 2

In any other task, the first Task ID (from Step 2) will be copied until the page is refreshed

### Operating System

Mac OS (ARM)

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else

It occurs every time in the latest Chrome browser

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Adaverse**
Fixes: #34846
Sets the value that needs to be copied whenever it changes. The previous implementation had a bug since the component will only render once with the page.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by Taragolis — APPROVED** [review]
I've checked locally this patch and it works

File: airflow/www/static/js/components/Clipboard.tsx [hunk 1]
```diff
@@ -43,9 +43,13 @@ export const ClipboardButton = forwardRef(
     },
     ref
   ) => {
-    const { hasCopied, onCopy } = useClipboard(value);
+    const { setValue, hasCopied, onCopy } = useClipboard(value);
     const containerRef = useContainerRef();
 
+    useEffect(() => {
+      setValue(value);
```
Comment (bbovenzi) [inline airflow/www/static/js/components/Clipboard.tsx:50]: Can we wrap this in an if statement and only setValue if it is different from the current clipboard value?

Comment (AchimGaedkeLynker) [reply airflow/www/static/js/components/Clipboard.tsx:50]: After reading https://stackoverflow.com/questions/41322523/reactjs-calling-setstate-with-same-parameter carefully, I believe this is not necessary, as same values do not trigger a state change event.

Would this unblock the pull request - allowing to close #34846 ?

Comment (ephraimbuddy) [reply airflow/www/static/js/components/Clipboard.tsx:50]: WDYT @bbovenzi ?

**Review by bbovenzi — APPROVED** [review]
