### PR TITLE
Store duration in seconds and scale to handle case when a value in the series has a larger unit than the preceding durations

### LINKED ISSUE #38371: Task and dagrun duration y-axis is incorrect if the last task has a different duration unit
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

During our internal testing it was found that the duration implementation we found that if the last taskinstance or if one of the taskinstance in the middle has a higher duration that leads to a different unit then the same unit applied to the previous durations and they are not scaled back. Below is an example where all taskinstances complete in seconds except for the last taskinstance which is more than a minute but all the durations are mentioned in minutes making it confusing. The same logic is present in dagrun duration as well. One solution would be to have everything as seconds and during chart construction we can scale them based on the max value. We have a fix for this tested internally and I will open a PR.

image

```python
from datetime import datetime, timedelta

from airflow import DAG
from airflow.decorators import task
from airflow.operators.empty import EmptyOperator

from datetime import timedelta


with DAG(
    dag_id="task_duration_average",
    start_date=datetime(2024, 1, 1),
    end_date=datetime(2024, 1, 15),
    catchup=True,
    schedule_interval="@daily",
) as dag:

    @task
    def sleeper(ds=None):
        import random, time, pendulum

        last_day = pendulum.datetime(2024, 1, 15)
        execution_date = pendulum.parse(ds)

        if execution_date == last_day:
            duration = 130
        else:
            duration = random.randint(1, 5)

        time.sleep(duration)

    sleeper()
```

### What you think should happen instead?

_No response_

### How to reproduce

1. Have a dag which takes few seconds and make last task instance take few minutes
2. Look at the task duration and dagrun duration chart and the grid bars.

### Operating System

Ubuntu

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tirkarthi**
closes: #38371
related: #38371

Store all durations in seconds and have unitDivisor which is the scale factor selected based on the maximum duration seen. During chart construction scale down the values with unitDivisor.

Before : 

image

After :

image

### CODE REVIEW

**Review by bbovenzi — APPROVED** [review]
Looks good. Perhaps later we could make a shared component or util to be more DRY

File: airflow/www/static/js/dag/details/task/TaskDuration.tsx [hunk 1]
```diff
@@ -179,7 +170,18 @@ const TaskDuration = () => {
     // @ts-ignore
     dataset: {
       dimensions: ["runId", "queuedDurationUnit", "runDurationUnit"],
-      source: durations,
+      source: durations.map((duration) => {
+        if (duration) {
+          const durationInSeconds = duration as TaskInstanceDuration;
```
Comment (tirkarthi) [inline airflow/www/static/js/dag/details/task/TaskDuration.tsx:175]: I couldn't find the right way to convince typescript compiler here since duration is a union type of {} | TaskInstanceDuration. Neither checking for duration to be true in if clause nor using (duration as TaskInstanceDuration) / unitDivisor without a temporary variable.

**Comment by tirkarthi** [comment]
@bbovenzi yes, working on the PRs I felt the same since I was modifying very similar code on both files. Since 2.9.0b1 is out I thought to focus more on the bug fixes.

File: airflow/www/static/js/dag/details/task/TaskDuration.tsx (hunk 1 above)
Comment (bbovenzi) [reply airflow/www/static/js/dag/details/task/TaskDuration.tsx:175]: Actually we can drop the `<RunDuration | {}>[]` and just have `RunDuration[]`


And for taskDurations we can change from `map` to `forEach` like so:

``` 
const durations: TaskInstanceDuration[] = [];

  dagRuns.forEach((dagRun) => {
    const { runId } = dagRun;
    const instance = task.instances.find((ti) => ti && ti.runId === runId);
    if (instance) {
 ```
 
 and then
 
 ```
      durations.push({
        ...instance,
        [orderingLabel]: dagRun ? dagRun[orderingLabel] : instance.startDate,
        runDuration,
        queuedDuration,
        runDurationUnit,
        queuedDurationUnit,
      });
```

Comment (tirkarthi) [reply airflow/www/static/js/dag/details/task/TaskDuration.tsx:175]: In the initial PR it used to be that way using .push and foreach but I remember vaguely that eslint had something about foreach and change was made to map using TaskInstanceDuration[] and then null was added that later changed to {}. Some of the relevant diffs as below. I guess this was made for a reason. I would keep the cast as it is a simpler change to typecast like assert and use the object. Thanks.

Relevant commits : 

https://github.com/apache/airflow/commit/8156faa5f710b0e21ab741073d2a889e019240e6
https://github.com/apache/airflow/commit/23435af92dcaa4f0668978dbf103706d7c02acb0

```diff
-  dagRuns.forEach((dagRun) => {
-    const instance = hasTaskInstances.instances.find(
-      (_instance) =>
-        _instance.taskId === taskId && _instance.runId === dagRun.runId
-    );
-
-    if (!instance) return null;
+  const durations: TaskInstanceDuration[] = task.instances.map((instance) => {
     // @ts-ignore
     const runDuration = moment.duration(
       instance?.startDate && instance?.endDate
@@ -108,77 +73,77 @@ const TaskDuration = () => {
       maxDuration = runDuration.asSeconds();
     }
 
-    durations.push(
-      new TaskInstanceDuration(
-        instance,
-        runDuration,
-        queuedDuration,
-        dagRun.dataIntervalStart,
-        dagRun.dataIntervalEnd,
-        dagRun.executionDate
-      )
-    );
-
-    return null;
-  });

```


```
-  const durations: TaskInstanceDuration[] = task.instances.map((instance) => {
+  const durations: (TaskInstanceDuration | null)[] = dagRuns.map((dagRun) => {
+    const { runId } = dagRun;
+    const instance = task.instances.find((ti) => ti && ti.runId === runId);
+    if (!instance) return null;
```

```
diff --git a/airflow/www/static/js/dag/details/task/TaskDuration.tsx b/airflow/www/static/js/dag/details/task/TaskDuration.tsx
index 1f99f39e4d..cb6ad1f69d 100644
--- a/airflow/www/static/js/dag/details/task/TaskDuration.tsx
+++ b/airflow/www/static/js/dag/details/task/TaskDuration.tsx
@@ -56,10 +56,10 @@ const TaskDuration = () => {
   if (!task) return null;
   const orderingLabel = ordering[0] || ordering[1] || "startDate";
 
-  const durations: (TaskInstanceDuration | null)[] = dagRuns.map((dagRun) => {
+  const durations: (TaskInstanceDuration | {})[] = dagRuns.map((dagRun) => {
     const { runId } = dagRun;
     const instance = task.instances.find((ti) => ti && ti.runId === runId);
-    if (!instance) return null;
+    if (!instance) return {};
```

https://github.com/github/eslint-plugin-github/blob/main/docs/rules/array-foreach.md

**Review by jscheffl — APPROVED** [review]
If the conversatio nis resolved... I assume so but it is open... then LGTM!

File: airflow/www/static/js/dag/details/task/TaskDuration.tsx (hunk 1 above)
Comment (bbovenzi) [reply airflow/www/static/js/dag/details/task/TaskDuration.tsx:175]: Yes, my bad. I remember now why we changed that. We needed empty columns in case there was no task instance for a particular dag run. Let's leave you work as-is then

**Comment by tirkarthi** [comment]
Thanks @bbovenzi and @jscheffl
