### PR TITLE
Fix timezone conversion in datetime trigger parameters

### LINKED ISSUE #54466: Date-time DAG param UI issues
### Apache Airflow version

3.0.4

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

DAG params of format `date-time` results in unexpected behavior when attempting to set the param value via the UI. I've attached a clip that outlines the problem; when a time is set using the date-time picker, 4 hours is automatically added to the user-inputted time. Then, once a user is done selecting the time and the date-time picker UI component is hidden, another four hours is added to the date-time. When I made this clip I was using the default `utc` timezone. I have also tested this with `America/New_York` default_timezone and was successfully able to reproduce the problem.

https://github.com/user-attachments/assets/c3d6c8a0-9ef9-4710-8ea4-f6319125a28e

### What you think should happen instead?

I would expect the user-inputted time to be used. I would think the UI should be config-aware and assume the inputted time is in the `default_timezone` tz. Instead, it seems like there is some timezone conversion happening within the UI component which results in an incorrect value in the `params`. 

### How to reproduce

I was able to reproduce the bug with this minimal DAG:
```
from airflow.sdk import DAG, Param, task
from datetime import datetime


with DAG(
    "test_date_time",
    dag_display_name="Test Date-Time Param",
    catchup=False,
    start_date=datetime(2025, 7, 1),
    schedule=None,
    params={
        "my_datetime": Param(type="string", format="date-time"),
    },
) as dag:

    @task
    def output_my_datetime(**context):
        datetime_dag_param = context["params"]["my_datetime"]
        print(f"Raw dt: {datetime_dag_param}")
        return datetime_dag_param

    output_my_datetime()
```

### Operating System

macOS Sequoia 15.4.1

### Versions of Apache Airflow Providers

No providers necessary to reproduce.

### Deployment

Astronomer

### Deployment details

We discovered the issue in our deployment which uses `America/New_York` as the core configuration `default_timezone`, however we were also able to reproduce using the `utc` tz.

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by steveahnahn**
## Summary

Fixes a bug where datetime parameter inputs in the Airflow UI were applying timezone conversion twice, causing incorrect scheduling times. When users selected a local time via the datetime picker, the actual trigger time would be offset by double the timezone difference.

## Problem
1. User picks "5:25 PM" local time (Pacific UTC-7)
2. DateTimeInput converts to UTC: "2025-08-17T00:25:00.000Z"
3. FieldDateTime adds fake UTC suffix: "2025-08-17T00:25:00.000Z:00+00:00"
4. This malformed string gets parsed incorrectly
5. Results in wrong final datetime (appeared like double conversion)
 
## Solution
`DateTimeInput` handles all conversions, other components pass UTC values unchanged

1. `DateTimeInput`: Maintains proper timezone conversion (local display -> UTC)
2. `FieldDateTime`: Removed faulty conditional that was adding fake UTC suffixes to already-converted values

## Testing
  - Manual testing with Pacific (UTC-7) timezone and verified DAG triggers execute at correct times
  - Confirmed no double conversion in browser console logs
  
## Related Issues
resolves #54466

### CODE REVIEW

**Comment by bbovenzi** [comment]
Thanks for the fix!
Can you test the Trigger Dag and Run Backfill forms to make sure they're still using the correct timezones?

File: airflow-core/src/airflow/ui/src/components/FlexibleForm/FieldDateTime.tsx [hunk 1]
```diff
@@ -56,7 +62,11 @@ export const FieldDateTime = ({
         name={`element_${name}`}
         onChange={(event) => handleChange(event.target.value)}
         size="sm"
-        value={((param.value ?? "") as string).slice(0, 16)}
+        value={
+          Boolean(param.value) && typeof param.value === "string"
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/components/FlexibleForm/FieldDateTime.tsx]: We might want to use `isValid()` instead https://github.com/apache/airflow/pull/54370/files

Comment (steveahnahn) [reply airflow-core/src/airflow/ui/src/components/FlexibleForm/FieldDateTime.tsx]: resolved with [773374f](https://github.com/apache/airflow/pull/54593/commits/773374f7401c8c4ab52621b72f841fc979b56c1c)

**Comment by steveahnahn** [comment]
Additional testing done with Trigger Dag, Trigger Dag advanced configurations & Run Backfill

File: airflow-core/src/airflow/ui/src/components/DateTimeInput.tsx [hunk 2]
```diff
@@ -17,42 +17,26 @@
...
-        })
-      }
-      ref={ref}
-      type="datetime-local"
-      value={date}
-      {...rest}
-    />
-  );
-});
+export const DateTimeInput = forwardRef<HTMLInputElement, Props>(({ onChange, value, ...rest }, ref) => (
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/components/DateTimeInput.tsx]: `DateTimeInput` is used at multiple places, we also just merged `EventsFilters`, `XComFilters`.

We might need to also make the datetime tz aware there before feeding it to the `DateTimeInput` component, but that would duplicate the conversion, maybe there's a way to achieve that without this duplication.

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/components/DateTimeInput.tsx]: For intance EventLogs filtering:
Screenshot 2025-08-19 at 18 43 10

**Comment by steveahnahn** [comment]
Fixed datetime parameter timezone conversion bug by removing faulty string manipulation in `FieldDateTime` that was corrupting properly converted UTC values from `DateTimeInput`. @pierrejeambrun

**Review by pierrejeambrun — APPROVED** [review]
LGTM. (tested the trigger run params + backfill form)
