### PR TITLE
Provider packages are installed by default in production image

### LINKED ISSUE #12150: Production image has only amazon and google providers installed
When "production" image is prepared for, only amazon and google providers are installed from sources.

**Apache Airflow version**:

master

**What you expected to happen**:

All providers should be installed

**How to reproduce it**:

```
./breeze --production-image --python 3.6
```

Then:

```
./breeze --production-image --python 3.6 shell bash
```

then

```
ls -la ~/.local/lib/python3.6/site-packages/airflow/providers/

amazon
google

```

UPDATE:

They are not even installed: 

```
.
./amazon
./amazon/aws
./amazon/aws/hooks
./amazon/aws/hooks/batch_waiters.json
./google
./google/cloud
./google/cloud/example_dags
./google/cloud/example_dags/example_bigquery_query.sql
./google/cloud/example_dags/example_cloud_build.yaml
./google/cloud/example_dags/example_spanner.sql
```

### PR DESCRIPTION
**Pull request by potiuk**
This is a fix to a problem introduced in #10806. The change
turned provider packages into namespace packages - which made
them ignored by find_packages function from setup tools - thus
prodiuction image build automatically and used by Kubernetes
tests did not have the provider packages installed.

This PR fixes it and adds future protection during CI tests of
production image to make sure that provider packages are
actually installed.

Fixes #12150

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

File: scripts/ci/images/ci_prepare_prod_image_on_ci.sh [hunk 1]
```diff
@@ -48,4 +48,61 @@ function build_prod_images_on_ci() {
 }
 
 
+
+function verify_prod_image_has_airflow_and_providers {
```
Comment (mik-laj) [inline scripts/ci/images/ci_prepare_prod_image_on_ci.sh:52]: Can you add a test that will check if at least one provider can be loaded? This will give us the greatest confidence that everything is working.
```
python -c "from airflow.providers.google.common.hooks.base_google import GoogleBaseHook"
```
We may have these files in the image, but for various reasons they may not be loaded by Python, e.g. due to invalid permissions.

Comment (potiuk) [reply scripts/ci/images/ci_prepare_prod_image_on_ci.sh:52]: I can do better than that. I already have script that imports all of the providers (I am using that in providers package/backport providers package preparation and it is perfectly suited for that case. it is even very well prepared to handle this case.

Comment (potiuk) [reply scripts/ci/images/ci_prepare_prod_image_on_ci.sh:52]: However it needs #12082 . So I'd rather merge it now and add the test in #12082 @mik-laj if that's ok?

Comment (mik-laj) [reply scripts/ci/images/ci_prepare_prod_image_on_ci.sh:52]: SGTM.

**Comment by potiuk** [comment]
> There was a reason I _didn't_ do this. By having this be find_namespace_packages it will _always_ include all the providers in the airflow dist. I.e. it reverses the split out.

Yes. Correct. it should only happen when "install_providers_from_sources" is set. that is the right fix

**Comment by potiuk** [comment]
Should be fixed now. As discussed - later when we will release provider packages we will switch to the mode of building the package using wheels. But I do not think we need to do it now, I think we need to release PyPI packages first and then we will synchronize the process. I yet have to see how we are going to build those. The Docker Image has all the features needed to build the "master" image differently - using packages.

However requiring going through the hoops of building all packages and installing them locally for local development and testing is not a good idea, so building from sources including all providers should remain to help developers who are actually working on improving the prod image.

File: scripts/ci/images/ci_prepare_prod_image_on_ci.sh [hunk 2]
```diff
@@ -48,4 +48,61 @@ function build_prod_images_on_ci() {
...
+         'find '"${AIRFLOW_INSTALLATION_LOCATION}"'/lib/python*/site-packages/airflow/ -type d | grep -c -v "/airflow/providers"')
+
+    echo
+    echo "Number of airflow dirs: ${COUNT_AIRFLOW_DIRS}"
+    echo
+
+    if [[ "${COUNT_AIRFLOW_DIRS}" -lt "${EXPECTED_MIN_AIRFLOW_DIRS_COUNT}" ]]; then
+        >&2 echo
+        >&2 echo Number of airflow folders installed is less than ${EXPECTED_MIN_AIRFLOW_DIRS_COUNT}
+        >&2 echo This is unexpected. Please investigate, looking at the output above!
```
Comment (kaxil) [inline scripts/ci/images/ci_prepare_prod_image_on_ci.sh:75]: Can we add some more information on what needs to be investigated, i.e. something like "Providers might not have been installed" etc

**Review by kaxil — APPROVED** [review]
