### PR TITLE
turn off autocomplete for connection forms

### LINKED ISSUE #13656: Password is unintendedly changed when editing a connection
**Apache Airflow version**: 2.0.0

**What happened**:

When editing a connection - without changing the password - and saving the edited connection, a wrong password is saved.

**What you expected to happen**:

If I do not change the password in the UI, I expect that the password is not changed.

**How to reproduce it**:

- Create a new connection and save it (screenshots 1 + 2)
- Edit the connection without editing the password, and save it again (screenshots 3 + 4)

If you _do_ edit the password, the (new or old) password is saved correctly.

*Screenshot 1*
image

*Screenshot 2*
image

*Screenshot 3*
image

*Screenshot 4*
image

(I blurred out the full string in the unlikely case that the full string might contain information on my fernet key or something)

### PR DESCRIPTION
**Pull request by bbovenzi**
Adding `autocomplete="off"` to the add/edit connection form. In addition to passwords, I could see an unintentional change to "Login" too, so turned off autocomplete to the whole form.

Fixes #13656

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by bbovenzi** [comment]
@potiuk Let me know if there is anywhere else we should do this.

File: airflow/www/static/js/connection_form.js [hunk 1]
```diff
@@ -59,6 +59,8 @@ function getControlsContainer() {
 $(document).ready(function () {
   const fieldBehavioursElem = document.getElementById('field_behaviours');
   const config = JSON.parse(decode(fieldBehavioursElem.textContent));
+  const form = document.getElementById('model_form');
```
Comment (ryanahamilton) [inline airflow/www/static/js/connection_form.js:64]: Maybe add a comment to make the intensions here clear?
```suggestion
  // Prevent login/password fields from triggering browser auth extensions
  const form = document.getElementById('model_form');
```

Comment (bbovenzi) [reply airflow/www/static/js/connection_form.js:64]: Good idea. Added.

**Review by ashb — APPROVED** [review]

**Review by ryanahamilton — APPROVED** [review]
