### PR TITLE
Correctly enable Connection "Save" button when editing 'Extra Fields'

### LINKED ISSUE #55496: Can not edit 'Extra Fields' of connection
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

1. The `Save` button is disabled when edit by `Extra Fields` of conenction
2. Click `Save` button after edit by `Extra Fields JSON` of conenction, no response

Image

Image

### What you think should happen instead?

`Extra Fields` can be edit

### How to reproduce

1. Add a `Extra Fields JSON` when adding a connection
2. Click `Eidt`

### Operating System

Ubuntu

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

breeze start-airflow --dev-mode

### Anything else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by yangyulely**
closes: #55496 
related: #55496 

### Issue Summary

Cannot edit the `Extra Fields` of connections in the Airflow UI. Two specific problems:

1. `Save` button is disabled when editing through `Extra Fields`
2. No response when clicking `Save` after editing through `Extra Fields JSON`

### Root Cause

The `ConnectionForm` component uses `React Hook Form` for state management, but the `FlexibleForm` component manages extra fields through a separate `Zustand` store. React Hook Form's `isDirty` state doesn't track changes made through the flexible form, causing the `Save` button to remain disabled and preventing proper form submission.

### Solution

The fix introduces proper state tracking for extra fields changes:

1. __Add dirty state tracking__: New `isExtraFieldsDirty` state tracks changes to extra fields independently
2. __Update save button logic__: Enable save button when either regular form fields OR extra fields are modified
3. __Fix form submission__: Ensure latest extra fields data is included in the submission
4. __Proper initialization__: Store and compare formatted initial JSON values to avoid false positives

### Result

`Extra Fields` and `Extra Fields JSON` are both work well after fixed
fix_extra_edit

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx [hunk 1]
```diff
@@ -251,8 +265,20 @@ const ConnectionForm = ({
...
-            onClick={() => void handleSubmit(onSubmit)()}
+            disabled={
+              Boolean(errors.conf) || formErrors || isPending || !isValid || (!isDirty && !isExtraFieldsDirty)
+            }
+            onClick={() => {
+              // Update the form's extra field with the latest conf value before submitting
+              void handleSubmit((data) => {
+                const updatedData = {
+                  ...data,
+                  extra,
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx]: I think this should be the other way around. Otherwise the existing `extra` values will override the user-edited values.
Order matters when spreading props

File: airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx [hunk 2]
```diff
@@ -74,14 +74,21 @@ const ConnectionForm = ({
   const paramsDic = { paramsDict: connectionTypeMeta[selectedConnType]?.extra_fields ?? ({} as ParamsSpec) };
 
   const [formErrors, setFormErrors] = useState(false);
+  const [isExtraFieldsDirty, setIsExtraFieldsDirty] = useState(false);
+  const [initialExtra, setInitialExtra] = useState("");
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx]: Are you sure we need new useStates that are updated via useEffects? 
We already have an `initialConnection` object that we should compare against the `conf: extra`

**Review by bbovenzi — CHANGES_REQUESTED** [review]
Let's try to avoid mixing more useStates and useEffects if possible. If not possible, leave some comments above the useEffect on why it was necessary

**Comment by yangyulely** [comment]
> Let's try to avoid mixing more useStates and useEffects if possible. If not possible, leave some comments above the useEffect on why it was necessary

@bbovenzi Thanks for review and excellent suggestion! I have make the change:

1. Simplified the submission to just use `mutateConnection(data)` as before.
2. Removed the unnecessary useState hooks and simplified the state management as suggested.

Can you review these? thanks~~

File: airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx [hunk 3]
```diff
@@ -96,6 +96,19 @@ const ConnectionForm = ({
...
+    try {
+      const initialParsed = JSON.parse(initialConnection.extra) as Record<string, unknown>;
+      const currentParsed = JSON.parse(extra) as Record<string, unknown>;
+
+      return JSON.stringify(initialParsed) !== JSON.stringify(currentParsed);
+    } catch {
+      // If parsing fails, fall back to string comparison
+      return extra !== initialConnection.extra;
+    }
+  })();
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx:110]: I don't think parsing and stringifying does anything helpful here.

Either we just do `extra !== initialConnection.extra` or we we iterate through initialParsed with Object.keys to actually compare each key/value pair

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx:110]: I think it's because of the front-end json formatting. 'content' is actually the same, but UI will show extra '\n' and indent to have a nice display, those wouldn't match with plain string comparison.

Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/pages/Connections/ConnectionForm.tsx:110]: Also you probably don't need to define a function and call that right away

**Review by pierrejeambrun — APPROVED** [review]
Working as expected. Thanks

**Review by bbovenzi — APPROVED** [review]
