### PR TITLE
Removes quotes for _PIP_ADDITIONAL_REQUIREMENTS

### LINKED ISSUE #16363: _PIP_ADDITIONAL_REQUIREMENTS environment variable of the container image cannot install more than one package
**Apache Airflow version**: 2.1.0

**Environment**: Docker

**What happened**: I tried to install more than one pip packages using the _PIP_ADDITIONAL_REQUIREMENTS enviroment variable when running Airflow image built using the latest Dockerfile. My _PIP_ADDITIONAL_REQUIREMENTS was set to "pandas scipy". The result was `ERROR: Invalid requirement: 'pandas scipy'`

**What you expected to happen**: I expected both pandas and scipy to install without errors. I believe that the image is now trying to install one package called "pandas scipy", which doesn't exist. I believe by removing the double quotation marks surrounding the ${_PIP_ADDITIONAL_REQUIREMENTS=} from this line of code would solve the issue: https://github.com/apache/airflow/blob/main/scripts/in_container/prod/entrypoint_prod.sh#L327

**How to reproduce it**: Using image built using the latest Dockerfile, try to run the image with `docker run --rm -it --env _PIP_ADDITIONAL_REQUIREMENTS="pandas scipy" image:tag`

### PR DESCRIPTION
**Pull request by potiuk**
Fixes #16363

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

File: scripts/in_container/prod/entrypoint_prod.sh [hunk 1]
```diff
@@ -324,7 +324,7 @@ if [[ -n "${_PIP_ADDITIONAL_REQUIREMENTS=}" ]] ; then
     >&2 echo "         the container starts, so it is onlny useful for testing and trying out"
     >&2 echo "         of adding dependencies."
     >&2 echo
-    pip install --no-cache-dir --user "${_PIP_ADDITIONAL_REQUIREMENTS=}"
+    pip install --no-cache-dir --user ${_PIP_ADDITIONAL_REQUIREMENTS}
```
Comment (uranusjr) [inline scripts/in_container/prod/entrypoint_prod.sh:327]: Does this work for `_PIP_ADDITIONAL_REQUIREMENTS="foo>1"`, or does it redirect? We probably need some documentation on this if the user needs to quote each requirements on their own.

Comment (potiuk) [reply scripts/in_container/prod/entrypoint_prod.sh:327]: It will work. We are using bash as interpreter and redirect only works when it is not passed via variable:

```
export _PIP_ADDITIONAL_REQUIREMENTS="pip<20.2.2 setuptools"
θ60° [jarek:~] 32s $ pip install --no-cache-dir --user ${_PIP_ADDITIONAL_REQUIREMENTS}
Collecting pip<20.2.2
  Downloading pip-20.2.1-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 1.2 MB/s 
Requirement already satisfied: setuptools in ./.pyenv/versions/3.7.9/lib/python3.7/site-packages (47.1.0)
Installing collected packages: pip
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /home/jarek/.local/include/python3.7m/pip
  sysconfig: /home/jarek/.local/include/python3.7/pip
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /home/jarek/.local/include/python3.7m/UNKNOWN
sysconfig: /home/jarek/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
Successfully installed pip-20.2.1
WARNING: You are using pip version 21.1; however, version 21.1.2 is available.
You should consider upgrading via the '/home/jarek/.pyenv/versions/3.7.9/bin/python3.7 -m pip install --upgrade pip' command.
θ61° [jarek:~] 41s $ pip install --no-cache-dir --user ${_PIP_ADDITIONAL_REQUIREMENTS}

```

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
Random failure. Should be good to go.

**Review by eladkal — APPROVED** [review]
