### PR TITLE
Store inventories in GitHub Action cache

### LINKED ISSUE #14989: Make Docs builds fallback in case external docs sources are missing
Every now and then our docs builds start to fail because of external dependency (latest example here #14985). And while we are doing caching now of that information, it does not help when the initial retrieval fails. This information does not change often but with the number of dependencies we have it will continue to fail regularly simply because many of those depenencies are not very reliable - they are just a web page hosted somewhere. They are nowhere near the stabilty of even PyPI or Apt sources and we have no mirroring in case of problem.

Maybe we could 

a) see if we can use some kind of mirroring scheme (do those sites have mirrrors ? )
b) if not, simply write a simple script that will dump the cached content for those to S3, refresh it in the CI scheduled (nightly) master builds ad have a fallback mechanism to download that from there in case of any problems in CI?

### PR DESCRIPTION
**Pull request by uranusjr**
Second go to resolve #14989. 

This downloads the constraints file and use it as the key to store `docs/_inventory_cache` into GitHub Action's cache. The function to download inventories (`_fetch_file`) is modified to swallow network errors (emitting a log to stderr) and always succeed.

I'm not yet sure how best to implement the part pulling version from constraints to fetch the currect inventory versions. I'll probably start with checking each listed documentation and figure out if they have a version inventory (not so sure for e.g. boto).

### CODE REVIEW

**Comment by potiuk** [comment]
Nice! Waaaaaay simpler than the initial idea :). Would you mind `git commit --amend` and `git --force-push` to re-push it again (and change it to non-draft).  This way we will see if the cache works (it's been successfully pushed it seems)

**Comment by potiuk** [comment]
> I'm not yet sure how best to implement the part pulling version from constraints to fetch the currect inventory versions. I'll probably start with checking each listed documentation and figure out if they have a version inventory (not so sure for e.g. boto).

Actually, I think that's IT. We do not need all those version changes actually when you look at it now. This will beautifully work as-is now without any further changes.

**Review by potiuk — APPROVED** [review]

File: scripts/ci/docs/ci_docs.sh [hunk 1]
```diff
@@ -30,8 +30,7 @@ export PYTHONPATH=${AIRFLOW_SOURCES}
 
 pip install --upgrade pip==20.2.4
 
-pip install .[doc] --upgrade --constraint \
-    "https://raw.githubusercontent.com/apache/airflow/constraints-${DEFAULT_BRANCH}/constraints-${PYTHON_MAJOR_MINOR_VERSION}.txt"
+pip install .[doc] --upgrade --constraint "${AIRFLOW_SOURCES}/constraints.txt"
```
Comment (kaxil) [inline scripts/ci/docs/ci_docs.sh:33]: Wait is this change required?

**Review by kaxil — APPROVED** [review]
