### PR TITLE
Fixed rendered template values not displaying with proper code format…

### LINKED ISSUE #50324: Rendered Template field is hard to read in Airflow 3
### Apache Airflow version

3.0.0

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

Airflow Rendered Template field is hard to read in case of large bash_commands

Airflow 2 properly formats and syntax highlights the rendered template. However Airflow 3 just throws all of that in a text box making it difficult to read.

Image

### What you think should happen instead?

Use code block instead for rendered template

### How to reproduce

Run the example_bash_operator dag

### Operating System

Ubuntu

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by dheerajturaga**
This PR attempts to fix #50324 , #49064

  The issue was caused by double JSON serialization in the frontend:
  1. Backend already serializes template field values to strings via serialize_template_field()
  2. Frontend was calling JSON.stringify() again on these already-stringified values
  3. This resulted in escaped quotes and poor formatting

image

Core Fixes

  - Fixed double serialization: Replaced JSON.stringify(value) with proper type checking in RenderedTemplates.tsx:97
    - Use string values directly if already strings
    - Only JSON stringify non-string values (objects/arrays)
  - Added whitespace preservation: Replaced \<Code\> component with \<SyntaxHighlighter\> to preserve newlines and indentation

Syntax Highlighting Enhancement

  - Integrated react-syntax-highlighter with automatic language detection:
    - JSON: Detects objects/arrays with valid JSON structure
    - YAML: Detects key-value pairs with colons and lists
    - SQL: Detects keywords like SELECT, INSERT, CREATE, etc.
    - Bash: Detects commands, shebangs, control structures, and operators
    - Text: Falls back to plain text for unrecognized content
  - Theme support: Respects dark/light mode themes consistent with DAG code viewer
  - Improved styling: Added proper spacing, border radius, and responsive alignment

### CODE REVIEW

**Comment by dheerajturaga** [comment]
Added line number support
image

**Comment by dheerajturaga** [comment]
@pierrejeambrun, @jscheffl thoughts on this one?

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx [hunk 1]
```diff
@@ -16,14 +16,75 @@
...
 import { useTaskInstanceServiceGetMappedTaskInstance } from "openapi/queries";
 import { ClipboardRoot, ClipboardIconButton } from "src/components/ui";
+import { useColorMode } from "src/context/colorMode";
+
+SyntaxHighlighter.registerLanguage("json", json);
+SyntaxHighlighter.registerLanguage("yaml", yaml);
+SyntaxHighlighter.registerLanguage("sql", sql);
+SyntaxHighlighter.registerLanguage("bash", bash);
+
+const detectLanguage = (value: string): string => {
```
Comment (jscheffl) [inline airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx]: Can you separate this function out into a separate TS module file?

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx [hunk 2]
```diff
@@ -16,14 +16,75 @@
...
+      JSON.parse(trimmed);
+
+      return "json";
+    } catch {
+      // Not valid JSON, continue
+    }
+  }
+
+  // Try to detect YAML (basic heuristics)
+  if (trimmed.includes(":") && (trimmed.includes("\n") || trimmed.includes("- "))) {
```
Comment (jscheffl) [inline airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx]: Detection safety:
- If a colon is matched it should be followed by a newline (`":\n"`)
- Should we not rather use a lib like https://www.npmjs.com/package/yaml to test parsing after some basic heuristics before making a decision (similar to JSON)?

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx [hunk 3]
```diff
@@ -16,14 +16,75 @@
...
+    return "yaml";
+  }
+
+  // Try to detect SQL (basic heuristics)
+  const sqlKeywords = /\b(?:select|insert|update|delete|create|alter|drop|from|where|join)\b/iu;
+
+  if (sqlKeywords.test(trimmed)) {
```
Comment (jscheffl) [inline airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx]: Would it might be better to match more than a single keyword, as `SELECT` will in almost all cases will be followed by a `FROM` and otherwise `DROP` will also usually be followed by a `TABLE`.

**Review by jscheffl — COMMENTED** [review]
From reading code I really like the lean approach. Some matching nit from my side to make it a bit more safe.

Would like to have an UI expert second opinion though.

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx (hunk 1 above)
Comment (dheerajturaga) [reply airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx]: Done!

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx (hunk 3 above)
Comment (dheerajturaga) [reply airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx]: I switched to using a SQL parser. should be more robust!

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx (hunk 2 above)
Comment (dheerajturaga) [reply airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx]: Done!

**Comment by dheerajturaga** [comment]
> From reading code I really like the lean approach. Some matching nit from my side to make it a bit more safe.
> 
> 
> 
> Would like to have an UI expert second opinion though.

@jscheffl I added the fixes you requested, let me know if this looks good to you

**Review by jscheffl — APPROVED** [review]
For me this looks good! LGTM!

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx [hunk 4]
```diff
@@ -32,20 +46,42 @@ export const RenderedTemplates = () => {
...
+                      <Box
+                        css={{
+                          "& pre": {
+                            borderRadius: "4px",
+                            fontSize: "14px",
+                            margin: 0,
+                            padding: "8px",
+                          },
+                        }}
+                        flex="1"
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx]: Can we not use such inline css, and style the appropriate component. Also chakraUI provide some default value for padding marging etc, that are 1,2,3,4,5 and translate to fix values in pixels for consitency accross the UI.

File: airflow-core/src/airflow/ui/src/utils/detectLanguage.ts [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+import { parse as parseYaml } from "yaml";
+
+export const detectLanguage = (value: string): string => {
+  const trimmed = value.trim();
+
+  // Try to detect JSON
+  if (
+    (trimmed.startsWith("{") && trimmed.endsWith("}")) ||
+    (trimmed.startsWith("[") && trimmed.endsWith("]"))
+  ) {
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/utils/detectLanguage.ts]: I would remove that check, Just try parsing it if it's not valid, then it's not json

File: airflow-core/src/airflow/ui/src/utils/detectLanguage.ts [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+    // Basic heuristics first - must contain colons or dashes for key-value pairs or lists
+    if (trimmed.includes(":") || trimmed.includes("- ")) {
+      parseYaml(trimmed);
+
+      // If parsing succeeds and it's not just a simple string, it's likely YAML
+      return "yaml";
+    }
+  } catch {
+    // Not valid YAML, continue to other checks
+  }
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/utils/detectLanguage.ts]: Same here

**Review by pierrejeambrun — APPROVED** [review]
Just a few minor comments, looks good to me.

File: airflow-core/src/airflow/ui/src/utils/detectLanguage.ts (hunk 5 above)
Comment (jscheffl) [reply airflow-core/src/airflow/ui/src/utils/detectLanguage.ts]: I think this is good to be kept. It is a clever performance optimization because this is a good pre-check before a "heavy" parser gets going... if it is a longer text body then this saves some time and makes the page faster I think.

Comment (dheerajturaga) [reply airflow-core/src/airflow/ui/src/utils/detectLanguage.ts]: yea, I agree. The pre check avoids parsing which could be helpful if these fields are large. I cleanup if you think otherwise.

File: airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx (hunk 4 above)
Comment (dheerajturaga) [reply airflow-core/src/airflow/ui/src/pages/TaskInstance/RenderedTemplates.tsx]: @pierrejeambrun , Done! let me know if this is good!

File: airflow-core/src/airflow/ui/src/utils/detectLanguage.ts (hunk 5 above)
Comment (pierrejeambrun) [reply airflow-core/src/airflow/ui/src/utils/detectLanguage.ts]: I'm pretty sure that this is exacly what all parsers will do. 

For instance `rhino` js engine (mozilla js engine written in Java), you can find that:
https://github.com/mozilla/rhino/blob/master/rhino/src/main/java/org/mozilla/javascript/json/JsonParser.java#L53

`JSON.parse` will fail early if characters are not JSON parsable.

File: airflow-core/src/airflow/ui/src/utils/detectLanguage.ts (hunk 6 above)
Comment (dheerajturaga) [reply airflow-core/src/airflow/ui/src/utils/detectLanguage.ts]: Done!

File: airflow-core/src/airflow/ui/src/utils/detectLanguage.ts (hunk 5 above)
Comment (dheerajturaga) [reply airflow-core/src/airflow/ui/src/utils/detectLanguage.ts]: @pierrejeambrun , point taken. made the changes you have requested. Please let me know if these are good

Comment (jscheffl) [reply airflow-core/src/airflow/ui/src/utils/detectLanguage.ts]: Okay, hope the same is with YAML... then this is a convincing argument...

**Review by jscheffl — APPROVED** [review]
Good for me!
