### PR TITLE
Fix the misalignment of gantt view progress bars (#55061)

### LINKED ISSUE #55061: Gantt view progress bars are not aligning with actual tasks with DAG versioning
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

Gantt view progress bars are not aligning with actual tasks with DAG versioning

Image

### What you think should happen instead?

_No response_

### How to reproduce

1. Execute a DAG with multiple tasks 
2. Remove some task now(This should create a new Dag version)
3. Execute a new run and notice pogress bars are not aligning with actual tasks instead showing for the task which now do not exits

### Operating System

linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by yimingpeng**
Hello, 
This is a fix for the gannt view progress bar misalignment with dag versioning (#55061).

closes: #55061

image

hello @guan404ming, could you please review when you have a chance? Thank you!

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [airflow-core/newsfragments](https://github.com/apache/airflow/tree/main/airflow-core/newsfragments).

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx [hunk 1]
```diff
@@ -185,9 +187,9 @@ export const Gantt = ({ limit }: Props) => {
           minBarLength: MIN_BAR_WIDTH,
         },
       ],
-      labels: [],
+      labels: chartLabels,
```
Comment (guan404ming) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx]:
```suggestion
      labels: flatNodes.map((node) => node.id),
```

I think it would be better and more clear in this way.

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx [hunk 2]
```diff
@@ -185,9 +187,9 @@ export const Gantt = ({ limit }: Props) => {
...
     }),
-    [data],
+    [data, chartLabels],
```
Comment (guan404ming) [inline airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx]:
```suggestion
    [data, flatNodes],
```

**Review by guan404ming — APPROVED** [review]
Nice, thanks for the fix.
Some nits.

**Comment by guan404ming** [comment]
```
Closes https://github.com/apache/airflow/issues/55061
```

We could add `closes` and the issue number in PR description then it would be automatically linked to the corresponding issue~

File: airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx (hunk 1 above)
Comment (yimingpeng) [reply airflow-core/src/airflow/ui/src/layouts/Details/Gantt/Gantt.tsx]: agree, I was thinking to get the labels specifically memoized would be performant but could be trivial, thanks and making the updates now.

**Comment by yimingpeng** [comment]
> ```
> Closes https://github.com/apache/airflow/issues/55061
> ```
> 
> We could add `closes` and the issue number in PR description then it would be automatically linked to the corresponding issue~

aha, copy that, thanks for all the suggestions,  :)

**Review by guan404ming — APPROVED** [review]
Nice!

**Review by jscheffl — APPROVED** [review]

**Comment by guan404ming** [comment]
Hi @bbovenzi @jscheffl, I think it would be nice to add this in 3.1 since this is a critical fix for gantt chart view.

**Review by bbovenzi — APPROVED** [review]
