### PR TITLE
Fix Grid cache invalidation for multi-run task operations

### LINKED ISSUE #55267: UI - Grid invalidation on TI Action
Following the Grid data optimization we forgot to update accordingly the cache invalidation when clearing / marking as.

When clearing a TI, we should also invalidate the Grid data for that run. (dagrun state).

When clearing a TI with `future` or `past` to true, this will impact other dag runs, and we should cache invalidate all the dag runs grid data information in that case.

Typically:
After a clear with depends on past/future to True, UI looks like this:
Image

While it should look like:

Image

Related: https://github.com/apache/airflow/pull/54416

### PR DESCRIPTION
**Pull request by bggwak**
### Problem
Grid UI was not updating after clearing or patching task instances when
using the `include_future` or `include_past` options.(#55267 )

### Solution
- Fixed cache invalidation logic to properly refresh all affected DAG runs,
  not just the current run.
- Considered precise invalidation based on past/future options, but this
  required overly complex predicate logic.
- Opted for a simpler approach: invalidate all DAG Grid data whenever
  multiple runs are affected.

### Related Issues
Fixes #55267

### CODE REVIEW

File: airflow-core/src/airflow/ui/src/queries/useClearTaskInstances.ts [hunk 1]
```diff
@@ -78,17 +79,23 @@ export const useClearTaskInstances = ({
...
       ...taskInstanceKeys,
       UseDagRunServiceGetDagRunKeyFn({ dagId, dagRunId }),
       [useDagRunServiceGetDagRunsKey],
       [useClearTaskInstancesDryRunKey, dagId],
       [usePatchTaskInstanceDryRunKey, dagId, dagRunId],
       UseGridServiceGetGridRunsKeyFn({ dagId }, [{ dagId }]),
-      UseGridServiceGetGridTiSummariesKeyFn({ dagId, runId: dagRunId }, [{ dagId, runId: dagRunId }]),
+      affectsMultipleRuns
+        ? [useGridServiceGetGridTiSummariesKey, { dagId }]
+        : UseGridServiceGetGridTiSummariesKeyFn({ dagId, runId: dagRunId }),
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/queries/useClearTaskInstances.ts:95]:
```suggestion
      UseGridServiceGetGridTiSummariesKeyFn({ dagId, runId: affectsMultipleRuns ? undefined : dagRunId }),
```

I feel like this is a bit simpler?

File: airflow-core/src/airflow/ui/src/queries/useClearTaskInstances.ts [hunk 2]
```diff
@@ -78,17 +79,23 @@ export const useClearTaskInstances = ({
       ),
     ];
 
-    const queryKeys = [
+    // Check if this clear operation affects multiple DAG runs
+    const { include_future: includeFuture, include_past: includePast } = variables.requestBody;
+    const affectsMultipleRuns = includeFuture === true || includePast === true;
+
+    const invalidateKeys = [
```
Comment (bbovenzi) [inline airflow-core/src/airflow/ui/src/queries/useClearTaskInstances.ts]: Let's not rename the variables

**Review by pierrejeambrun — APPROVED** [review]
Code looks good, CI is not happy, you might need use the spread  operator instead to set or unset the runid variable.

**Review by eladkal — APPROVED** [review]
