### PR TITLE
Fix XCom edit modal value not repopulating on reopen.

### LINKED ISSUE #61486: XCom value is not populating on edit operation
### Apache Airflow version

main (development)

### If "Other Airflow 3 version" selected, which one?

_No response_

### What happened?

Image

### What you think should happen instead?

_No response_

### How to reproduce

1. Run a dag which generates an XCom on Airflow main branch.
2. Navigate to the XCom page.
3. Edit the XCom, on first attempt, notice that the XCom value is visible.
4. Once updated, try to edit the same XCom again and notice that the value is not populating again.

Below dag can be used to repro:
```python
import datetime

from airflow.providers.standard.operators.bash import BashOperator
from airflow import DAG

dag = DAG(
'test_api_dag',
start_date=datetime.datetime(2025, 8,25),
schedule='@daily',
is_paused_upon_creation=False,
catchup=False,
)

hello_task = BashOperator(
task_id="hello",
bash_command="echo hello",
dag=dag
)

hello_task
``` 

### Operating System

Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Arbaaz123676**
## Summary

This PR fixes an issue where the XCom value was not displayed when reopening the edit modal after updating it.

## Root Cause

The modal lifecycle and query behavior caused stale or skipped state updates when reopening the modal, leading to an empty value field.

## Changes

- Removed `lazyMount` from the dialog to ensure proper unmount/remount behavior.
- Enabled refetch on mount for the XCom entry query.
- Adjusted the population effect to rely on `data` instead of `data?.value !== undefined`.
- Ensured query invalidation for both `GetXcomEntries` and `GetXcomEntry` after update.

## Result

The XCom edit modal now consistently repopulates the latest value when reopened.

Fixes #61486

### CODE REVIEW

**Review by bbovenzi — APPROVED** [review]

**Review by pierrejeambrun — CHANGES_REQUESTED** [review]
This doesn't seem to fix the problem for me and some pieces of the change set seems irrelevant. (also CI need fixing)

https://github.com/user-attachments/assets/d166da58-43cf-4885-9c66-9b80963b22f7 

Can you double check or eventually provide a recording of this scenario working on your end?

File: airflow-core/src/airflow/ui/src/pages/XCom/XComModal.tsx [hunk 1]
```diff
@@ -113,13 +114,25 @@ const XComModal = ({ dagId, isOpen, mapIndex, mode, onClose, runId, taskId, xcom
...
+            dagRunId: runId,
+            deserialize: true,
+            mapIndex,
+            stringify: false,
+            taskId,
+            xcomKey,
+          },
+        ],
+        response,
+      );
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/XCom/XComModal.tsx]: Why are we changing this? Doesn't seem related.

**Review by pierrejeambrun — COMMENTED** [review]
As requested above you didn't provide more context (screenshot, explanation).

Part of the code change seem unrelated to the PR and looks like fully AI generated without any human double checking.

Closing the PR. Please do not re-open unless you are willing to actually spend the time needed to manually test this before asking for a review.

File: airflow-core/src/airflow/ui/src/pages/XCom/XComModal.tsx (hunk 1 above)
Comment (Arbaaz123676) [reply airflow-core/src/airflow/ui/src/pages/XCom/XComModal.tsx]: This updates the Query cache for a Airflow XCom entry using the API response after a successful request, so the UI updates immediately without refetching from the server.

Comment (bbovenzi) [reply airflow-core/src/airflow/ui/src/pages/XCom/XComModal.tsx]: This manually query setting is also incorrect. The response.value is always a string even if it is a date or json object.

File: airflow-core/src/airflow/ui/src/pages/XCom/XComModal.tsx [hunk 2]
```diff
@@ -58,6 +58,7 @@ const XComModal = ({ dagId, isOpen, mapIndex, mode, onClose, runId, taskId, xcom
       dagRunId: runId,
       deserialize: true,
       mapIndex,
+      stringify: false,
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/pages/XCom/XComModal.tsx]: Nit.

Not needed, it defaults to false already.

```suggestion
```

**Review by pierrejeambrun — APPROVED** [review]
One thing to remove. LGTM

**Review by choo121600 — APPROVED** [review]
looks good to me :)

**Review by bbovenzi — APPROVED** [review]
