### PR TITLE
Render stacktraces properly

### LINKED ISSUE #47921: stacktrace is not formatted in the logs in UI
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

stacktrace for exceptions from Python is present as part of extra key in `error_detail` and is not formatted making it hard to read the stacktrace.

Image

### What you think should happen instead?

_No response_

### How to reproduce

```python
from __future__ import annotations

from datetime import datetime

from airflow import DAG
from airflow.decorators import task

with DAG(
    dag_id="exception_stacktracen",
    start_date=datetime(2025, 2, 1),
    catchup=False,
    schedule=None,
) as dag:

    @task
    def error(**context):
        1 / 0

    error()
```

### Operating System

Ubuntu 20.04

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by aritra24**
Closes: #47921

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by aritra24** [comment]
Screenshot 2025-03-19 at 10 48 55 PM
First pass at fixing the stacktraces in logs, still need to make it prettier. So any recommendations are welcome...

**Comment by aritra24** [comment]
for context this is the error at hand
```
{
            "timestamp": "2025-03-19T15:00:52.088368Z",
            "event": "Task failed with exception",
            "level": "error",
            "logger": "task",
            "error_detail": [
                {
                    "exc_type": "ZeroDivisionError",
                    "exc_value": "division by zero",
                    "exc_notes": [],
                    "syntax_error": null,
                    "is_cause": false,
                    "frames": [
                        {
                            "filename": "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/task_runner.py",
                            "lineno": 582,
                            "name": "run"
                        },
                        {
                            "filename": "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/task_runner.py",
                            "lineno": 718,
                            "name": "_execute_task"
                        },
                        {
                            "filename": "/opt/airflow/task-sdk/src/airflow/sdk/definitions/baseoperator.py",
                            "lineno": 373,
                            "name": "wrapper"
                        },
                        {
                            "filename": "/opt/airflow/airflow/decorators/base.py",
                            "lineno": 252,
                            "name": "execute"
                        },
                        {
                            "filename": "/opt/airflow/task-sdk/src/airflow/sdk/definitions/baseoperator.py",
                            "lineno": 373,
                            "name": "wrapper"
                        },
                        {
                            "filename": "/opt/airflow/providers/standard/src/airflow/providers/standard/operators/python.py",
                            "lineno": 202,
                            "name": "execute"
                        },
                        {
                            "filename": "/opt/airflow/providers/standard/src/airflow/providers/standard/operators/python.py",
                            "lineno": 226,
                            "name": "execute_callable"
                        },
                        {
                            "filename": "/opt/airflow/airflow/utils/operator_helpers.py",
                            "lineno": 262,
                            "name": "run"
                        },
                        {
                            "filename": "/files/dags/sample_dag2.py",
                            "lineno": 17,
                            "name": "error"
                        }
                    ]
                }
            ]
        },
```

**Comment by ashb** [comment]
Display looks nice, but the indentation of display needs a bit of work.

Thanks for picking this up.

**Comment by bbovenzi** [comment]
+1 on indentation.

File: airflow/ui/src/components/RenderStructuredLog.tsx [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+      </Code>,
+      " - ",
+    );
+  }
+
+  const errorDetail = "error_detail" in structured ? structured.error_detail : undefined;
+  let details;
+
+  if (errorDetail !== undefined) {
+    delete structured.error_detail;
```
Comment (bbovenzi) [inline airflow/ui/src/components/RenderStructuredLog.tsx:127]: Why are we deleting this?

File: airflow/ui/src/components/RenderStructuredLog.tsx
Comment (bbovenzi) [inline airflow/ui/src/components/RenderStructuredLog.tsx:1]: `renderStructuredLog` since it doesn't actually return a named component

File: airflow/ui/src/queries/useLogs.tsx [hunk 2]
```diff
@@ -16,22 +16,17 @@
  * specific language governing permissions and limitations
  * under the License.
  */
-import { chakra, Code } from "@chakra-ui/react";
+import { chakra } from "@chakra-ui/react";
 import type { UseQueryOptions } from "@tanstack/react-query";
 import dayjs from "dayjs";
 import innerText from "react-innertext";
-import { Link } from "react-router-dom";
+import type { JSX } from "react/jsx-runtime";
```
Comment (bbovenzi) [inline airflow/ui/src/queries/useLogs.tsx]: We don't need this import

File: airflow/ui/src/components/RenderStructuredLog.tsx
Comment (aritra24) [reply airflow/ui/src/components/RenderStructuredLog.tsx:1]: Ack

File: airflow/ui/src/queries/useLogs.tsx (hunk 2 above)
Comment (aritra24) [reply airflow/ui/src/queries/useLogs.tsx]: Ack

File: airflow/ui/src/components/RenderStructuredLog.tsx [hunk 3]
```diff
@@ -0,0 +1,177 @@
...
+    if (Object.hasOwn(structured, key)) {
+      elements.push(
+        " ",
+        <chakra.span color={key === "logger" ? "fg.info" : undefined} key={`prop_${key}`}>
+          {key === "logger" ? "source" : key}={JSON.stringify(structured[key])}
+        </chakra.span>,
+      );
+    }
+  }
+
```
Comment (jscheffl) [inline airflow/ui/src/components/RenderStructuredLog.tsx]: Proposal alternative to render:
```suggestion
      return (
        <details key={error.exc_type} open={true} style={{ marginLeft: "20em" }}>
          <summary data-testid={`summary-${error.exc_type}`}>
            <chakra.span color="fg.info" cursor="pointer">
              {error.exc_type}: {error.exc_value}
            </chakra.span>
          </summary>
          {errorLines}
        </details>
      );
    });
  }

  elements.push(
    <chakra.span className="event" key={2} style={{ whiteSpace: "pre-wrap" }}>
      {event}:
    </chakra.span>,
  );

  for (const key in structured) {
    if (Object.hasOwn(structured, key)) {
      elements.push(
        " ",
        <chakra.span color={key === "logger" ? "fg.info" : undefined} key={`prop_${key}`}>
          {key === "logger" ? "source" : key}={JSON.stringify(structured[key])}
        </chakra.span>,
      );
    }
  }

  elements.push(
    <chakra.span className="event" key={2} style={{ whiteSpace: "pre-wrap" }}>
      {details}
    </chakra.span>,
  );

```

Then it would look like:
image

...and folded:
image

**Review by bbovenzi — APPROVED** [review]
Jens' suggestion looks like the right UX. Let's just rebase

**Comment by bbovenzi** [comment]
Mind updating the Logs.test.tsx? We should probably add a new test for this stacktrace change

**Comment by aritra24** [comment]
Yup, trying to get my dev setup working again. Will get fixing once I manage to get that done 🥲

File: airflow-core/src/airflow/ui/src/components/RenderStructuredLog.tsx [hunk 4]
```diff
@@ -0,0 +1,180 @@
...
+  let details;
+
+  if (errorDetail !== undefined) {
+    delete structured.error_detail;
+    details = (errorDetail as Array<ErrorDetail>).map((error) => {
+      const errorLines = error.frames.map((frame) => (
+        <chakra.p key="test">
+          File{" "}
+          <chakra.span color="fg.info" key="test">
+            &quot;{frame.filename}&quot;
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/components/RenderStructuredLog.tsx]: Not sure we need to encode there, this seem to also work
```suggestion
            "{frame.filename}"
```

File: airflow-core/src/airflow/ui/src/components/RenderStructuredLog.tsx [hunk 5]
```diff
@@ -0,0 +1,180 @@
...
+      </Code>,
+      " - ",
+    );
+  }
+
+  const errorDetail = "error_detail" in structured ? structured.error_detail : undefined;
+  let details;
+
+  if (errorDetail !== undefined) {
+    delete structured.error_detail;
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/components/RenderStructuredLog.tsx]: Not fan of the delete, we could spread and use that:

```js
const { errorDetail, ...structuredWithoutDetails} = profiles;
```

`structuredWithoutDetails` is not a good name but it's just for the example.

**Review by pierrejeambrun — APPROVED** [review]
Nice addition 🎉 

Just a couple of nits, non blocking

File: airflow-core/src/airflow/ui/src/components/RenderStructuredLog.tsx (hunk 4 above)
Comment (aritra24) [reply airflow-core/src/airflow/ui/src/components/RenderStructuredLog.tsx]: I think the linter had complained against it but I'll recheck.

File: airflow-core/src/airflow/ui/src/components/RenderStructuredLog.tsx (hunk 5 above)
Comment (aritra24) [reply airflow-core/src/airflow/ui/src/components/RenderStructuredLog.tsx]: Ack, fair I'll update it.

**Comment by aritra24** [comment]
@pierrejeambrun / @bbovenzi all review comments should now be resolved. Could you take another look?

File: airflow-core/src/airflow/ui/src/queries/useLogs.tsx [hunk 6]
```diff
@@ -16,22 +16,17 @@
  * specific language governing permissions and limitations
  * under the License.
  */
-import { chakra, Code } from "@chakra-ui/react";
+import { chakra } from "@chakra-ui/react";
 import type { UseQueryOptions } from "@tanstack/react-query";
 import dayjs from "dayjs";
 import innerText from "react-innertext";
-import { Link } from "react-router-dom";
+import type { JSX } from "react/jsx-runtime";
```
Comment (jscheffl) [inline airflow-core/src/airflow/ui/src/queries/useLogs.tsx]: Import really not needed. Can you remove? Then I think it is good to merge.
```suggestion
```

Comment (aritra24) [reply airflow-core/src/airflow/ui/src/queries/useLogs.tsx]: Oops, I think it's auto adding it somehow. I removed it a couple times. It somehow sneaks back in if I don't pay attention to the auto imports.

**Review by jscheffl — APPROVED** [review]

File: airflow-core/src/airflow/ui/src/components/renderStructuredLog.tsx [hunk 7]
```diff
@@ -0,0 +1,180 @@
...
+      </Code>,
+      " - ",
+    );
+  }
+
+  const { error_detail: errorDetail, ...reStructured } = structured;
+  let details;
+
+  if (errorDetail !== undefined) {
+    delete structured.error_detail;
```
Comment (pierrejeambrun) [inline airflow-core/src/airflow/ui/src/components/renderStructuredLog.tsx]: You don't need that anymore since we use `reStructured` from now on.

**Comment by pierrejeambrun** [comment]
@aritra24  You marked https://github.com/apache/airflow/pull/47965#discussion_r2012133830 as resolved but I still see the statement. Did you push your latest change ?

**Comment by aritra24** [comment]
Huh, I was sure I deleted it... 🤔 perhaps some commit of mine brought it back. Let me remove it once more...

**Comment by pierrejeambrun** [comment]
It's ok I just pushed it

**Comment by aritra24** [comment]
Thanks!
